### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.salesforce.androidsdk.smartsync.app.HybridAppWithSmartSync"

### ISSUE THREAD

**Issue by RichardClarkeDW** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#112]
I'm working with local cloned repos (current) and when trying to do any MobileSDK applications, including the TestApp simplest sample, I get the error

java.lang.ClassNotFoundException: Didn't find class "com.salesforce.androidsdk.smartsync.app.HybridAppWithSmartSync"

And the application fails to start

e.g.

cordova create TestApp
cd TestApp
cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin
cordova platform add android
cordova prepare
cordova emulate

This error occurs

Any ideas?

**Comment by bhariharan** [comment]
@RichardClarkeDW It looks like the library project references are incorrect. Which version of ```Cordova``` platform are you using? I have seen this error only in the newer versions of ```Cordova```, since we don't support it yet. I'd recommend using [forcedroid](https://www.npmjs.com/package/forcedroid) to generate your app. This takes care of lining up the dependencies and some other post-install steps that are required.

**Comment by Jeremywhiteley** [comment]
What version of Cordova is supported?    In the documentation it says to install Cordova.  By default it installs the latest version of Cordova.    Why don't just tell us which version to install and save us some headaches.   ???   

Sent from my iPhone

On Oct 20, 2015, at 2:27 PM, Bharath Hariharan <notifications@github.com> wrote:

@RichardClarkeDW It looks like the library project references are incorrect. Which version of Cordova platform are you using? I have seen this error only in the newer versions of Cordova, since we don't support it yet. I'd recommend using forcedroid to generate your app. This takes care of lining up the dependencies and some other post-install steps that are required.

**Comment by bhariharan** [comment]
The problem is that ```Cordova``` switched to using ```Gradle``` instead of ```ant``` to build, so it doesn't find the dependencies the same way. Instead of using ```cordova platform add android```, try ```cordova platform add android@3.6.4```. This will limit the ```Cordova``` platform version to ```3.6.4```, which should work.

**Comment by RichardClarkeDW** [comment]
See my comment in https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/970#issuecomment-149708869

I just tried this using cordova directly (forcing the android platform version) without using forcedroid

cordova create TestApp3
cd TestApp3
cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin
cordova platform add android@3.6.4
cordova prepare
cordova emulate

As is always the case the emulate fails due to the missing icon (again a clue something is messed up with the template).  I cloned icon.png to sf__icon.png.

Repeating the emulation and running the "Hello Cordova" app gives the same exception:

E/AndroidRuntime( 1300): Caused by: java.lang.ClassNotFoundException: Didn't fin
d class "com.salesforce.androidsdk.smartsync.app.HybridAppWithSmartSync" on path
: DexPathList[[zip file "/data/app/io.cordova.hellocordova-1.apk"],nativeLibrary
Directories=[/data/app-lib/io.cordova.hellocordova-1, /system/lib]]

Questions:
1 - should the sf__icon.png be included in res/drawable in the generated application?
2 - should the smartsync library be referenced in a simple hello world application?

Thanks for your help as this has cost me days of wasted time

**Comment by sevem** [comment]
Same problem. I'm using Cordova 5.3.3. With your recommended workaround to use android 3.6.4 I'm able to build a running apk, but know I got some errors during the start of the app. No problems with the app on iOS. So this might not be a general app problem

"Uncaught module com.salesforce.plugin.oauth not found", source: file:///android_asset/www/cordova.js (59)

android@3.6.4 is pretty old I think. Is there a release plan for supporting the latest Cordova version?

**Comment by RichardClarkeDW** [comment]
FYI today I uninstalled Cordova 4.3.1 and went back to 4.0.0 (based on the error message "Installed cordova command line tool version (3.6.3-0.2.13) is less than the minimum required version (4.0).  Please update your version of Cordova."

Same issues - sf__icon.png missing in the res/drawables folder and "java.lang.ClassNotFoundException: Didn't find class "com.salesforce.androidsdk.smartsync.app.HybridAppWithSmartSync""

So with forcedroid at v 3.3.1 I can't get a test app build working in the emulator with the current Cordova or v 4.0.0 or v 4.3.1

Next step for me is a clean PC and fresh installs of all the tools but I am not confident that will fix it

**Comment by bhariharan** [comment]
Cordova broke API backward compatibility with previous versions in their 4.0 platform (5.0 CLI) release. There are only 2 ways to work past the problem:

1) Downgrade Cordova CLI version and use the latest version of forcedroid/forceios to generate your app. This will automatically pull the compatible Cordova platform version (3.7).

2) Wait for Mobile SDK 4.0 release, which will support Cordova 4.0 (CLI 5+). This release is currently slated for mid-November, but keep in mind that we are waiting for Cordova to release 4.0 for iOS at this time, which will impact our release timeline. #safeharbor

We will update our documentation to include the supported Cordova versions, but unfortunately, there's little we can do if newer versions of Cordova break existing functionality by not being backward compatible with their older plugins. We share the same frustration as you do in this regard.

@RichardClarkeDW The problem you're facing is due to incorrect library project dependency path. I suspect it's an issue only on ```Windows```. Edit your project's ```project.properties``` file and ensure the filepath to the dependent library project (```SmartSync```) is correct.

@kchitalia Could you try generating an app using the latest ```forcedroid``` and check if the generated app has the correct library paths in ```Windows```?

**Comment by bhariharan** [comment]
@RichardClarkeDW Try the following steps:

* Remove the reference to ```sf__icon.png``` from your app's ```AndroidManifest.xml```. That should fix that error.
* Edit your app's ```project.properties``` file. It should have the following entry:

```android.library.reference.2=..\\..\\plugins\\com.salesforce\\src\\android\\libs\\SmartSync```

If it doesn't, add the above line in there. Let me know if you still have issues.

**Comment by RichardClarkeDW** [comment]
OK I spent a few hours on this again today without a good outcome.

Thanks @bhariharan for the suggestion to add 
android.library.reference.2=..\\..\\plugins\\com.salesforce\\src\\android\\libs\\SmartSync
to the project properties as this was missing

That assumes (?) the MobileSDK has been git cloned locally into a peer folder of my application into plugins/com.salesforce - which was not the case for me.,.

Without renaming git clone will pull local folders

- SalesforceMobileSDK-Android
- SalesforceMobileSDK-CordovaPlugin
- SalesforceMobileSDK-Samples
- SalesforceMobileSDK-Shared

So I moved these into a plugins folder and changed the project.properties reference to 

android.library.reference.2=..\\..\\..\\plugins\\SalesforceMobileSDK-CordovaPlugin\\src\\android\\libs\\SmartSync

That does resolve the missing SmartSync library but just moved the problem further along the dependency chain

SmartSync is dependent on SmartStore
android.library.reference.1=../SmartStore
that folder is there so all good

SmartStore is dependent on the SalesforceSDK
android.library.reference.1=../SalesforceSDK
that folder is there so all good

But the SalesforceSDK is dependent on the cordova framework
android.library.reference.1=../../external/cordova/framework
and that path does not exist relative to the SalesforceSDK library

And hence the build gives an error:

BUILD FAILED
C:\Program Files (x86)\Android\android-sdk\tools\ant\build.xml:573: ../../external/cordova/framework resolve to a path with no project.properties file for project C:\Users\richard.clarke.DOWHAT\TrailHybridApps\plugins\SalesforceMobileSDK-CordovaPlugin\src\android\libs\SalesforceSDK

So by manually editing the project properties to reference SmartSync I have resolved the SmartSync and SmartStore and SmartSDK dependencies.

But where should the SalesforceSDK be referencing to resolve the base cordova framework references?

Thanks

Richard

**Comment by RichardClarkeDW** [comment]
Thanks @bhariharan for the suggestion.

I added that file which was missing.  That resolves the references to SmartSync and in turn the dependency on SmartStore (which in turn depends on SalesforceSDK)

The remaining problem is the project.properties file in plugins\com.salesforce\src\android\libs\SalesforceSDK references 
android.library.reference.1=../../external/cordova/framework
which does not exist

Hence I get 
BUILD FAILED
C:\Program Files (x86)\Android\android-sdk\tools\ant\build.xml:573: ../../external/cordova/framework resolve to a path with no project.properties file for project C:\Users\richard.clarke.DOWHAT\TrailHybridApps\TestApp5\plugins\com.salesforce\src\android\libs\SalesforceSDK

I tried changing that reference to 
android.library.reference.1=../../../../../../platforms/android/cordovalib
but then the build just produces lots of errors

Any ideas?

Richard

**Comment by lingjunjiang** [comment]
Hi @bhariharan,

I got the same issue as RichardClarkeDW (the one Didn't find class "com.salesforce.androidsdk.smartsync.app.HybridAppWithSmartSync). However, after adding "android.library.reference.2=..\\..\\plugins\\com.salesforce\\src\\android\\libs\\SmartSync" in project.properties, I tested the app in 2 simulators of different SDK versions.

1. Android SDK 19 - the error doesn't show, but the app shows "Unfortunately, [app name] has stopped" without any further error message.

2. Android SDK 17 - the error still show "Didn't find class "com.salesforce.androidsdk.smartsync.app.HybridAppWithSmartSync".

Is there any restrictions regarding the version?

Thanks.

**Comment by RichardClarkeDW** [comment]
@lingjunjiang interesting you got as far as emulating the application as I don't due to errors during the corodova build.  In the SalesforceSDK plugin what library reference do you have?  Mine is set to an external/cordova/framework folder which does not exist.  Which makes me wonder what yours is set to and whether you have the framework folder?  Thanks Richard

**Comment by bhariharan** [comment]
@RichardClarkeDW Replace ```android.library.reference.1=../../external/cordova/framework``` with ```android.library.reference.1=..\\..\\external\\cordova\\framework```. The problem here is the forward slashes in the paths. ```Windows``` uses backslashes. In our ```4.0``` release, we will be fixing these problems, since we will be switching to ```Gradle```.

**Comment by RichardClarkeDW** [comment]
Thanks @bhariharan I will make that change - but in the file system there is no folder external\cordova\framework - what should have installed that or is there a different path to reference?

Also do you have an expected date for the version 4.0 SDK?

**Comment by bhariharan** [comment]
```Mobile SDK 4.0``` is tentatively set for Nov/Dec #safeharbor

Find the local path to ```Cordova``` and reference that in the file there. Meanwhile, for ```Android```, feel free to check out our ```unstable``` branch and use it, if you want to use the new ```Cordova```.

**Comment by lingjunjiang** [comment]
Thanks all.
@bhariharan @RichardClarkeDW 

As I'm working on MAC, with changing the \\ to /, it works for me now.

**Comment by RichardClarkeDW** [comment]
I am close to getting this working (current MobileSDK with Cordova@4.3.1 on Windows with forcedroid).  When I've ironed out the last two remaining issues I will document the process I have found will reliably create a working Android app.  

Two questions I am hoping someone can help with:

1 - In Salesforce under "OAuth Connected Apps" within the user record the use of OAUTH is attributed to the application "SalesforceMobileSDK Sample App" not the --appname value passed to forcedroid.  The parameter name is what Android is seeing as an app name, but not what Salesforce sees in the OAUTH process.  I can't find where "SalesforceMobileSDK Sample App" is coming from in the buiild process.  

2- Using forcedroid's "remote_hybrid" option and specifying a starting page is not working for me.  My developer org has a my domain set.  If I OAUTH login without specifying my domain I end up at a black page in the emulator after logging in.  If I OAUTH login specifying my domain I end up looking at the normal desktop Salesforce UI in the emulator with everything working, but not going to the start page as it should.

Any ideas?

OAUTH and all the calls to the MobileSDK libraries is working now.  But I do have these last two issues to sort out.

Thanks

Richard

**Comment by bhariharan** [comment]
@RichardClarkeDW Answers to your questions:

1. ```SalesforceMobileSDK Sample App``` in the ```Allow/Deny``` screen is coming from the connected app configuration. If you update your ```bootconfig.json``` to point to your connected app, you'll see the name of that connected app instead. The version of ```bootconfig.json``` that's created is only a template. It is meant to be updated to point to your connected app, as mentioned in our developer guide.

2. You'll need to specify only the endpoint that you want to load. For example, that could be something like ```/one/one.app```. We will automatically pull in the domain that you've set (for instance, ```https://login.salesforce.com```), and append the two and load the page you requested.

**Comment by RichardClarkeDW** [comment]
@bhariharan - thanks for the hints

I was changing the bootconfig.json as that is obviously a key early step.  But what I was not doing was running cordova prepare after making the change, which left the version of the same file in .\platforms\android\assets\www still pointing to the json file as it is in the mobile SDK template.

After making sure the file in ./www was correct, running cordova prepare, then double checking the version in .\platforms\android\assets\www was updated, the application name sorted itself out.

And the issue with the VisualForce page was whilst it was enabled for mobile applications I had missed setting the page headers to set the docType and turn the sidebar and showHeader to false, and that sorted out the remote page loading as it should.

So finally all working via Eclipse - although not via the cordova command line.

Look forward to the new SDK when it comes out.

So for the record in case others are stuck on getting the MobileSDK samples working (or stuck working through https://developer.salesforce.com/trailhead/trail/mobile_sdk_intro prior to the Salesforce MobileSDK version 4.0) here is what worked for me:

- install cordova@4.3.1 globally with npm (this includes the android 3.6.4 platform which is aligned with the MobileSDK 3.3)
- install forcedroid globally with npm
- run forcedroid as you would normally
- edit ./www/bootconfig.json and set the remoteAccessConsumerKey and oauthRedirectURI and api values
- clone the icon.png file to sf__icon.png in .\platforms\android\res\drawable
- edit .\platforms\android\platform.properties and make this the only reference
android.library.reference.1=..\\..\\..\\..\\AppData\\Roaming\\npm\\node_modules\\forcedroid\\libs\\SmartSync
- note the SmartSync library references SmartStore and that references the SalesforceSDK and that references the Cordova framework, so the single reference from the application resolves everything
- run cordova prepare
- validate the .\platforms\android\assets\www\bootconfig.json file matches
- note if your application appears in the Salesforce "Connected Apps OAuth Usage" as "SalesforceMobileSDK Sample App" that will be because .\platforms\android\assets\www\bootconfig.json still contains the template default values
- in Eclipse file/import from the application ONLY the application module
- in Eclipse file/import from C:\Users\USERNAMEHERE\AppData\Roaming\npm\node_modules\forcedroid\libs all three libraries SmartSync, SmartStore and SalesforceSDK (this ignores libraries and plugins pulled into the application with forcedroid)
- in Eclipse right click the application and select run-as Android application

This was the only process I have found to reliably work around the incompatibilities of the framework and SDK.  It only takes a few steps though once you have it worked out.
