### ISSUE TITLE
Bootstrap Error when starting call/sms/email from app (iOS)

### ISSUE THREAD

**Issue by plevie** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#124]
```
Error code: 1

Error description: CDVWebViewDelegate: Navigation started when state=1

Error context: AppLoading
```

When starting a call from the application with either window.open('tel:123456') or even href='tel:123456' this error occurs on second method call. So for the first call everything is ok, but when the second call is started, the application shows that error.

Same applies to sms and mailto links

**Comment by toddhalfpenny** [comment]
Could be related to this... I think I got over this by using the answer in this link (though it was some time ago).
http://salesforce.stackexchange.com/questions/66129/mobile-sdk-3-x-cordova-bug-dialer-returns-error-for-hybrid-apps

**Comment by bhariharan** [comment]
Please try this against our ```unstable``` branch, and reopen if it still exists.
