### ISSUE TITLE
Hybrid app getAuthCredentials failed in cordova container

### ISSUE THREAD

**Issue by igxz** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#129]
hi all, I am trying to build a local hybrid app that uses **SalesforceMobileSDK-CordovaPlugin**, the expected result should be user list from my Salesforce instance.  I followed every steps from https://www.youtube.com/watch?v=kLlzSWTyRjM(starts from **30:55**), I am using Windows 8.1, instead of use Andriod emulator, I add browser platform to cordova container, but after I run the app on browser, i got **"com.salesforce.oauth:getAuthCredentials failed"** exception(please see attached screen-shot), after looked at **app.js** file, it's definitely having issue talks to connected app that I created in my Sealesforce instance, and I also double checked the values of  **"remoteAccessConsumerKey"** & **"oauthRedirectURI"** properties in **bootconfig.json**. I don't know what else I have missed. Any advices will be appreciated! 

![rtaimage](https://cloud.githubusercontent.com/assets/13952193/11380870/a1e5a122-935d-11e5-9297-4da45e3dd310.png)
![rtaimage2](https://cloud.githubusercontent.com/assets/13952193/11380871/a1e8e17a-935d-11e5-9c5d-ab0f8da6f826.png)

**Comment by kchitalia** [comment]
@igxz Are you trying to run a cordova app for Android or Windows?

**Comment by wmathurin** [comment]
It will only work inside a container (i.e.Android, iOS or Windows emulators).
