### ISSUE TITLE
Using this plugin as Phonegap Build Plugin

### ISSUE THREAD

**Issue by rnng** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#135]
Hey Saleforce-Community and Cordova-plugin-developer

do you would like to contribute the Cordova-Plugin to npm so that I can use this in Phonegap Build? I am seeing no way to user this plugin in Phonegap Build.

Do you have any recommendations?

**Comment by wmathurin** [comment]
When we first released the plugin, Phonegap build didn't support plugins that contained pre-compiled binaries (like ours). That has changed a while back (http://phonegap.com/blog/2014/12/09/phonegap-build-new-features/) and we should probably revisit that decision.

**Comment by huminzhi** [comment]
The issue is fixed or solved in latest build.
