### ISSUE TITLE
Freezing dependency version

### ISSUE THREAD

**Issue by sjaakiejj** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#154]
As we were developing our application with the SalesforceMobileSDK-CordovaPlugin, we ran into an issue. Our application worked fine up until a week ago, when it started crashing whenever the app was started a second time (e.g. kill the app, open it up again) on iOS. I discovered that this was tied to an update that was pushed to the phonegap-push-plugin, that got automatically updated as the Salesforce plugin does not specify a version of the plugin to use. In order to reduce the dependency on these issues and ensure that the SDK plugin works consistently, I suggest you freeze the version of the dependencies and ensure that these are well tested.

**Comment by bhariharan** [comment]
Done [here](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/pull/174). This will be in our next release.
