### ISSUE TITLE
Callback called only once when using SmartSync syncDown/syncUp plugin method

### ISSUE THREAD

**Issue by coderReview** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#156]
When I use the following code:

``
cordova.require("com.salesforce.plugin.smartsync").syncDown(target, this.soupName, {mergeMode:sync.MERGE_MODE_DOWNLOAD.OVERWRITE}, handleSyncUpdate.bind(this));
``

The callback is called only once. Is the keep callback flag of Cordova Plugin being set for this method?

Thank you

**Comment by wmathurin** [comment]
We could have done that. But instead we are sending "sync" events to the web view.
For some sample code, please look at https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/master/samples/smartsyncexplorer/SmartSyncExplorer.html line 147/
