### ISSUE TITLE
Customer Portal + Auth Provider + Facebook Login

### ISSUE THREAD

**Issue by pt-asumra** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#161]
**PROBLEM:
When we login using Facebook it successfully redirects to the Facebook login page and if login username and password are correct then shows the authorisation of the Facebook developer app. when you press okay it goes to the Default Landing/Home Page for customer portal without dismissing the overlay web view displayed by salesforce mobile sdk. Control doesn't transfer back to the ionic cordova app after Facebook login.**

Setup: 
-> On Salesforce
1. org with customer portal
2. Site created for login to customer portal and the SiteLogin has two buttons "Login" and "Facebook Login"
3. Auth. Provider created for Facebook in both Salesforce Setup as well as Facebook developer app.
4. When click on "Facebook Login" SiteLogin redirects to the Facebook SSO URL successfully and when authorised on Facebook by the user it comes back to the Landing Page for Customer Portal which is in our case Profile Page. 
5. Created a Connected app on Salesforce
6. set the Callback Url from Auth. Provider to Salesforce Connected app.

-> On ionic cordova salesforce app for iOS
1. used the consumer key of the connected app to connect
2. Built the app and run on both simulator and device.

For the Hybrid iOS App:
This setup works well if used with salesforce login. after successful authentication the overlay login window(with webview) from salesforce mobile sdk and we are able to see our cordova ionic app top screen.

Please help us solving this issue for Facebook login.
If you want details of the dev org we can provide the details.

**Comment by wmathurin** [comment]
This is an old issue. Please re-open if it's still happening with the latest version of the Mobile SDK (6.1).
For docs on how to setup facebook as an auth provider see:
https://help.salesforce.com/articleView?id=sso_authentication_providers.htm&type=5
https://developer.salesforce.com/docs/atlas.en-us.externalidentityImplGuide.meta/externalidentityImplGuide/external_identity_provide_sso_for_mobile_apps.htm
