### ISSUE TITLE
Local Hybrid App takes user to desktop portal online page instead of local page.

### ISSUE THREAD

**Issue by lingjunjiang** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#171]
Hi buddies,

One of my clients got a weird situation. I was just wondering if anyone had met the same behaviour or known which might cause this.

The app is build upon Salesforce Mobile SDK 4 in hybrid mode, and "isLocal" is set to true in bootconfig.json file. It is running on iOS 9.2. However, the client uses a community user to login from the app and sometimes it takes him to the desktop portal (online home page) instead of local index.html file! Which is really weird for me and I cannot reproduce it anyway.

From my point of view, the only chance it opens the desktop portal is the login page doesn't return an access token, instead, it redirects to the online home page in the web view where the Oauth login page is in. So I wanted to know if this is possible?

Any insights or comments would be appreciated.

Best Regards,
Lingjun

**Comment by wmathurin** [comment]
Make sure the oauthRedirectURI in your bootconfig.json is the value you configured for the connected app on the server. Also we recommend you don't use an actual https address. Instead use something like: sfdc:///mobilesdk/oauth/done.

**Comment by lingjunjiang** [comment]
@wmathurin Thanks for the hints, I would try this and see if it would happen again or not.
