### ISSUE TITLE
PushPlugin not found error

### ISSUE THREAD

**Issue by tapan007** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#175]
I am getting a "PushPlugin not found error" when I add the following code in the callback for getAuthCredentials().

Has anyone got the following code to work?

Code: 

cordova.require("com.salesforce.util.push").registerPushNotificationHandler(
function(message) {
// add code to handle notifications
},
function(error) {
// add code to handle errors
}
);

Error in Safari when debugging:

TypeError: console.err is not a function. (In 'console.err("PushPlugin not found")', 'console.err' is undefined)﻿

**Comment by tapan007** [comment]
@bhariharan could you please suggest some workaround for now.

**Comment by lingjunjiang** [comment]
@tapan007 I had the same issue and it seems the window.plugins object doesn't exist. My workaround is  to use the window.PushNotification instead, and put the following code in the callback of getCredential:

`var push = PushNotification.init({
                android: {
                    senderID: "12345679"
                },
                ios: {
                    alert: "true",
                    badge: "true",
                    sound: "true"
                },
                windows: {}
            });

            push.on('registration', function(data) {
                // data.registrationId
                console.log('>>>> successuflly registered: ' + JSON.stringify(data));
            });

            push.on('notification', function(data) {
                console.log('>>>> received notification: ' + JSON.stringify(data));
                // data.message,
                // data.title,
                // data.count,
                // data.sound,
                // data.image,
                // data.additionalData
            });

            push.on('error', function(e) {
                console.log('>>>> received error: ' + JSON.stringify(e));
                // e.message
            });`

**Comment by bhariharan** [comment]
We have fixed ```PushPlugin``` issues in our latest patch release ```4.1.2```.
