### ISSUE TITLE
Issues with Cordova build android with SDK4.1.1 using forcedroid

### ISSUE THREAD

**Issue by khirod81** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#181]
Hi,

I tried to create a project using forcedroid, and facing some issues AndroidManifest merge.

Steps, which I followed, are below:

1.	Updated Cordova globally to - Cordova CLI: 5.4.0
2.	forcedroid create —apptype=hybrid_local --appname=mytest --targetdir=/Users/khirod/MyTest --packagename=com.myserver.mytest --usessmartstore=ye The above creates the project on my directive and I could see the below information. 
3.	Installed ios platform to 3.9.2
4.	Current plugin and platform list
Plugin list
com.salesforce 4.1.1 "SalesforceMobileSDK Plugins"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-whitelist 1.2.2 "Whitelist"
phonegap-plugin-push 1.5.0 "PushPlugin"
urbanairship-cordova 5.1.0 "Urban Airship"
Platform List
android 5.0.0, ios 3.9.2

5.	Installed shelljs@0.5.3
6.	Cordova prepare
7.	Cordova build android

Issues after the above the step.
AAPT: /Users/khirod/MyTest/mytest/platforms/android/res/drawable-mdpi/ua_ic_close.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Users/khirod/MyTest/mytest/platforms/android/res/drawable-xxhdpi/ua_ic_close.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Users/khirod/MyTest/mytest/platforms/android/res/drawable-ldpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Users/khirod/MyTest/mytest/platforms/android/res/drawable-hdpi/ua_ic_close.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
:processDebugManifest
/Users/khirod/MyTest/mytest/platforms/android/AndroidManifest.xml:53:9-58:20 Error:
	Element activity#com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity at AndroidManifest.xml:53:9-58:20 duplicated with element declared at AndroidManifest.xml:23:9-28:20
/Users/khirod/MyTest/mytest/platforms/android/AndroidManifest.xml Error:
	Validation failed, exiting
:processDebugManifest FAILED

Please suggest how I can fix these issues.

**Comment by frankyanwang** [comment]
I can build the project no problem using the same steps. But I couldn't figure out the issue with android on my nexus6: (cordova.js:59 Uncaught module com.salesforce.util.logger not found cordova.js:59) it doesn't show logon screen or display white screen. Any idea?

**Comment by huminzhi** [comment]
It seems a same issue as https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1074

**Comment by bhariharan** [comment]
@khirod81 You need to install ```shelljs@0.5.3``` first, before running ```forceios``` or ```forcedroid```. Could you post your console output from the ```forcedroid create``` step?

**Comment by bhariharan** [comment]
This is fixed in ```Mobile SDK 4.2.0```.

**Comment by khirod81** [comment]
Thank you @bhariharan. I will give a try by installing it.
