### ISSUE TITLE
Provide me  working version number for SalesforceMobileSDK-CordovaPlugin

### ISSUE THREAD

**Issue by tanaygit** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#189]
1. npm
2. cordova
3. android
4. jdk

**Comment by toddhalfpenny** [comment]
I'm not sure this is an "issue", or really the most polite request either.

I suggest that this issue is closed and you post on the either the [Google+ forum](https://plus.google.com/u/1/communities/114225252149514546445) or [StackExchange](http://salesforce.stackexchange.com/).

**Comment by bhariharan** [comment]
@tanaygit This forum is reserved for known bugs or issue in ```Mobile SDK```. For questions or other discussions, please post in our [Google+ Community](https://plus.google.com/u/1/communities/114225252149514546445), as @toddhalfpenny mentioned. I suggest you read our developer guide, which is available [here](https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/master/doc/mobile_sdk.pdf). It contains the information you're looking for.
