### ISSUE TITLE
Gradle files modify after adding SalesforceMobileSDK plugin in Cordova project

### ISSUE THREAD

**Issue by harshalijain** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#199]
Hi,

I am using Mobile SDK version 4.1.2 and cordova 6.2.0. I wish to add android platform and use a cordova plugin _cordova.plugins.diagnostic_ . Now I run following command

cordova platform add android@5.0.0
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.example.myapp
	Name: MyApp
	Activity: MainActivity
	Android target: android-23
Android project created with cordova-android@5.0.0

Installing "com.salesforce" for android
Installing "cordova-plugin-whitelist" for android

This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
	
Installing "cordova-plugin-device" for android
Installing "phonegap-plugin-push" for android
Running SalesforceMobileSDK plugin android post-install script
Moving Salesforce libraries to the correct location
Fixing Gradle dependency paths in Salesforce libraries
Fixing root level Gradle file for the generated app
include ":SalesforceSDK"

include ":SmartStore"

include ":SmartSync"

include ":SalesforceHybrid"

Moving Gradle wrapper files to application directory
Fixing application build.gradle
allprojects {
	repositories {
		mavenCentral()
	}
}
Done running SalesforceMobileSDK plugin android post-install script

Plugin "cordova-plugin-device" already installed on android. Making it top-level.
Installing "cordova-plugin-inappbrowser" for android

Dependent plugin "cordova-plugin-whitelist" already installed on android.
Installing "cordova.plugins.diagnostic" for android
Dependent plugin "phonegap-plugin-push" already installed on android.

Fixing AndroidManifest.xml file for Salesforce SDK Plugin.
Fixed AndroidManifest.xml

The command prompt output says that it changed build.gradle and settings.gradle file. But when I open the project in Android Studio , settings.gradle is reset to original version

include ":"

include ":CordovaLib"

Moreover, the line 
compile project(':SalesforceHybrid')

is also removed later from build.gradle file.

This issue arises when I try to add one more plugin other than MobileSDK plugin.
Why does this issue arise, even if the script ran succesfully to modify settings.gradle and build.gradle ?
Is there any fix to avoid resetting of build.gradle and settings.gradle file to avoid modifications?

**Comment by bhariharan** [comment]
@harshalijain The problem here is adding additional plugins after adding the ```Salesforce``` plugin. As long as the ```Salesforce``` plugin is added last, your project will be setup correctly. Check out [this blog post](https://rwhitleysfdc.wordpress.com/2016/06/07/creating-hybrid-android-apps-with-mobile-sdk-4-1-1/) by @rwhitley on how to overcome this issue.
