### ISSUE TITLE
Server changes after logging out from application in Android

### ISSUE THREAD

**Issue by harshalijain** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#201]
Hi, 
In my cordova project, I added the Salesforce MobileSDK plugin for Android platform.
While running my application, if I log into the app from Sandbox org, and then logout, the server changes to Production instead of Sandbox. I faced the issue only on Android platform, it works just as expected on iOS. Is this some configuration issue ? Please help.

**Comment by bhariharan** [comment]
This is as expected. On ```Android```, we default to the server shown on top of the server list every time the login screen is loaded, which is usually ```Production```.

**Comment by harshalijain** [comment]
Is this functionality changed in Mobile SDK v5? After upgrading to v5, it seems to be working fine now.
