### ISSUE TITLE
Passcode screen not responding on enter

### ISSUE THREAD

**Issue by harshalijain** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#211]
Hi,
I added the latest Mobile SDK to my cordova application and I observed that in Passcode screen after login,  when I tap Go button from soft input keyboard the first time, there is no response from the screen and it is stuck there forever. I am running it on Android 6.0.1 phone. Is there any work around for the same?

**Comment by bhariharan** [comment]
This is fixed in our ```unstable``` branch, and will be a part of our upcoming release ```4.3```. Stay tuned!
