### ISSUE TITLE
OAuth command does nothing when running on android

### ISSUE THREAD

**Issue by dkaskoun** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#216]
We're working on trying to get a mobile app up and running with the mobile SDK. I've tried re-setting up the app about 20 times at this point, but I've never seemed to be able to get this fully working.

I was finally able to get a project with the cordova plugin working and able to compile to my android phone, but when it gets to the point where it runs the oauthPlugin.getAuthCredentials function, nothing happens. It doesn't bring up the salesforce login, it doesn't error, it just does nothing...

I've tried getting this set up in ionic projects, straight up cordova projects, forcedroid hybrid projects, but haven't had any luck with any of them. I'm hoping that I'm just missing some setup step to get this to work on a phone. I'd really like to get it working with this plugin so we don't need to resort to developing two separate apps for android and ios. Let me know if there's any additional info that would help (versions, etc.)

**Comment by huminzhi** [comment]
Hi @dkaskoun , may we know the SDK version you are using?
I have tried forcedroid create hybrid app, it builds and runs ok.
Did you update bootconfig.json with current info?

**Comment by dkaskoun** [comment]
I've been trying with the lastest from this repo, including the build that just happened yesterday.

We finally got it to compile to ios after upgrading xcode, though, and it works fine there...

I didn't update bootconfig, but it should default to a test connected app, right? I haven't needed to update that for browser/ios compiling.

Just occurred to me you might be asking about android SDK version. I have 5.0 and 5.1 (API versions 21 and 22) installed because my phone is running 5.1 I believe.

**Comment by huminzhi** [comment]
@dkaskoun so you did 'cordova platform add android@5.0.0' then 'cordova prepare', and you are seeing the issue oauthPlugin.getAuthCredentials do nothing?

**Comment by sevem** [comment]
@dkaskoun I guess you are using Android Studio? How many projects do you have in your workspace? In some cases the Android project is not created correctly. If you see your project and some Salesforce SDK projects in your Android Studio project everything should be fine. If not, you have a problem with installing your SalesforceMobileSDK-Cordova Android plugin. There is a postinstall script which initializes your android project correctly. If you have an error here your android project does not work (e.g. wrong android platform version). And then you got the oauthplugin error because of missing project references

**Comment by dkaskoun** [comment]
I did run the platform command to set it to 5.0.0, and did do a prepare.

As for Android studio, I don't really have anything in my workspace, I specifically downloaded it for this. Far as I could tell, the Android Studio project was created correctly. I was able to open it, and the compile/run seemed to work.

Unfortunately, I don't know that I'll have a lot of time to test this again soon. Since we were able to get it to run fine on ios, which is the more important one for us at this point, we're going to mainly move forward with that, but I will try to find some time to give this another shot at some point.

**Comment by sevem** [comment]
@dkaskoun these are my steps to setup an android project

1. remove android platform if already added
cordova platform rm android

2. remove the Modile SDK plugin
cordova plugin rm com.salesforce

3. install the PushPlugin manually
cordova plugin add https://github.com/phonegap/phonegap-plugin-push --variable SENDER_ID='your.app.id'

4. add the platform android
cordova platform add android@5.0.0

5. set ANDROID_HOME
export ANDROID_HOME=/<installation location>/sdk
export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

6. ensure that the correct shelljs version is installed
npm install shelljs@0.7.0

7. add the Mobile SDK plugin
cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin

8. open the Android project in Android studio

9. keep a look on the console and upgrade gradle if necessary

**Comment by huminzhi** [comment]
@sevem Thank you for your help on this thread. @dkaskoun Are you unblocked by @sevem 's suggestion?

**Comment by dkaskoun** [comment]
I'm sorry, I haven't had a chance to retest this yet on Android. I'm trying to get at least the ios version wrapped up by the end of this week, so I may have a chance to try again next week.
