### ISSUE TITLE
Display Salesforce login screen after certain screen in Hybrid Mobile app

### ISSUE THREAD

**Issue by bhagatpravin** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#219]
Hi,

I am developing an ionic hybrid mobile app. Currently app displays Salesforce login screen (sandbox / production) after splash screen. Is there a way to display salesforce login screen after showing app introduction screen for e.g. Splash screen --> Introduction screen --> Salesforce login screen --> dashboard screen?

Thanks and regards,
Pravin

**Comment by huminzhi** [comment]
Yes, you can refer to the doc [here](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/hybrid_deferred_login.htm?search_text=shouldAuthenticate) about Defer Login

**Comment by urthakkar** [comment]
@bhagatpravin please use our [Google Community page ](https://plus.google.com/u/0/communities/114225252149514546445) for such questions.  

Please refer the documentation at https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/hybrid_deferred_login.htm?search_text=defer
