### ISSUE TITLE
Can there be on Close/back button in plugin

### ISSUE THREAD

**Issue by sudhansurana** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#221]
Hi,
IOS environment.
Can there be on Close/back button in plugin so that control comes back to app.

Regards
Sudhansu

**Comment by bhariharan** [comment]
The plugin has no UI. You can add buttons in your app's UI. This forum is reserved for known issues in the Mobile SDK. For other questions, please post [here](https://plus.google.com/u/1/communities/114225252149514546445).
