### ISSUE TITLE
SyncUp function Not updating Online Records

### ISSUE THREAD

**Issue by Subhasis-Sanyal** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#224]
We are facing issue in Mobile Application Development using Salesforce Hybrid Mobile SDK v4.3, Ionic v2.0.0, Angular.js v1.4.0, Cordova Framework v6.2.0, Cordova iOS v4.2.0 on my Mac-Mini iOS v10.11.6. The issue is being faced in SyncUp function in the Cordova SmartSync Plugin 4.3.0. The plug-in is returning success response with Offline Soup (Cache) properly updated but it is not syncing the record online. It appears either HTTP call to SFDC is not being initiated or getting chopped with unhandled error-reporting. This is because even if we run the call in offline-mode (No LAN/Wi-Fi/4G), then also same success message is received. Any help is highly appreciated. PS - We are not using Backbone Models (OOB) and instead making direct call from Angular Controller layer. 

The Success Response: 
{"detail":{"status":"DONE","target":{"modificationDateFieldName":"LastModifiedDate","idFieldName":"Id","type":"rest"},"_soupEntryId":1,"isGlobalStore":false,"maxTimeStamp":0,"totalSize":0,"type":"syncUp","progress":100,"options":{"mergeMode":"OVERWRITE"},"soupName":"SampleSyncUpTestSoup”}}

Sample Code:
var sfSmartsync = cordova.require("com.salesforce.plugin.smartsync");
var soupName = "SampleSyncUpTestSoup";
options = {
    mergeMode : "Force.MERGE_MODE.OVERWRITE",
    attributes: {type:"Contact"}
};
var data = [{
   Id: "122324354645",
   FirstName: "Robert",
   LastName: "Vadra",
   email: "Robert.Vadra@cognizant.com"
}];
function successCallback(params) {
    alert("Sync Up Sucess");
    document.addEventListener("sync", function (event) {
        console.log(JSON.stringify(event));
    }
};    
function errorCallback(error) {
    alert("Sync Up Error");
    console.log(error);
}
sfSmartsync.syncUp(soupName, options, successCallback, errorCallback);

**Comment by wmathurin** [comment]
If you don't use smartsync.js, you need to make sure your soup elements have the boolean fields \_\_locally\_created\_\_, \_\_locally\_updated\_\_ and \_\_locally\_deleted\_\_ and \_\_local\_\_. \_\_local\_\_ should be true if any of the first three are true. The application is responsible for setting those fields (when you use smartsync.js, that is done automatically for you).
Finally you need a soup index on \_\_local\_\_.

During syncUp, we look for soup elements for which \_\_local\_\_ is true and do a create/update/delete on the server based on the value of \_\_locally\_created\_\_, \_\_locally\_updated\_\_ and \_\_locally\_deleted\_\_.

(@rwhitley Maybe this needs to be highlighted in the documentation).

**Comment by Subhasis-Sanyal** [comment]
@wmathurin - Can you please provide a sample code to call this Plugin. This is not available in your SDK Samples. The Plugin is probably only way to avoid Backbone.js dependency and use any of the latest Java Script framework like Angular JS etc. Therefore, it is highly appreciated if you can add adequate documentation and code samples for the various CRUD Sync Operations using the Cordova Plugin "com.salesforce.plugin.smartsync".

**Comment by wmathurin** [comment]
The documentation for smartsync in hybrid apps can be found here: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/entity_framework_hybrid_using.htm

**Comment by wmathurin** [comment]
The documentation about the smartsync plugin specifically is to be found here: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/entity_framework_using_smartsync_plugin.htm
