### ISSUE TITLE
Whitescreen and background

### ISSUE THREAD

**Issue by mopi1402** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#230]
When the user double press on the home button (multi task mode to switch between applications), the application goes white. 
The display returns to normal when the application has focus again.

It's also append if the control center pane is open, or the notification center.

**Comment by bhariharan** [comment]
@mopi1402 Is this on `iOS`? If so, this is expected. We replace the topmost screen with a white screen before backgrounding to prevent snapshotting by `iOS` (security feature). This is by design.

**Comment by mopi1402** [comment]
Yes, this is on iOS.
Ok, so, is there a way to prevent this feature ?
I don't see anything in the source code :p

Anyway, thank you for your answer.

**Comment by khawkins** [comment]
You can, in native code.  You can either set `[SalesforceSDKManager sharedManager].useSnapshotView` to `NO`, which will turn off this practice entirely.  Or you can override the view that's displayed, via the `snapshotViewControllerCreationAction`, `snapshotPresentationAction`, and `snapshotDismissalAction` properties.  A good place to do this would be in your `AppDelegate`.

**Comment by mopi1402** [comment]
@khawkins Thank you ! :)
