### ISSUE TITLE
No SFLoginViewController equivalent in Hybrid apps?

### ISSUE THREAD

**Issue by elliottthurmannewell** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#232]
Looking to do something with the oAuth screen's navigation bar, i.e. hide it as per [this](https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/oauth_hide_gear_icon.htm) guide, but there is no **showNavbar** or **showSettingsIcon** properties I can find in the generated iOS classes for a Hybrid app.

Also for Android, it is mentioned in the documentation on [this](https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/oauth_custom_login_host.htm) page, that you can 

> The MDM policy can also hide the navigation bar and Settings icon to prevent users from changing the login host.

 for Android devices, just like iOS, but there is no page on how to do this.

Any help in this would be appreciated, I assume there must be a way around this as we cannot have one of our clients being able to change their loginURL.

**Comment by trooper2013** [comment]
@elliottthurmannewell The SFLoginViewController has not been exported in the 4.x version of the plugin. For now you could alternatively add the following SFLoginViewController.h header to the plugins group in your Xcode project. It will be exported in subsequent releases.

```


/** The Salesforce login screen view.
 */
@interface SFLoginViewController : UIViewController

/** Returns a shared singleton of `SFLoginViewController` class.
 */
+(_Nonnull instancetype)sharedInstance;

/**
 * Outlet to the OAuth web view.
 */
@property (nonatomic, strong, nullable) IBOutlet UIView* oauthView;

/** Specify the font to use for navigation bar header text.*/
@property (nonatomic, strong, nullable) UIFont * navBarFont;

/** Specify the text color to use for navigation bar header text. */
@property (nonatomic, strong, nullable) UIColor * navBarTextColor;

/** Specify navigation bar color. This color will be used by the login view header.
 */
@property (nonatomic, strong, nullable) UIColor *navBarColor;

/** Specify visibility of nav bar. This property will be used to hide/show the nav bar*/
@property (nonatomic) BOOL showNavbar;

/** Specifiy the visibility of the settings icon. This property will be used to hide/show the settings icon*/
@property (nonatomic) BOOL showSettingsIcon;

/** Applies the view's style attributes to the given navigation bar.
 @param navigationBar The navigation bar that the style is applied to.
 */
- (void)styleNavigationBar:(nullable UINavigationBar *)navigationBar;
@end
```

Hope that helps.

**Comment by elliottthurmannewell** [comment]
Hey @trooper2013, thanks for responding.

I appreciate the code, but adding that header file and specifying the property as per the docs still does not effect the navigation bar.

Using:
```
#import "AppDelegate.h"
#import "MainViewController.h"
#import "SFLoginViewController.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication*)application didFinishLaunchingWithOptions:(NSDictionary*)launchOptions
{
    self.viewController = [[MainViewController alloc] init];
    return [super application:application didFinishLaunchingWithOptions:launchOptions];
    
    SFLoginViewController *loginViewController =
    [SFLoginViewController sharedInstance];
    
    loginViewController.showNavbar = NO;
}

@end
```
in the AppDelegate class.

On a related note, is there not a version of this for Android devices?
Otherwise the SF docs are a bit misleading in saying that the navigation bar can be completely removed to prevent users using different loginURLs.

Thanks again.

**Comment by trooper2013** [comment]
@elliottthurmannewell Which version of the mobile SDK are you using? There used to be a bug prior to 4.3.1 where the application: didFinishLaunchingWithOptions wouldnt get invoked from our swizzled method. So  you have 2 options to fix this. 

[Option 1]  
Update  the return statement in the method for  AppDelegate+SalesforceHybridSDK.m - 
```
(BOOL)sfsdk_swizzled_application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

.....
 return YES;
}
```

```
(BOOL)sfsdk_swizzled_application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

.....
 return return [self sfsdk_swizzled_application:application didFinishLaunchingWithOptions:launchOptions];
}
```
[Option 2]
Initialize the SFLoginViewController in your AppDelegates init method.

Hopefully this solves your problem. I would personally use option 1 since you many have additional  bootstrapping code that you may need to add in the future for your app.

About Android, I apologize if the documentation is not clear. I will need to  find out how 
it is done. Meanwhile please try the above suggested fix for iOS.

**Comment by elliottthurmannewell** [comment]
@trooper2013 plugin.xml says 4.3.1 but xcode logs for getAuthCredentials call says 4.3.0

The first option gives this error on startup:

```
*** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[MainViewController getAuthCredentialsWithCompletionBlock:failureBlock:]: unrecognized selector sent to instance 0x7fc971d21680
```

I'm afraid native iOS is nowhere near my understanding hence the hybrid approach, so I do not really have an understanding on the class system.

**Comment by bhariharan** [comment]
@elliottthurmannewell There is an MDM setting that can be used to hide the settings icon on `Android` as well. See [this](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1119/files) pull request for details.

**Comment by elliottthurmannewell** [comment]
@bhariharan Hey Bharath, thanks for that, I'll test it out. Does that just hide the settings rather than the bar then?

Any ideas on the iOS native version as well?

**Comment by trooper2013** [comment]
@elliottthurmannewell  For iOS, the steps are just as described previously. 

You can refer to this sample project which is hybrid app(iOS) using our sdk.   

[Sample](https://www.dropbox.com/s/5gtle4ri861i0ja/My42App.zip?dl=0)

- Locate the MyApp42.xcodeproj  project file and open it in Xcode. 
- Find the AppDelegate.m in the "Classes" group of  the  Xcode project. 
- Locate the line the following line in the AppDelegate.m 
     ```
    [[SFLoginViewController sharedInstance] setShowSettingsIcon:FALSE];
    ```
- Toggle on/off the settings icon for a hybrid app. Note that the setting is achieved 
using code in objective-c.  

Hope that helps.

**Comment by elliottthurmannewell** [comment]
@trooper2013 Copying the - init method in the AppDelegate.m from that sample app into my project and adding a copy of the SFLoginController.h example worked fine :) 

Thanks for all your help with this I really appreciate it!
