### ISSUE TITLE
Cordova plugin build not working for Android 

### ISSUE THREAD

**Issue by BarunKrSingh** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#233]
I am able to run the salesforce mobile sdk application by importing the same in Android studio.
However, trying to emulate the same through  the command line using the "cordova emulate android" fails.
I see that the running the cordova CLI commands modifies build.gradle under android platform by removing the salesforce compile dependency which gets updated while we add the plugin("https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin"). As a result of this, i end up getting class not found exceptions.Would appreciate the assistance for a fix.

**Comment by Naveenbc** [comment]
@BarunKrSingh I have the same issue in android and in IOS I am not able to build in either of the ways. Please let me know if you are to find the solution.

**Comment by bhariharan** [comment]
@BarunKrSingh We don't support `cordova build` on `Android` at the moment. `Android Studio` is the way to go. We will add support in the future.

**Comment by Naveenbc** [comment]
@bariharan can you answer my few questions please?
1) I had developed a hybrid salesforce mobile app using Ionic, cordova and salesforce mobile SDK, Even that's not working now. Is it because newer version of salesforce mobile SDK is not supporting Cordova? 
2) If currently salesforce mobile SDK is not supporting Cordova, when can we expect support for hybrid apps?
Your inputs will be greatly appreciated and helpful for me. Kindly do the needful.

**Comment by bhariharan** [comment]
@Naveenbc Regarding question (1), you'll need to debug and provide more information. This forum is reserved for known bugs/issues with our plugin. For other discussions, please use our [Google+ community](https://plus.google.com/u/1/communities/114225252149514546445). Regarding question (2), we do support `Cordova`, just not `build`. You can use our plugins with `Android Studio`.

**Comment by BarunKrSingh** [comment]
@bhariharan  I appreciate the prompt response. Thank you so much for the update.

**Comment by huminzhi** [comment]
@BarunKrSingh Does @bhariharan 's answer solve the issue? May we close this issue? Thanks!

**Comment by BarunKrSingh** [comment]
@huminzhi taking his input ,we are building the app using android studio and not using a task runner.
Anyway You can close the ticket for now
