### ISSUE TITLE
Issue while running on Android 7.0 platform

### ISSUE THREAD

**Issue by harshalijain** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#234]
Hi,
With the release of Android 7.0, private libraries access have been restricted at runtime. More details in this article
http://android-developers.blogspot.in/2016/06/improving-stability-with-private-cc.html

So whenever I run my cordova application which is using SalesforceMobileSDK-Cordova Plugin, a warning in dialog box always comes up before application is launched.
Please suggest a workaround with Mobile SDK v4.1.2
![screen shot 2016-10-20 at 3 16 03 pm](https://cloud.githubusercontent.com/assets/10045610/19554908/404a9c22-96d8-11e6-8cdd-f888f1e46544.png)

**Comment by bhariharan** [comment]
@harshalijain We have upgraded to a new version of `SQLCipher` that supports `Android 7.0`. This will be in our upcoming release - `Mobile SDK 5.0`. If you want to workaround the problem in `Mobile SDK 4.1.2`, you'll have to upgrade `SQLCipher` yourself to the latest.

**Comment by harshalijain** [comment]
Thanks for your feedback, can you provide me with a guide or steps to upgrade SQLCipher in Mobile SDK 4.1.2

**Comment by wmathurin** [comment]
We don't test older versions of the Mobile SDK with newer versions of third party libraries (e.g. SQLCipher). We recommend you upgrade the Mobile SDK itself. The [dev guide](https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/master/doc/mobile_sdk.pdf) has a section on how to upgrade.
