### ISSUE TITLE
SalesforceSDK issue - App in hung state

### ISSUE THREAD

**Issue by ashvi12b** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#244]
Please fill out the following details:

1. Version of Mobile SDK Used:  v4.3.1, Cordova version - 
2. Issue found in Native App or Hybrid App: Hybrid app
3. OS Version:10.1.1 
4. Device: ipad
5. Issue: On app launch the built using SalesforceSDK. Wifi is connected, but on app launch we get "Can't connect to Salesforce. A Server with the specified hostname could not be found" error. 

This issue occurs occasionally and its not easily reproducible.  the app get this his hung state, where it need to complete uninstall and a re-install. There is no networking issue, because I'm able to hit the same salesforce endpoint and other endpoint from safari browser without any problem.

Even clicking on retry or dismiss, keep it in the  same blue screen

![salesforceerror screen](https://cloud.githubusercontent.com/assets/23531166/20404161/b5ffffd4-acd1-11e6-80ee-33f813063a0b.jpeg)

**Comment by bhariharan** [comment]
@ashvi12b What happens if you force kill the app and restart it? This just means we are unable to connect to the server at that time.

**Comment by ashvi12b** [comment]
even if we kill and re-open the app, its still in the struck mode. We had to uninstall and re-install the app. We pass the salesforce custom url through our MDM settings.

**Comment by ashvi12b** [comment]
@bhariharan  - some additional information, the SalesForce SDK is adding a additional https to the authorize endpoint. 

https://https//signetgem.my.salesforce.com/services/oauth2/authorize?.......

**Comment by bhariharan** [comment]
@ashvi12b The custom URL sent through MDM for iOS should not have the `https://` prefix. If you remove that, it should work fine.

**Comment by ashvi12b** [comment]
@bhariharan -  we do not have https:// prefixed from MDM.

AppServiceHostLabels: Signet – Production
AppServiceHosts: signetgem.my.salesforce.com

this issue is not happening on 90% of the ipad. only on 10% of the ipads we are facing this issue. When a user logs out. We initiate the process to push them back to our custom SSO login screen.  Before they are taken to our SAML login process the authorize endpoint fails and it has double https://https// in the url.

**Comment by bhariharan** [comment]
How do you initiate auth when a user logs out?

**Comment by ashvi12b** [comment]
we use SDK to perform the log out and 
const oauthPlugin = window.cordova.require("com.salesforce.plugin.oauth");
oauthPlugin.logout();

then we perform the logging back in using the below code

      oauthPlugin = window.cordova.require("com.salesforce.plugin.oauth");      
      oauthPlugin.getAuthCredentials(
            function(creds) {
                // Initialize ForceJS
                init({
                    accessToken: creds.accessToken,
                    instanceURL: creds.instanceUrl,
                    refreshToken: creds.refreshToken
                });
                resolve({ userId: creds.userId, accessToken: creds.accessToken, instanceURL: creds.instanceUrl, creds: creds });
            },
            function(error) {
                console.error(error);
                reject(error);
            }
        );

**Comment by bhariharan** [comment]
Have you tried using `oauthPlugin.getAuthCredentials` - that's the appropriate call after logout occurs.

**Comment by ashvi12b** [comment]
@bhariharan  - yes, after oauthPlugin.logout();
we are calling it,
oauthPlugin.getAuthCredentials(

**Comment by bhariharan** [comment]
@ashvi12b Sorry, what I meant was instead of calling `getAuthCredentials` after, try calling `authenticate` on the plugin after.

**Comment by awasyliuk** [comment]
@bhariharan Can you explain why this issue was closed?  This past 6 weeks we've had customers of ours with the same issue in our native iOS app.  The only workaround has been to delete the app and reinstall.
