### ISSUE TITLE
Application not restarted after Logout

### ISSUE THREAD

**Issue by harshalijain** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#259]
Hi,
In my Android application, I have enabled PIN screen. Now when my application is idle for too long, PIN screen opens up, I tap Forgot Password, and hence choose to logout of my application. I switch user, and set a new PIN, but after logging in, my application is not restarted. It continues from the same screen previously, this prevents new data and values to be downloaded for different user. Is this desired behaviour, and is there any work around possible to restart application.

**Comment by bhariharan** [comment]
@harshalijain When a logout occurs, the application will not be restarted nor will the activity context the application was in. As a framework, we don't want to make intrusive changes to the application call stack. You'll need to terminate the screens when a logout is occurring in your application.
