### ISSUE TITLE
Deferred Login in Android

### ISSUE THREAD

**Issue by mjrforce** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#264]
When setting shouldAuthenticate to false in the bootconfig, we receive the "Never Authenticated" error when we call getAuthCredentials in Android. The below code is from the SalesforceDroidGapActivity java file. No issues in iOS. 

`    public void getAuthCredentials(CallbackContext callbackContext) {
        Log.i(TAG, "getAuthCredentials called");

        if (client != null) {
            JSONObject credentials = client.getJSONCredentials();
            if (callbackContext != null) {
                callbackContext.success(credentials);
            }
        } else {
            if (callbackContext != null) {
                callbackContext.error("Never  authenticated");
            }
        }
    }`

**Comment by bhariharan** [comment]
@mjrforce You need to call the `authenticate` API on the `OAuth` plugin instead of `getAuthCredentials`.
