### ISSUE TITLE
Invasive Icons

### ISSUE THREAD

**Issue by ericwooley** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#276]
When we include this plugin, the salesforce icons overwrite our icons. 

Is this a known issue? I was surprised to not find other issues relating to this. Is there a recommended path for keeping our own icons?

**Comment by sevem** [comment]
@ericwooley on iOS or Android?

**Comment by bhariharan** [comment]
@ericwooley Yes - our `Cordova` plugin sets our icons, but you can change it as @ericwooley mentioned above.

**Comment by ericwooley** [comment]
The problem is on IOS for us. 

It just seems weird to me that this would be doing anything with icons as a Cordova plugin. It doesn't seem like a it's acting as a good citizen. Right now our build process has to do a bunch of extra things to deal with icons that seem to keep inserting themselves.

I don't understand why they are included at all. Is this plugin not really meant for the community and more built for a specific app?

**Comment by bhariharan** [comment]
@ericwooley Thank you for your feedback. Unfortunately, our plugin is a bit more intrusive than a regular `Cordova` plugin, since we have more build steps and we're a larger library in general. We will consider removing the icon in a future release.
