### ISSUE TITLE
responseHeader with new force.js in REST call

### ISSUE THREAD

**Issue by sevem** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#277]
Currently I try to switch to the Mobile SDK 5.0 and also to the new force.js library. Now I have the problem that I'm not able to get the responseHeader of a REST call. With the old forcetk.mobilesdk.js I had access to the responseHeader after doing e.g. a describe call with .... 

```javascript
forceClient.describe(objectType, function (result) {
...
    var date = arguments[2].getResponseHeader('Date');
    var lastModified = arguments[2].getResponseHeader('Last-Modified');
...
```

After switching to the new force.js library, the arguments with the responseHeader is not available. Is there a possibility to get the responseHeader of the REST call?

**Comment by bhariharan** [comment]
@sevem Could you post your feature request [here](https://github.com/ccoenraets/forcejs/issues)? That's where `force.js` originated from.

**Comment by bhariharan** [comment]
@sevem Looks like this is actually work on our side to expose the headers in our native plugin. Ignore my previous comment. We will prioritize this.

**Comment by vsvikram** [comment]
@bhariharan I'm using SDK 6.2 with the force.js apexrest method for rest API calls in an iOS hybrid app. I'm able to get the custom JSON response sent from API in successful cases but in case of error codes like 400, the JSON response which was sent from API is not available in apexrest error handler method, instead a general error log is available: "The operation couldn’t be completed. (https://xxxxxxxxx/services/apexrest/mobileSyncService error 400.)"

Could you please confirm if this is an implementation issue or the same case as above highlighted by @sevem.

Please find attached screenshot for your reference.

Success Response from API:  JSON object with one key 'status'

![screen shot 2018-11-19 at 6 08 15 pm](https://user-images.githubusercontent.com/17747628/48758387-e507b480-ecc5-11e8-82cf-cf4099f98deb.png)

Error Response: JSON object not available: only standard string

![screen shot 2018-11-20 at 1 08 56 pm](https://user-images.githubusercontent.com/17747628/48758439-0ff20880-ecc6-11e8-88df-8e224dbf1977.png)

Please help clarify this.

**Comment by akshayajeevan** [comment]
hey @bhariharan 

I am not able to get the responseHeader in the current version.
Can you please let me know if the response headers are exposed in the current version? 

Thanks.

**Comment by wmathurin** [comment]
They are not exposed currently.

**Comment by wmathurin** [comment]
The error callback is called for non successful requests (requests that don't have a 2xx status code or requests that fail to get a response).
In the next version of the mobile sdk (8.2) soon to be released, we are sending back more than just the error through the error callback.

```json
{
  "response": { 
    "headers": { ... }, 
    "statusCode": 400, 
    "body": "response-body"
  }, 
  "error": "error message - when no response was received e.g. when the server could not be reached"
}
```
For more information see:
* https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3237
* https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2095
