### ISSUE TITLE
Mobile SDK Community login with Guest User

### ISSUE THREAD

**Issue by tbalancin** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#278]
Hello Team,

I have set up the guest user like in this documentation https://goo.gl/KCFbxG to log into my community custom log in page but it fails to load the lightning component with "invalid page" error. 

If I open the page of login on browser it works normally. 

Could you please help to understand what I'm missing here to allow the guest user see the custom login page?

I have set up the app according the others topics in this doc.

Regards.

**Comment by bhariharan** [comment]
@tbalancin `Lighting Communities` have been designed to run inside a web browser and are currently not supported with the `Mobile SDK`.
