### ISSUE TITLE
MainActivity cannot be cast to com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity

### ISSUE THREAD

**Issue by GigagamOr** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#279]
Hello,
I am always running into this problem. I am aware of the other [Issue](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/168), but that one doesn't help me, as I have tried cordova platform add before or after I add the plugin - doesn't make a difference.

The project has been created with forcedroid with no errors and most importantly it used to work with platform android@5.0.0, but when I updated to the new required version (6.1.0) this error started to pop up.

The whole error message:
`java.lang.ClassCastException: com.ionicframework.event120709.MainActivity cannot be cast to com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity
                             at com.salesforce.androidsdk.phonegap.plugin.SalesforceOAuthPlugin.getAuthCredentials(SalesforceOAuthPlugin.java:109)
                             at com.salesforce.androidsdk.phonegap.plugin.SalesforceOAuthPlugin$1.run(SalesforceOAuthPlugin.java:72)
                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                             at java.lang.Thread.run(Thread.java:818)`

Any ideas?

**Comment by bhariharan** [comment]
@GigagamOr Could you try creating a new app with `forcedroid@5.0.0` and running it? How did you upgrade `cordova`? We don't support `cordova platform update` within an existing project - this could lead to unpredictable results.

**Comment by GigagamOr** [comment]
I will try it in a second.

I didn't update cordova, still 5.4.0; and I didn't actually run `cordova platform update`, I did `cordova platform rm android` and `cordova platform add android@6.1.0` (since android@5.0.0 gives me the failed version requirement error).

**Comment by SergeyLevdanski** [comment]
Hello there!

I have the same issue.

**Comment by wmathurin** [comment]
Our plugin.xml sets the main activity by using edit-config (see https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/blob/master/plugin.xml#L150) but that requires cordova 6.x.

We recommend you install the latest forcedroid and create a fresh application with it and then move you html/javascript/css into it.

**Comment by GigagamOr** [comment]
Thanks, I'll try it first thing in the morning and report back then.
