### ISSUE TITLE
iOS Unable To Launch the Startpage

### ISSUE THREAD

**Issue by amoizesmailacn** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#286]
Hi,

I  created hybrid app using Cordova using this step: 

cordova create <folder name> <package_name> <project name> 
cd <folder name>
npm init
npm install shelljs@0.7.0 --save
cordova plugin add phonegap-plugin-barcodescanner
cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin
cordova platform add android@6.1.0 

cordova platform add ios@4.3.0
copy a completed bootconfig.json file to www/
cordova prepare

The  android working fine, it calls the start page but in iOS it's odd because after the successful login, it doesn't call the star page, what's shown is white screen.

2017/03/24 05:38:11.383 hybrid[15195:1f07] DEBUG com.salesforce <SFRootViewManager>: popViewController: View controller ((null)) not found in the view controller stack.  No action taken.
2017/03/24 05:38:11.772 hybrid[15195:1b03] DEBUG com.salesforce <SFHybridViewController>: webView:decidePolicyForNavigationAction:decisionHandler: Loading URL '<custom url>/secur/frontdoor.jsp?sid=[redacted]&retURL=https%3A%2F%2F<custom_url>%2Fidex.html&display=touch'

**Comment by bhariharan** [comment]
@amoizesmailacn Could you post more logs that you see when you load the app? Have you tried to force stop the app and start it up again?

**Comment by amoizesmailacn** [comment]
@bhariharan I've tried recreating the app using the cordova create, and still the issue is the same.

Here's the log starting from login:

2017/03/27 02:23:15.360 hybridios[21401:450f] DEBUG com.salesforce <SFOAuthCoordinator>: webView:didStartProvisionalNavigation: host=<custom-domain>.my.salesforce.com : path=/
2017/03/27 02:23:15.360 hybridios[21401:850f] DEBUG com.salesforce <SFAuthenticationManager>: oauthCoordinator:didStartLoad:
2017/03/27 02:23:19.632 hybridios[21401:7cab] DEBUG com.salesforce <SFAuthenticationManager>: oauthCoordinator:didFinishLoad:error:
2017/03/27 02:23:42.153 hybridios[21401:822b] DEBUG com.salesforce <SFOAuthCoordinator>: webView:didStartProvisionalNavigation: host=<custom-domain>.my.salesforce.com : path=/_ui/identity/verification/method/EmailVerificationFinishUi/e
2017/03/27 02:23:42.153 hybridios[21401:1b4b] DEBUG com.salesforce <SFAuthenticationManager>: oauthCoordinator:didStartLoad:
2017/03/27 02:23:46.927 hybridios[21401:822b] DEBUG com.salesforce <SFAuthenticationManager>: oauthCoordinator:didFinishLoad:error:
2017/03/27 02:23:47.386 hybridios[21401:822b] DEBUG com.salesforce <SFOAuthCoordinator>: webView:didStartProvisionalNavigation: host=<custom-domain>.my.salesforce.com : path=/setup/secur/RemoteAccessAuthorizationPage.apexp
2017/03/27 02:23:47.386 hybridios[21401:1b4b] DEBUG com.salesforce <SFAuthenticationManager>: oauthCoordinator:didStartLoad:
2017/03/27 02:23:47.776 hybridios[21401:5e17] DEBUG com.salesforce <SFAuthenticationManager>: oauthCoordinator:didFinishLoad:error:
2017/03/27 02:23:53.617 hybridios[21401:5e1f] DEBUG com.salesforce <SFOAuthCoordinator>: webView:didStartProvisionalNavigation: host=<custom-domain>.my.salesforce.com : path=/_ui/identity/oauth/ui/AuthorizationPage
2017/03/27 02:23:53.617 hybridios[21401:5e1f] DEBUG com.salesforce <SFAuthenticationManager>: oauthCoordinator:didStartLoad:
2017/03/27 02:23:54.314 hybridios[21401:8237] DEBUG com.salesforce <SFAuthenticationManager>: oauthCoordinator:didFinishLoad:error:
2017-03-27 10:23:54.327 hybridios[21401:361903] Reachability Flag Status: -R ------- networkStatusForFlags
2017-03-27 10:23:54.329 hybridios[21401:361903] Reachability Flag Status: -R ------- networkStatusForFlags
2017/03/27 02:23:54.335 hybridios[21401:5e1f] DEBUG com.salesforce <SFAuthenticationManager>: oauthCoordinatorDidAuthenticate for userId: 0053B000000g1Ag, auth info: <SFOAuthInfo: 0x610000200c40, authType=SFOAuthTypeUserAgent>
2017/03/27 02:23:54.335 hybridios[21401:8237] DEBUG com.salesforce <SFIdentityCoordinator>: SFIdentityCoordinator:Starting identity request at https://test.salesforce.com/id/00D3B0000008tnLUAQ/0053B000000g1AgQAI
2017/03/27 02:23:54.337 hybridios[21401:8237] DEBUG com.salesforce <SFRootViewManager>: popViewController: View controller (<SFLoginViewController: 0x7f8f54902f40>) is now being dismissed from presentation.
2017-03-27 10:23:54.346867 hybridios[21401:364920] [] nw_host_stats_add_src recv too small, received 24, expected 28
2017-03-27 10:23:54.350530 hybridios[21401:364920] [] ____nwlog_simulate_crash_inner_block_invoke dlopen CrashReporterSupport failed
2017-03-27 10:23:54.350759 hybridios[21401:364920] [] __nwlog_err_simulate_crash simulate crash failed "nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available"
2017-03-27 10:23:54.351606 hybridios[21401:364920] [] nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available, dumping backtrace:
        [x86_64] libnetcore-856.30.16
    0   libsystem_network.dylib             0x0000000112a37666 __nw_create_backtrace_string + 123
    1   libnetwork.dylib                    0x0000000113913006 nw_socket_add_input_handler + 3164
    2   libnetwork.dylib                    0x00000001138f0555 nw_endpoint_flow_attach_protocols + 3768
    3   libnetwork.dylib                    0x00000001138ef572 nw_endpoint_flow_setup_socket + 563
    4   libnetwork.dylib                    0x00000001138ee298 -[NWConcrete_nw_endpoint_flow startWithHandler:] + 2612
    5   libnetwork.dylib                    0x0000000113909ae1 nw_endpoint_handler_path_change + 1261
    6   libnetwork.dylib                    0x0000000113909510 nw_endpoint_handler_start + 570
    7   libnetwork.dylib                    0x00000001139211f9 nw_endpoint_resolver_start_next_child + 2240
    8   libdispatch.dylib                   0x00000001127b4978 _dispatch_call_block_and_release + 12
    9   libdispatch.dylib                   0x00000001127de0cd _dispatch_client_callout + 8
    10  libdispatch.dylib                   0x00000001127bbe17 _dispatch_queue_serial_drain + 236
    11  libdispatch.dylib                   0x00000001127bcb4b _dispatch_queue_invoke + 1073
    12  libdispatch.dylib                   0x00000001127bf385 _dispatch_root_queue_drain + 720
    13  libdispatch.dylib                   0x00000001127bf059 _dispatch_worker_thread3 + 123
    14  libsystem_pthread.dylib             0x0000000112b874de _pthread_wqthread + 1129
    15  libsystem_pthread.dylib             0x0000000112b85341 start_wqthread + 13
2017/03/27 02:23:55.650 hybridios[21401:83b3] DEBUG com.salesforce <SFKeychainItemWrapper>: setObject:forKey: Value already stored in the keychain. No action taken.
2017/03/27 02:23:55.652 hybridios[21401:1b4b] DEBUG com.salesforce <SFUserAccountManager>: Replacing temp user identity with <SFUserAccount username=(null) fullName=(null) accessScopes={(
    api,
    web
)} credentials=<SFOAuthKeychainCredentials: 0x61800035a2b0, identifier="3MVG9snqYUvtJB1PQHwOYmcfaMdxujlJhUI7fLUOZ31pLBsYaYb7JZVoOUfOSHmC5yuM6u1zDA_263sjNfSZz-1172053209" clientId="3MVG9snqYUvtJB1PQHwOYmcfaMdxujlJhUI7fLUOZ31pLBsYaYb7JZVoOUfOSHmC5yuM6u1zDA_263sjNfSZz" domain="<custom-domain>.my.salesforce.com" identityUrl="https://test.salesforce.com/id/00D3B0000008tnLUAQ/0053B000000g1AgQAI" instanceUrl="https://<custom-domain>.my.salesforce.com" communityId="(null)" communityUrl="(null)" issuedAt="2017-03-27 02:23:49 +0000" organizationId="00D3B0000008tnLUAQ" protocol="https" redirectUri="ios://auth/success">, community=(null)>
2017/03/27 02:23:55.665 hybridios[21401:83b3] INFO com.salesforce <SalesforceSDKManagerWithSmartStore>: Authentication (SFOAuthTypeUserAgent) succeeded.  Launch completed.
2017/03/27 02:23:55.665 hybridios[21401:5e1f] INFO com.salesforce <AppDelegate>: Post-launch: launch actions taken: SFSDKLaunchActionAuthenticated
2017-03-27 10:23:55.666 hybridios[21401:361903] Apache Cordova native platform version 4.3.0 is starting.
2017-03-27 10:23:55.667 hybridios[21401:361903] Multi-tasking -> Device: YES, App: YES
2017-03-27 10:23:55.670 hybridios[21401:361903] Reachability Flag Status: -R ------- networkStatusForFlags
2017/03/27 02:23:55.671 hybridios[21401:83b3] DEBUG com.salesforce <SFAuthenticationManager>: addSidCookieForDomain: <custom-domain>.my.salesforce.com
2017-03-27 10:23:55.683 hybridios[21401:361903] [CDVTimer][handleopenurl] 0.064969ms
2017-03-27 10:23:55.686 hybridios[21401:361903] [CDVTimer][intentandnavigationfilter] 2.898991ms
2017-03-27 10:23:55.686 hybridios[21401:361903] [CDVTimer][gesturehandler] 0.095963ms
2017-03-27 10:23:55.687 hybridios[21401:361903] [CDVTimer][localstorage] 0.373006ms
2017-03-27 10:23:55.687 hybridios[21401:361903] [CDVTimer][TotalPluginStartup] 4.274964ms
2017/03/27 02:23:56.376 hybridios[21401:1b4b] DEBUG com.salesforce <SFHybridViewController>: webView:decidePolicyForNavigationAction:decisionHandler: Loading URL 'https://<custom-domain>.my.salesforce.com/secur/frontdoor.jsp?sid=[redacted]&retURL=https%3A%2F%2Fap2.salesforce.com%2Fone%2Fone.app&display=touch'

Note: Custom-Domain is our URL prefix. Thanks

**Comment by amoizesmailacn** [comment]
Hi @bhariharan 

Hope you can help on this issue. 
Please let me know what I'm missing out.

I tried this approach too: 
[Developing Hybrid Remote Apps](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/hybrid_develop_hybrid_remote.htm)

unfortunately, the white screen still exist.
Thank

here's the sample logs: 

2017/03/27 03:00:24.361 fileexplorer[24816:9317] DEBUG com.salesforce <SFKeychainItemWrapper>: setObject:forKey: Value already stored in the keychain. No action taken.
2017/03/27 03:00:24.364 fileexplorer[24816:a207] DEBUG com.salesforce <SFUserAccountManager>: Replacing temp user identity with <SFUserAccount username=(null) fullName=(null) accessScopes={(
    api,
    web
)} credentials=<SFOAuthKeychainCredentials: 0x610000148da0, identifier="3MVG9YDQS5WtC11pG06U2rQ7pUSRf.emo1A17CTqiLUZBjLic49VK59MDMg0UDfD7HimI5URUZNjYfCZB7IyF-3103343629" clientId="3MVG9YDQS5WtC11pG06U2rQ7pUSRf.emo1A17CTqiLUZBjLic49VK59MDMg0UDfD7HimI5URUZNjYfCZB7IyF" domain="login.salesforce.com" identityUrl="https://login.salesforce.com/id/00D6F000001flHuUAI/0056F000006u3AdQAI" instanceUrl="https://ap4.salesforce.com" communityId="(null)" communityUrl="(null)" issuedAt="2017-03-27 03:00:17 +0000" organizationId="00D6F000001flHuUAI" protocol="https" redirectUri="test://success">, community=(null)>
2017/03/27 03:00:24.371 fileexplorer[24816:9317] INFO com.salesforce <SalesforceSDKManagerWithSmartStore>: Authentication (SFOAuthTypeUserAgent) succeeded.  Launch completed.
2017/03/27 03:00:24.371 fileexplorer[24816:a207] INFO com.salesforce <AppDelegate>: Post-launch: launch actions taken: SFSDKLaunchActionPasscodeVerified|SFSDKLaunchActionAuthenticated
2017-03-27 11:00:24.373 fileexplorer[24816:423045] Apache Cordova native platform version 4.3.0 is starting.
2017-03-27 11:00:24.373 fileexplorer[24816:423045] Multi-tasking -> Device: YES, App: YES
2017-03-27 11:00:24.375 fileexplorer[24816:423045] Reachability Flag Status: -R ------- networkStatusForFlags
2017/03/27 03:00:24.377 fileexplorer[24816:9317] DEBUG com.salesforce <SFAuthenticationManager>: addSidCookieForDomain: ap4.salesforce.com
2017-03-27 11:00:24.399 fileexplorer[24816:423045] [CDVTimer][handleopenurl] 0.092983ms
2017-03-27 11:00:24.401 fileexplorer[24816:423045] [CDVTimer][intentandnavigationfilter] 1.721978ms
2017-03-27 11:00:24.402 fileexplorer[24816:423045] [CDVTimer][gesturehandler] 0.063002ms
2017-03-27 11:00:24.402 fileexplorer[24816:423045] [CDVTimer][localstorage] 0.320017ms
2017-03-27 11:00:24.402 fileexplorer[24816:423045] [CDVTimer][TotalPluginStartup] 3.028989ms
2017/03/27 03:00:25.061 fileexplorer[24816:a10b] DEBUG com.salesforce <SFHybridViewController>: webView:decidePolicyForNavigationAction:decisionHandler: Loading URL 'https://ap4.salesforce.com/secur/frontdoor.jsp?sid=[redacted]&retURL=https%3A%2F%2Fap4.salesforce.com%2Fapex%2FFileExplorer&display=touch'

**Comment by bhariharan** [comment]
@amoizesmailacn There are a couple of problems that I see here from your logs:
1. Your login domain isn't correctly set. See this log line:
```2017/03/27 02:23:56.376 hybridios[21401:1b4b] DEBUG com.salesforce : webView:decidePolicyForNavigationAction:decisionHandler: Loading URL 'https://.my.salesforce.com/secur/frontdoor.jsp?sid=[redacted]&retURL=https%3A%2F%2Fap2.salesforce.com%2Fone%2Fone.app&display=touch'```
How and where are you setting your custom login host in the app?
2. The simulator you're using appears to have some issues:
```2017-03-27 10:23:54.350530 hybridios[21401:364920] [] ____nwlog_simulate_crash_inner_block_invoke dlopen CrashReporterSupport failed
2017-03-27 10:23:54.350759 hybridios[21401:364920] [] __nwlog_err_simulate_crash simulate crash failed "nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available"```
Have you tried resetting the simulator?

Which version of `Mobile SDK` are you using? Could you try running one of our hybrid sample apps out of the box to verify they work with your credentials?

**Comment by amoizesmailacn** [comment]
Hi @bhariharan 

I found the fix in this bug, here's the step on how I resolved it:

In Xcode, open your hybrid remote project.
In the Project Navigator, expand the Plugins folder.
Select the AppDelegate+SalesforceHybridSDK.m file.
In the code editor, find the setupRootViewController method definition.
On the right-hand side of the self.viewController assignment, add a userUIWebView:YES argument to the end of the parameter list:

```
self.viewController = [[SFHybridViewController alloc]
    initWithConfig:(SFHybridViewConfig*)
        [SalesforceSDKManager sharedManager].appConfig 
     useUIWebView:YES];
```

Please see this [link](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/hybrid_develop_hybrid_remote.htm).

**Comment by bhariharan** [comment]
I wasn't aware you were using `localhost` in your app. If so, that's only supported in `UIWebView` and not in `WKWebView`. This is by design due to limitations on `WKWebView`.
