### ISSUE TITLE
Error : No resource found that matches the given name (at 'icon' with value '@drawable/sf__icon')

### ISSUE THREAD

**Issue by EssenKh** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#287]
Whenever I create ionic project and i add the SalesforceMobileSDK plugin, when i import my project to android studio to build and run it. I receive this error. I already read issues about this problem but i didn't find a solution.
Regards

**Comment by bhariharan** [comment]
@EssenKh This forum is reserved for bugs/issues in our code. For setup related issues, please use our `Google+ community` [here](https://plus.google.com/u/1/communities/114225252149514546445).
