### ISSUE TITLE
Error: No resource found that matches the given name (at 'icon' with value '@drawable/sf__icon').

### ISSUE THREAD

**Issue by EssenKh** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#291]
Please fix the default AndroidManifest.xml file.
I get this error when i add cordova plugin to ionic project ( ionic 2.2.2) using this command:
ionic plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin
from: [https://github.com/ccoenraets/ionic-starter-salesforce](https://github.com/ccoenraets/ionic-starter-salesforce)
`Error: No resource found that matches the given name (at 'icon' with value '@drawable/sf__icon').`
While running: ionic run android --device or when I compile from Android Studio
Maybe you should change the icon to sf__icon
Best Regards

**Comment by EssenKh** [comment]
@bhariharan

**Comment by bhariharan** [comment]
@EssenKh This indicates that our post-install script was not run and hence, our libraries aren't in the correct location. The `ionic` steps you've mentioned do not include `Android` platform addition, which explains why the post-install script wasn't run. Please use our `forcedroid` package from [here](https://www.npmjs.com/package/forcedroid) to generate a hybrid app and then import the generated app in `Android Studio`. I have verified that it works as expected.

**Comment by EssenKh** [comment]
Hi,
is that means that i can't use ionic framework with Salesforce Mobile SDK
to release my project ?
Best Regards

2017-04-08 17:58 GMT+01:00 Bharath Hariharan <notifications@github.com>:

**Comment by bhariharan** [comment]
We haven't verified with `ionic` - it probably works with `iOS`. On `Android`, if you choose to use `ionic` you'll need to manually run the post-install script to move libraries to the correct location. We are working on removing the post-install script so that it will work out of the box in a future release.

**Comment by EssenKh** [comment]
​How can i run the psot-install script to move libraries to the correct
location ? can you explain me more. Maybe i  will work on that If i have
permissions .
Best Regards ​

2017-04-08 18:05 GMT+01:00 Bharath Hariharan <notifications@github.com>:

**Comment by bhariharan** [comment]
The script is under the `tools/` folder of our plugin and setup as a plugin hook. You'll need to run `node tools/postinstall-android.js` after adding our plugin. Then, you need to import the generated app in `Android Studio`.

Note: `cordova build` does NOT work at this time.

**Comment by EssenKh** [comment]
​How can i run the psot-install script to move libraries to the correct
location ? can you explain me more. Maybe i  will work on that If i have
permissions .
Best Regards ​

**Comment by bhariharan** [comment]
See my comment [here](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/291#issuecomment-292732304).

**Comment by EssenKh** [comment]
Adding the Cordova plugin version 4.3.0 doesn't genrate this error, and the application run successfully. But without displaying data and no pop up for allowing access ( on external device). do you have an idea about this issue ?

**Comment by bhariharan** [comment]
You'll need to debug your hybrid resources to see what's failing.

**Comment by EssenKh** [comment]
Even if it is added as it is shown on the terminal: debugging show: `plugin not found `

**Comment by bhariharan** [comment]
This forum is for known issues/bugs with our platform. Please use our Google+ community for any other questions/discussions.

**Comment by EssenKh** [comment]
@bhariharan any news about this issue, you told me that you are working on removing the post-install script so that it will work out of the box in a future release. is there any news ?
Thank you
Regards

**Comment by bhariharan** [comment]
@EssenKh We have removed many parts of the post-install script and consolidated them to a few simple steps. Give it a shot with `Mobile SDK 5.1`.

**Comment by EssenKh** [comment]
@bhariharan Thank you, always compiling from android studio. can I use cordova commands ?
Best Regards

**Comment by bhariharan** [comment]
@EssenKh Probably not fully compatible on that front. We still recommend `Android Studio` or `gradle` command line.

**Comment by EssenKh** [comment]
@bhariharan  
ionic plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#5.1.0
returns this error:
```
Error: Failed to fetch plugin https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin via git.
Either there is a connection problems, or plugin spec is incorrect:
Error: C:\Program Files\Git\bin\git.exe: Command failed with exit code 1
Error output:
```
error: pathspec '5.1' did not match any file(s) know to git

**Comment by bhariharan** [comment]
@EssenKh Your tag is incorrect. It should be `#v5.1.0` at the end.

`ionic plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v5.1.0`
