### ISSUE TITLE
Repository "https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin" checked out to git ref " master"

### ISSUE THREAD

**Issue by EssenKh** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#296]
Repository "https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin" checked out to git ref " master" 
while running: 
cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin

**Comment by bhariharan** [comment]
@EssenKh Yeah - `master` is the default branch that it pulls from. What's the issue? If you need a specific version, say `5.1.0`, you can run:
`cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v5.1.0`
