### ISSUE TITLE
registerPushNotificationHandler don't get callback when user click on iOS push notification alert. 

### ISSUE THREAD

**Issue by frankvlocity** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#297]
I have facing an (iOS) issue that when click on iOS push notification registerPushNotificationHandler don't get callback while app is coming back from background. It works for my Android Nougat system. It also works when app is in foreground.

Here is my code snippet. iOS background app don't get callback.
```
cordova.require("com.salesforce.util.push").registerPushNotificationHandler(
	function(data) {
		console.log("PUSH MSG: ", data);
		// add code to handle notifications
		console.log("register push notifications.");
		var payload = data["message"];
		if (_.get(data, "additionalData.foreground")) {
                       // works for both iOS and android
		}
		if (!_.get(data, "additionalData.foreground")) {
                      // works only for Android. 
		}
	},
	function(error) {
		// add code to handle errors
		console.log("Failed to register push notifications.");
	}
);
```

Please help!

**Comment by bhariharan** [comment]
@frankvlocity Are you getting the callback on the native portion of the `PushPlugin`? Which version of `Mobile SDK` are you using? We're now using the stock `Cordova PushPlugin` for the most part, except for the `Salesforce` registration bit.

**Comment by frankvlocity** [comment]
@bhariharan haven't tried debugging on native portion of code, only debug on JS part. I am using SalesforceMobileSDK-CordovaPlugin v5.0.0. It was the same behavior of v4.3.0. any idea? I will try to debug on native part.

**Comment by bhariharan** [comment]
@frankvlocity I think this is an issue with the `PushPlugin` - it's not really under our control or in our code. Perhaps you could file an issue with them [here](https://github.com/phonegap/phonegap-plugin-push)?

**Comment by sebas00** [comment]
@frankvlocity  I fixed it by changing the code as in the issue mentioned above, as well as updating the phonegap-plugin-push to version  1.10.5 : "phonegap-plugin-push": "^1.10.5"

**Comment by frankvlocity** [comment]
@sebas00 I actually had applied the same fix as your check in at that time. But it still don't give callback for IOS in the background. Android works fine. Is the plugin upgrade actually fix the issue? I can give it a try again.

**Comment by sebas00** [comment]
@frankvlocity  It worked for me like this: I removed the SalesforceMobileSDK plugin, added the latest version of the push plugin then added the SFMobileSDK again. 

I created a pushfix.js file for the changed code, and call that instead of the salesforce push plugin from the login callback on index.html. You can find it here:
https://gist.github.com/sebas00/80d43e1b18d2ab52447b38c6b73b5c8c

**Comment by frankvlocity** [comment]
@sebas00  ok I will give it a try and let you know. Thanks!

**Comment by frankvlocity** [comment]
@sebas00  can you also show me the PR code how you fix it?  I just want to make sure I have it the same way.
