### ISSUE TITLE
Cordova add plugin fails in Forcedroid create on Win 10, Win 8.1 and Mac 10.12

### ISSUE THREAD

**Issue by 8Bhatb** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#300]
Please fill out the following details:

Reference to issue #1411 (https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1411)

Disclaimer : This is my first time posting an  issue, please be gentle :). I tried this on new VMs for Windows 10 and 8.1 and a clean macbook. All of them returned the same issue. Could someone use forcedroid on a fresh install and confirm it works without issues

1. Version of Mobile SDK Used: 5.1.0 (didnt specify a version, forcedroid seems to pull 5.1.0)
Node v7.10.0
NPM v4.2.0
GIT 2.12.2.2
2. Issue found in Native App or Hybrid App: hybrid remote
3. OS Version: Windows 10.1 Pro, Windows 8.1 Pro, Mac OSX 10.12 Sierra, 
4. Device: Android
5. Steps to reproduce: https://trailhead.salesforce.com/modules/mobile_sdk_hybrid/units/mobilesdk_hybrid_getting_started
6. Actual behavior:
forcedroid fails with an EISDIR error. This happens during 
cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v5.1.0 --force
On further research, the error is thrown in sha.get(p,function()) inside add-local-tarball.js. sha.get is expecting a file, instead, a directory in tmp folder is passed.
7. Expected Behavior:
forcedroid create succeeds and 
8. Error Log:
Errorlog attached
[2017-05-07T02_49_29_953Z-debug.log.txt](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/files/981533/2017-05-07T02_49_29_953Z-debug.log.txt)

**Comment by bhariharan** [comment]
@8Bhatb Looking at the logs, it doesn't look like something we're explicitly doing that's causing this issue. I have verified on my `Unix` machine that it works fine. Unfortunately, I don't have a `Windows` machine to try this on.
```
31 verbose checkoutTreeish HEAD is now at 24a997d... Merge pull request #294 from bhariharan/master
32 info git [ 'submodule', '-q', 'update', '--init', '--recursive' ]
33 verbose updateSubmodules git+https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin.git#v5.1.0 submodule update
34 error addLocal Could not install C:\Users\root\AppData\Local\Temp\npm-3564-c06ba0e7\git-cache-ac9445e6\24a997d4581941c692b26bae755b2c5360fff306
35 silly fetchPackageMetaData Error: EISDIR: illegal operation on a directory, read
35 silly fetchPackageMetaData  error for https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v5.1.0 { Error: EISDIR: illegal operation on a directory, read errno: -4068, code: 'EISDIR', syscall: 'read' }
36 silly rollbackFailedOptional Starting
```
Looks like an issue with `node` or `npm` itself in your environment. Have you tried looking online for solutions?

**Comment by 8Bhatb** [comment]
Thanks for the update @bhariharan .

I looked for anyone else who faced this issue, no luck.

What version of linux are you using. No luck with Windows and Mac, but I can try linux.

**Comment by bhariharan** [comment]
I am using `Mac 10.12.4`.

**Comment by 8Bhatb** [comment]
And it worked as expected with Mac 10.12.4?

**Comment by bhariharan** [comment]
Yes.

**Comment by 8Bhatb** [comment]
Thanks @bhariharan . I assume you reinstalled node, npm and cordova before frying out forcedroid.

I am trying again on a fresh build Win 10 VM. Will shoot the exact details out.

Curious to understand what the Build status means, Its saying failed for Cordova Plugin as well as Android SDK page, atleast for android-25. Is that the reason for the issue

**Comment by bhariharan** [comment]
@8Bhatb `Build status` is inaccurate and a little misleading - it's broken due to environmental issues and doesn't represent the status of the project itself. If it helps, my `npm` version is `3.10.5` and my `node` version is `v6.2.2`. Could you try with those versions?

**Comment by 8Bhatb** [comment]
No luck. Have tried with the two versions on couple of Macs, no luck.

Is there a way to add SDK to an existing project and create a hybrid_remote interface in that project. I am starting this this, can I create an activitity which will use the SDK and let me connect to a VF page.
https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/android_update_maven.htm

**Comment by bhariharan** [comment]
@8Bhatb Yes, that's possible. The way to do it would be to launch `SalesforceDroidGapActivity` and launch the `URL` you want within the `WebView` there.

**Comment by bonalupraveenkumar** [comment]
Hi ,

I am facing the same issue with Mac 10.12.4 os.
Has anyone found the solution for it .Please provide me with the instructions.

Thanks
Praveen

**Comment by bhariharan** [comment]
These steps should work:
```
sudo npm install -g forcedroid
forcedroid create
```
Go through the prompts to create a `hybrid_remote` app.
Open the generated app in `Android Studio` and run it.

**Comment by 8Bhatb** [comment]
Hi @bonalupraveenkumar 

Here is my solution to the problem. Please adjust for Mac accordingly
The problem is in CordovaPlugin available here . The repository does not contain a package.json file. This file is used for calculating checksum for creating a tarball. But since it was not there, it failed and caused the complete installation to fail.

To get around, I created my own package.json and added to a repository I cloned from here, then I ran forcedroid with that repository and it worked.

So to fix, you need to locate constants.js, for me it was located in c:\Users\root\AppData\Roaming\npm\node_modules\forcedroid\shared\. You might have a local and global instance of installation, change in both constants.js In the javascript, you need to locate plugin repository line and replace with my repository as shown below.

**Before**
var VERSION = '5.1.0';

module.exports = {
    version: VERSION,

    tools: {
        gitMinVersion: '2.10',
        npmMinVersion: '3.10',
        podMinVersion: '1.1'
    },
    
    cordova: {
        //pluginRepoUri: 'https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#dev',    // dev
        pluginRepoUri: 'https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v' + VERSION, // GA
        minimumCliVersion: '6.4.0',
        platformVersion: {
            ios: '4.3.0',
            android: '6.1.2'
        }
    },	

**After**
var VERSION = '5.1.0';

module.exports = {
    version: VERSION,

    tools: {
        gitMinVersion: '2.10',
        npmMinVersion: '3.10',
        podMinVersion: '1.1'
    },
    
    cordova: {
        //pluginRepoUri: 'https://github.com/8Bhatb/SalesforceMobileSDK-CordovaPlugin#dev',    // dev
        pluginRepoUri: 'https://github.com/**8Bhatb**/SalesforceMobileSDK-CordovaPlugin', // GA
        minimumCliVersion: '6.4.0',
        platformVersion: {
            ios: '4.3.0',
            android: '6.1.2'
        }
    },

Once you have done that, you need to make sure ANDROID_HOME environment variable is set correctly to Android SDK location. Do a “echo %ANDROID_HOME%” on command prompt. For me, the Android SDK is present in C:\Users\root\AppData\Local\Android\sdk

**Comment by bhariharan** [comment]
@8Bhatb @bonalupraveenkumar `Cordova CLI 7.0.0` is not supported on `Mobile SDK 5.1` because of the `package.json` requirement. We have fixed this in our `dev` branch and will support that in our next version. Meanwhile, please use `Cordova CLI 6.4.0` for `Mobile SDK 5.1`.

**Comment by bonalupraveenkumar** [comment]
@bhariharan @8Bhatb  Thank you very much.I will try it and will let you guys know .

Thanks

**Comment by bonalupraveenkumar** [comment]
Thank you @bhariharan @8Bhatb  ..It worked for me .I had to install cordova 6.4.0 to resolve the issue
