### ISSUE TITLE
smartstore.client not working on iOS

### ISSUE THREAD

**Issue by devfelipereis** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#301]
Hello!

I started a project using Android and I'm using promises with "navigator.smartstoreClient". It's everything working fine.

Today I tryed to run my app on iOS but my functions that is using smartstoreClient are not working.
The code is not passing in the success or catch block, nothing is happening.

Any ideias?

**Comment by wmathurin** [comment]
Could you tell us what version of the SDK you are using and also what iOS device / OS version you have tried to run it on?

**Comment by devfelipereis** [comment]
I was checking the versions by the tags and I see that version 4.2.0 of this SDK does not have smartstoreClient. I see that is working on Android cause I'm using version 5.0.0 there.
But when I try to install 5.0.0 on iOS, it gives me an error to install 4.2.0.

I'm running on iOS 3.92. How to run version 5.0.0+ on iOS? Thank you!
