### ISSUE TITLE
Blank screen using iOS

### ISSUE THREAD

**Issue by devfelipereis** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#302]
Hello!

I'm trying to build my app for iOS but Im getting a blank screen.

I got this from logs:

`2017-05-09 11:08:09.291 SGF_Mobile[287:14671] useProxy: false
2017-05-09 11:08:09.292 SGF_Mobile[287:14671] force init
2017-05-09 11:08:09.293 SGF_Mobile[287:14671] soup exists test
2017/05/09 14:08:09.301 SGF_Mobile[287:3b07] DEBUG com.salesforce <SFSmartStorePlugin>: SFSmartStorePlugin pluginInitialize
2017/05/09 14:08:09.303 SGF_Mobile[287:3b07] DEBUG com.salesforce <SFSmartStorePlugin>: pgSoupExists jsVersion:5.1.0 
2017/05/09 14:08:09.303 SGF_Mobile[287:3b07] DEBUG com.salesforce <SFSmartStorePlugin>: pgSoupExists called.
2017/05/09 14:08:09.303 SGF_Mobile[287:3b07] DEBUG com.salesforce <SFSmartStorePlugin>: pgSoupExists with soup name 'Fiscal_Relatorio__c'.
2017/05/09 14:08:09.310 SGF_Mobile[287:3b07] DEBUG com.salesforce <SFSmartStore>: initWithName:user:isGlobal: defaultStore, user: 00DJ0000003H1hRMAS-005J0000006HAfO-(null), isGlobal: 0
2017/05/09 14:08:09.311 SGF_Mobile[287:3b07] INFO com.salesforce <SFSmartStoreUpgrade>: Migrating stores from legacy locations, where necessary.
2017/05/09 14:08:09.312 SGF_Mobile[287:3b07] INFO com.salesforce <SFSmartStoreUpgrade>: Legacy SmartStore directory does not exist.  Nothing to do.
2017/05/09 14:08:09.312 SGF_Mobile[287:3b07] INFO com.salesforce <SFSmartStoreUpgrade>: No legacy stores to migrate.
2017/05/09 14:08:09.313 SGF_Mobile[287:d03] INFO com.salesforce <SFSmartStoreUpgrade>: Updating encryption method for all stores, where necessary.
2017/05/09 14:08:09.316 SGF_Mobile[287:d03] INFO com.salesforce <SFSmartStoreUpgrade>: Number of stores to update: 1
2017/05/09 14:08:09.317 SGF_Mobile[287:d03] DEBUG com.salesforce <SFSmartStoreUpgrade>: Store 'defaultStore' currently does not employ encryption.`

When my code starts working with database, it runs a soupExists "pgSoupExists with soup name 'Fiscal_Relatorio__c'." and then the log shows a lot of stuff that I don't understand and something like:

Legacy SmartStore directory does not exist.  Nothing to do.

Do I need to do something about this?

In the xcode, I also get this:

`dyld`dyld_fatal_error:
->  0x1fe1b08c <+0>: trap   
    0x1fe1b090 <+4>: nop    `

All this is happening after login. I can log in but then I got the blank screen.

I'm using xcode 8.2.1, cordova 6.4.0, iOS 4.3.0 and Salesfroce SDK 5.1.0.

Any ideias? Thanks!

**Comment by bhariharan** [comment]
@devfelipereis Are you upgrading from a previous version of `Mobile SDK` or is this a fresh install of your app? If this is an upgrade, which version of `Mobile SDK` are you upgrading from? This line appears to indicate it's an upgrade:
```
INFO com.salesforce <SFSmartStoreUpgrade>: Number of stores to update: 1 2017/05/09 14:08:09.317 SGF_Mobile[287:d03] DEBUG com.salesforce <SFSmartStoreUpgrade>: Store 'defaultStore' currently does not employ encryption.
```
Also, what's the exact stack trace of the crash shown in the console?

**Comment by devfelipereis** [comment]
It's a fresh install. I started on Android and it's working fine there. Then, I'm trying to run on iOS.

I have some news... I started again and now I see that my soups are being created and it works.
Sadly, it is just working in my emulator. When I install in a real device(I'm using an Ipad), it's not working.

I'm getting:

`dylddyld_fatal_error:
-> 0x1fe1b08c <+0>: trap
0x1fe1b090 <+4>: nop `

and this link contains the full logs from xcode: https://pastebin.com/tzmPA5v3

In the line 1807, I got this:

2017/05/10 12:25:26.972 SGF_Mobile[980:a81f] DEBUG com.salesforce <SFSmartStorePlugin>: pgSoupExists with soup name 'Fiscal_Relatorio__c'.

This is my fist check and it should run for more soups in my application and then create soups, etc... In tthis case is just running once and nothing is happening.

**Comment by bhariharan** [comment]
@devfelipereis A couple of things stand out in your stack trace:
```
2017/05/10 12:25:04.348 SGF_Mobile[980:852b] DEBUG com.salesforce <SFAuthenticationManager>: oauthCoordinator:didStartLoad:
2017/05/10 12:25:06.652 SGF_Mobile[980:7107] DEBUG com.salesforce <SFAuthenticationManager>: oauthCoordinator:didFinishLoad:error:
2017/05/10 12:25:08.355 SGF_Mobile[980:852b] DEBUG com.salesforce <SFOAuthCoordinator>: webView:didStartProvisionalNavigation: host=cs10.salesforce.com : path=/_ui/identity/oauth/ui/AuthorizationPage
2017/05/10 12:25:08.355 SGF_Mobile[980:852b] DEBUG com.salesforce <SFAuthenticationManager>: oauthCoordinator:didStartLoad:
2017/05/10 12:25:18.247 SGF_Mobile[980:8437] DEBUG com.salesforce <SFAuthenticationManager>: oauthCoordinator:didFinishLoad:error:
2017/05/10 12:25:18.256 SGF_Mobile[980:7107] DEBUG com.salesforce <SFAuthenticationManager>: oauthCoordinator:didBeginAuthenticationWithView
2017/05/10 12:25:18.257 SGF_Mobile[980:7107] DEBUG com.salesforce <SFRootViewManager>: pushViewController: View controller (<SFLoginViewController: 0x16d30e10>) is already presented.
```
The snippet above indicates that authentication is getting canceled because it's getting back an error and kicking off the error callback and it attempts to kick off authentication again. Eventually, authentication is successful, but after that, this happens:
```
2017/05/10 12:25:18.612 SGF_Mobile[980:8437] DEBUG com.salesforce <SFDefaultUserAccountPersister>: Unable to enumerate the content at /var/mobile/Containers/Data/Application/756D981D-C2E8-462F-82DA-28A70E676717/Library/com.pandoapps.sgfmobile/Preferences.plist: Error Domain=NSCocoaErrorDomain Code=256 "The file “Preferences.plist” couldn’t be opened." UserInfo={NSUnderlyingError=0x16e6d1b0 {Error Domain=NSPOSIXErrorDomain Code=20 "Not a directory"}, NSFilePath=/var/mobile/Containers/Data/Application/756D981D-C2E8-462F-82DA-28A70E676717/Library/com.pandoapps.sgfmobile/Preferences.plist, NSUserStringVariant=(
    Folder
)}
2017/05/10 12:25:18.615 SGF_Mobile[980:8437] DEBUG com.salesforce <SFDefaultUserAccountPersister>: Unable to enumerate the content at /var/mobile/Containers/Data/Application/756D981D-C2E8-462F-82DA-28A70E676717/Library/com.pandoapps.sgfmobile/Preferences.plist: Error Domain=NSCocoaErrorDomain Code=256 "The file “Preferences.plist” couldn’t be opened." UserInfo={NSUnderlyingError=0x16e26790 {Error Domain=NSPOSIXErrorDomain Code=20 "Not a directory"}, NSFilePath=/var/mobile/Containers/Data/Application/756D981D-C2E8-462F-82DA-28A70E676717/Library/com.pandoapps.sgfmobile/Preferences.plist, NSUserStringVariant=(
    Folder
)}
```
I suspect this could be `Keychain` access related, but basically, we're unable to persist or retrieve credentials successfully and that's required for the app to work. Could you try this on a different device? There's no reason for the app to not work on device given that it works on the simulator.

**Comment by devfelipereis** [comment]
At moment I don't have another ipad to test. I did some research about "Keychain" but nothing that could help.

**Comment by bhariharan** [comment]
@devfelipereis We don't do anything device specific. It sounds like a specific issue with the `iPad` you're using. There's not a whole lot we can do at this time. You could try resetting the `iPad` or testing against a different `iPad`. You could also post on our community [here](https://plus.google.com/u/1/communities/114225252149514546445) to check with anyone else has run into similar issues.
