### ISSUE TITLE
Using External Storage for Large Soup Elements

### ISSUE THREAD

**Issue by devfelipereis** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#305]
Hello!

From https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/offline_external_storage.htm

I have this:

"Create a soup spec object. Configure this object with the soup name and a list of features that includes external storage."

How can I use this feature in my app?

When I call "navigator.smartstore.getSoupSpec('Relatorio__c_Fotos')" for example, it doesn't return an object. 

From this sdk, I see that the code is doing this:

`var SoupSpec = function (soupName, features) {
    this.name = soupName;
    this.features = features;
};`

Any examples or something to help me use external storage?

Thank you!

**Comment by bhariharan** [comment]
@devfelipereis This forum is meant for known issues or bugs with the `Mobile SDK` code. For other questions, please use our [Google+ community](https://plus.google.com/u/1/communities/114225252149514546445).
