### ISSUE TITLE
Failed to fetch plugin https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v5.1.0 via registry

### ISSUE THREAD

**Issue by bingwang0** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#306]
npm ERR when running forcedroid.  Is this repo missing pakcage.json?

Full error message:

_forcedroid failed

Command failed: cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v5.1.0 --force
Error: Failed to fetch plugin https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v5.1.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 235 Error output:
npm ERR! addLocal Could not install /var/folders/w0/54_b87c544b49z2bq3pz08hs8c12kq/T/npm-31216-25870b70/git-cache-ac7f8006/24a997d4581941c692b26bae755b2c5360fff306
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v5.1.0" "--save"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm **not being able to find a package.json** in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bwang/Documents/Xcode/TrailHybridApps1/node_modules/npm-debug.log_

**Comment by bhariharan** [comment]
@bingwang0 This is caused by a breaking change in `Cordova CLI 7.0.0`. Please downgrade to `Cordova CLI 6.4.0` and use `forcedroid`. We will support `Cordova CLI 7.0.0` in our next release.

**Comment by bingwang0** [comment]
Thanks!

**Comment by bruceyue** [comment]
When can we use Cordova CLI 7.0.0?

**Comment by bhariharan** [comment]
@bruceyue It's already fixed in `dev` and will be a part of our next release (`5.2.0`).

**Comment by bruceyue** [comment]
When the  next release (5.2.0) will coming?

**Comment by bhariharan** [comment]
We don't have a release date yet, but probably around August. #safeharbor
