### ISSUE TITLE
Plugin is broken on IOS because cordova-plugin-wkwebview-engine

### ISSUE THREAD

**Issue by EladZucker** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#307]
wkedbview-engine have serious issues with CORS and it seems the plugin using it. so nothing really works (no access to file:// or any remote server).

**Comment by bhariharan** [comment]
For `XHR` requests, please use `force.js`. This routes requests through our native network plugin. `XHR` requests without origin won't work in `WKWebView`. This forum is for known bugs/issues with the code. For other discussions, please use our Google+ community.
