### ISSUE TITLE
Authorization login page

### ISSUE THREAD

**Issue by jsanz1209** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#308]
We are developing a hybrid application that integrates with Salesforce SDK 4.3.1 version.
We have created a custom login page in Visualforce and a landing controller that redirects to the autorization page. 
Being at the authorization page, if the user denies the access, it turns back to the login page but it seems that the height has been modified by the autorization page and now the login page looks bad (watch video). It happens in all Android devices which we have tested (with Android 5, 6 or 7). 
Is possible to personalize the autorization page and avoid this behavoir? Or is possible not to use the authorization page?﻿

https://youtu.be/DtN_25TUFxU

**Comment by bhariharan** [comment]
@jsanz1209 We don't control the authorization page - we simply display it within a `WebView`. Please take a look at [Salesforce Help](help.salesforce.com) for articles that allow you to configure the auth flow in your org. This would require server side configuration.
