### ISSUE TITLE
Could not find Force.SObject in www/SmartSync js plugin

### ISSUE THREAD

**Issue by vivekweb** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#309]
I am bit new to Hybrid app development and currently using this plugin in Ionic. By following the instructions, i did registerSoups, syncDown and few more. 
w.r.t to below guide, i am trying to use Force.Sobject but it is not found in"www/com.salesforce.plugin.smartsync.js" file
https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/entity_framework_hybrid_using.htm
Any ideas to setup in Ionic ?
Thanks

**Comment by wmathurin** [comment]
You need to include [smartsync.js](https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/master/libs/smartsync.js) if you want to use Force.SObject 

Also please use our Google community for such queries and benefit from larger developer audience on the platform. https://plus.google.com/u/1/communities/114225252149514546445
