### ISSUE TITLE
Create fails 

### ISSUE THREAD

**Issue by gabesumner** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#311]
I added something very simple to the default Hybrid app created by "forceios":

force.create("Account", {"Name": "Acme Inc."}, function() {}, function(error){alert(error);});

It returns an error of:

The operation couldn't be completed https://(myurl)/services/data/v39.0/sobjects/Account?Name=Acme%20Inc. error 400

The GET/QUERY operations work fine, but attempting to POST/CREATE results in an error.

**Comment by bhariharan** [comment]
We have fixed this issue in our `dev` branch [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2021). The fix will be a part of our next release. Meanwhile, you could generate new binaries from the `dev` branch of our source repo and stick them in your app to get unblocked, or you could use `Mobile SDK 5.0.1`.
