### ISSUE TITLE
App Crashing IOS 9.3

### ISSUE THREAD

**Issue by thiagosjk** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#313]
Hello all,

I'm using Mobile SDK 5.1 with iOS and I'm trying to run it in a device with iOS 9.3.
My app is crashing on device but it works on emulator.

I'm getting this error on xcode:

dylddyld_fatal_error:
-> 0x1fe1b08c <+0>: trap
0x1fe1b090 <+4>: nop `

It's just happening in version 9.3 and it works for 10+.

Is anyone else here getting the same error?

I'm using xcode 8.2.1, cordova 6.4.0, iOS 4.3.0 and Salesfroce SDK 5.1.0.﻿

How can I debug a bit better the error? the message "dylddyld_fatal_error" is not so helpful

**Comment by bhariharan** [comment]
@thiagosjk How did you create the app? We need more info than just a crash to investigate the issue.

**Comment by wmathurin** [comment]
The issue was also report [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/1986). We believe it's an iOS bug fixed in 9.3.2 (see [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/1986#issuecomment-308589514) for more details).
