### ISSUE TITLE
forceios create Failing when installing temp files

### ISSUE THREAD

**Issue by GH4Arlene** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#318]
Am upgrading from Salesforce Mobile SDK 4.3 to 5.1.  From the npm-debug.log:

31 verbose checkoutTreeish HEAD is now at 24a997d... Merge pull request #294 from bhariharan/master
32 info git [ 'submodule', '-q', 'update', '--init', '--recursive' ]
33 verbose updateSubmodules git+https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin.git#v5.1.0 submodule update
34 error addLocal Could not install /var/folders/ns/_mbtz1bx54z71n7sm7y809100000gn/T/npm-31964-5e673263/git-cache-04654069/24a997d4581941c692b26bae755b2c5360fff306
35 silly fetchPackageMetaData Error: EISDIR: illegal operation on a directory, read
35 silly fetchPackageMetaData     at Error (native)
35 silly fetchPackageMetaData  error for https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v5.1.0 { Error: EISDIR: illegal operation on a directory, read
35 silly fetchPackageMetaData     at Error (native) errno: -21, code: 'EISDIR', syscall: 'read' }

however, the dir referenced above in  /var/folders.....   was created  (drwxr-xr-x) with several files and dirs in it.

node v6.7.0
npm v3.10.3
cordova-ios v4.3.0
cordova-cli v7.0.1

Do I have a version mis-match in my toolbox?

**Comment by wmathurin** [comment]
This is caused by a breaking change in Cordova 7.0.0. Please use Cordova 6.4.0 with this plugin.
