### ISSUE TITLE
POST requests failing in 5.1.0

### ISSUE THREAD

**Issue by fnijenhuis** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#331]
I've posted my issue on the Google + community, but I get no response there, so let me try it in here.

We’re doing an upgrade of the SalesforceMobileSDK framework (to version 5.1.0). For the iOS platform we encounter the problem that sending a POST request to Salesforce results in an error. We’ve traced these requests up until the pgSendRequest method (com.salesforce.plugin.network) in libSalesforceHybridSDK.a. Input seems to be fine, but the response is the following:

"The operation couldn’t be completed. (https://xyz.salesforce.com/services/apexrest/RESTWebserviceApp/UserInfo/getUserInfo?userId=xxxx error 400.)"

I have replaced our org with xyz and the actual user id with xxxx.
For the error above input to this method was the following:

{
  "endPoint": "/services/apexrest",
  "path": "/RESTWebserviceApp/UserInfo/getUserInfo",
  "method": "POST",
  "queryParams": {
    "userId": “xxxx”
  },
  "headerParams": {},
  "fileParams": {}
}

This goes for all POST requests, the one above is just an example.

I think the framework builds the request in the wrong way. It seems to send the parameters (in above example the user id) as a query string instead of as a JSON body. I can reproduce this scenario with POSTMAN. When I send the user id as JSON body I get a good result, but if I send it as a query string I get a HTTP 400 Bad request.

Not sure if it is related, but we also see the following message a lot in the logs:
A background URLSession with identifier com.salesforce.network already exists!

I really hope to get some help on this, as this has been blocking the upgrade to 5.1.0 for quite a while now.

Thanks in advance!

**Comment by bhariharan** [comment]
@fnijenhuis We have fixed this in `Mobile SDK 5.2.0`. Please upgrade to `5.2.0`. Thanks!
