### ISSUE TITLE
Build with cordova for ionic 1 project failed with "AAPT: No resource found that matches the given name (at 'icon' with value '@drawable/sf__icon')"

### ISSUE THREAD

**Issue by Ryssa** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#334]
I'm facing a problem trying to build an app using this plugin with ionic@1.7.16.

I tried everything using cordova@7.0.0 since using cordova@6.5.0 I got the following warning when adding android platform:

`plugin doesn't support this project's cordova version. cordova: 6.5.0, failed version requirement: >=7.0.0
Skipping 'phonegap-plugin-push' for android`

So I installed cordova@7.0.0 and this warning is gone. However, I still cannot build the app for android.

I executed the following commands:

`ionic start projectTest salesforce`

`cordova platform add android@6.2.3`

`cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin --force`

And the plugins installed after this are:

``` com.salesforce 5.2.0 "SalesforceMobileSDK Plugins"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.0.0 "PushPlugin" 
```

But when running `cordova run android` I got the error:

`/platforms/android/build/intermediates/manifests/full/debug/AndroidManifest.xml:35:23-41: AAPT: No resource found that matches the given name (at 'icon' with value '@drawable/sf__icon').`

Any thoughts?

**Comment by bhariharan** [comment]
@Ryssa That error indicates that the required post install steps weren't run. Please use `forcedroid` to create your hybrid app. Also, `cordova run` is currently not supported. As mentioned in our developer guide, please import the generated app in `Android Studio` and then run the app.

**Comment by jorgeartigas** [comment]
@Ryssa  hey I'm facing the same issue when running "ionic cordova run android" with

Salesforcemobilesdk-cordovaplugin: 9.2.0
Cordova CLI: 10.0.0 (cordova-lib@10.1.0)
Cordova Platforms : android 10.1.0

did you find any solutions?
