### ISSUE TITLE
Running 'cordova build' after 'forcedroid create' breaks with an error about 'no resource found'

### ISSUE THREAD

**Issue by alsocalledchris** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#337]
Error message is:

No resource found that matches the given name (at icon with value drawable/sf__icon)

Reproduce by running the below commands:

`forcedroid create`
(create a hybrid_remote )
cd into directory
`cordova build`

See the error. Means that updating the android platforms folder with any changed assets is a manual task if cordova build does not work.

**Comment by wmathurin** [comment]
That error indicates that the required post install steps weren't run. 
What version of forcedroid are you using, was there any error when you ran the create.
Also, `cordova build` is currently not supported. As mentioned in our developer guide, please import the generated app in Android Studio and then run the app.

**Comment by alsocalledchris** [comment]
@wmathurin  thanks for your response. 

I'm running the latest version (5.2.0) of forcedroid - no other errors were seen. Can I run the post-install scripts manually as a temp fix?

Where does it mention that cordova build command is not supported? (As manually fixing the error seems to suggest the build works OK.) I'm not seeing it mentioned in https://www.npmjs.com/package/forcedroid nor https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/preface_intro.htm nor https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/master/doc/mobile_sdk.pdf - if you could point me at the documentation I need to read that would be appreciated.

I would rather not use Android studio as I would like to keep my build process within the cordova tooling - and potentially use PhoneGap build servers - is this not possible/officially supported?

Thanks again.

**Comment by wmathurin** [comment]
Currently the only way to build an application that uses Cordova + Mobile SDK on Android is in Android Studio. Using build servers (e.g. PhoneGap build) is not currently supported.
