### ISSUE TITLE
External Soup error in Android

### ISSUE THREAD

**Issue by dfattlar** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#338]
When querying an external soup with a SmartSQL query (ex. select {Account:_soup} from {Account}) iOS correctly returns the soup items, but Android returns this error: 
JSONException
Value at 0 is null

If the 'features:["externalStorage"]' flag is removed on soup init, you can query the soup as expected without JSON error.

I noticed this while using SDK v5.0.1, so I upgraded to v5.2.0 and still get the error. 
Running on Galaxy Tab A, Android v7.0

I am able to recreate this with both large and small data sets. I set up a smaller set for testing, it had indices for Id and Name, the Description field did not have an index.
select {Account:Id} from {Account} - returns correct ids
select {Account:Name} from {Account} - returns correct list of Names
select {Account:Description} from {Account} - no index
select {Account:_soup} from {Account} - JSONException  Value at 0 is null

**Comment by wmathurin** [comment]
We will investigate thanks.

**Comment by wmathurin** [comment]
We cannot reproduce the issue (see new test referenced in PR above).
Please re-open if you can provide more repro steps.
