### ISSUE TITLE
411 http error code

### ISSUE THREAD

**Issue by angelsalazar** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#340]
Hi guys,
I am developing a mobile application for my salesforce community using the forceios library you provide. This application is meant to be used for creating cases through our clients mobile devices.

I recently run into the following issue when trying to create a case through my mobile app.
Below you can find the error I got every time I tried to create a case ( I use the function create present on the force library).

`The operation couldn’t be completed. (https://portal-anm.cs14.force.com/services/data/v39.0/sobjects/Case error 411.)`

I know that 411 means that the Content-Length header is missing, but I am assuming that the force library will add that on my behalf. Apparently it does not or maybe I am getting that error for another reason which I do not know as it only says error 411.

Anyway I did couple test before writing this issue.

1) Log in through the community
Apparently I am not able to create cases when I logged in to my mobile app through the community. (I got the same error which I provided above).

2) Log in through the sandbox
When logging in through my sandbox everything is fine, as I am able to create the cases.

After those tests, I thought my problem has to be with the domain used to make the api calls.
So I tested the endpoints with my salesforce and community domain using postman.

3) Community domain (https://portal-anm.cs14.force.com/services/data/v39.0/sobjects/Case/)
Headers
Content-Type : application/json
Authorization : Bearer myoauthtoken

Body
```
{
      "Subject" :  "POSTMAN CASE 2",
      "RecordTypeId" : "012c00000009KxcAAE",
      "Type" : "Salesforce",
      "Priority" : "Low",
      "Case_Category__c" : "Other",
      "Description" :"Some Case"
}
```

the Response I got was successful.

4) Salesforce domain (https://anm--portal.cs14.my.salesforce.com/services/data/v39.0/sobjects/Case/)
Headers
Content-Type : application/json
Authorization : Bearer myoauthtoken

Body
```
{
      "Subject" :  "POSTMAN CASE 1",
      "RecordTypeId" : "012c00000009KxcAAE",
      "Type" : "Salesforce",
      "Priority" : "Low",
      "Case_Category__c" : "Other",
      "Description" :"Some Case"
}
```

the Response I got was successful.

After testing the endpoints with the different domains and getting a successful response I do not know how to solve this problem, could you help me out or provide me hints about what may be causing the error?

I am using
forceios version 5.2.0
ForceJS - REST toolkit for Salesforce.com Version: 1.0
cordova version 7.0.1
OS macOS Sierra version 10.12.6

PS.
I tried to add the Content-Length header, but when doing the request the app shuts down.

**Comment by wmathurin** [comment]
We have fixed a content-length related bug a while back.

I just tried with the latest code.
```javascript
 force.create("Case", {
                "Subject" :  "POSTMAN CASE 2",
//                "RecordTypeId" : "012c00000009KxcAAE",
                "Type" : "Salesforce",
                "Priority" : "Low",
//                "Case_Category__c" : "Other",
                "Description" :"Some Case"
            }, function(result) {
            alert("result->[" + result + "]");
        }, function(error) {
            alert("error->[" + error + "]");
            }
        );
```
And was able to successfully create case(s).

Could you upgrade forceios and make sure you also use the latest [force.js](https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/master/libs/force.js).

Please re-open if you are still having the issue.
