### ISSUE TITLE
sendRequest with GET method and JSON body

### ISSUE THREAD

**Issue by mopi1402** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#343]
Hi,
Finally, I migrate to SalesForce Mobile SDK from 4.3 to 5.2 because 4.3 is not compatible anymore with latest iOS version.

I was using CordovaHTTP to manage requests outside WKWebView and I'm using GET method with JSON content in some APEX calls.

Now I'm using SFDC Mobile SDK 5, I don't need CordovaHTTP anymore, but I've not succeed to send a valid request with GET method and JSON content.

It's seems I can only send params if I'm not using POST, PATCH, PUT. see :
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/0dcd036ba365affd255d5054a06554f112101891/libs/SalesforceHybridSDK/SalesforceHybridSDK/Classes/Plugins/SFNetworkPlugin/SFNetworkPlugin.m

So, may you please tell me if I can send JSON content in the body, with a GET method ?

It will be a pity if I'm still need CordovaHTTP to process GET with JSON content.

Thank you for your help !

**Comment by wmathurin** [comment]
Why would you have a body on a REST request?
According to Roy Fielding:

> Any HTTP request message is allowed to contain
a message body, and thus must parse messages with that in mind.
Server semantics for GET, however, are restricted such that a body,
if any, has no semantic meaning to the request.
So, yes, you can send a body with GET, and no, it is never useful
to do so.

See [here](https://groups.yahoo.com/neo/groups/rest-discuss/conversations/messages/9962)

**Comment by mopi1402** [comment]
Sorry, my bad.

I had a bug and NetworkPlugin was crashing... I think this is because I'd forgotten to URLEncode my variables, or may be cause I was sending null and undefined as string. 
Now it's working like a charm.
