### ISSUE TITLE
Command failed: cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v5.3.0 --force

### ISSUE THREAD

**Issue by ksakuda** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#348]
How do you troubleshoot the following? - Issue with forceios with Hybrid app:

Command failed: cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v5.3.0 --force
Error: Failed to fetch plugin https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin via git.

**Comment by wmathurin** [comment]
Are you running forceios or forcedroid? 
Could you do `forceios create --verbose` and report back what it says around the error.

**Comment by wmathurin** [comment]
Re-open when you can provide more details and have established that it is not a setup issue on your dev box (as it seems to be).

**Comment by AudoVeliz** [comment]
hello @wmathurin 
i am facing the same issue but with "forcehybrid", here you have the details using forcehybrid create --verbose

Thank you in advance

Enter the target platform(s) separated by commas (ios, android): Audos-MacBook-Air:~ audocastedo$ forcehybrid create --verbose
Enter the target platform(s) separated by commas (ios, android): ios,android 
Enter your application type (hybrid_local, hybrid_remote): hybrid_local
Enter your application name: MyTrailHybridLocal
Enter your package name: com.mytrail.hybrid
Enter your organization name (Acme, Inc.): MyTrail, Inc.
Enter output directory for your app (leave empty for the current directory): TrailHybridApps
Invalid value for output directory (directory must not already exist): 'TrailHybridApps'.
Enter output directory for your app (leave empty for the current directory): TrailHybridApps

********************************************************************************
*
*   Creating ios and android hybrid_local application using Salesforce Mobile SDK
*     with app name:        MyTrailHybridLocal
*          package name:    com.mytrail.hybrid
*          organization:    MyTrail, Inc.
*   
*     in:                   TrailHybridApps
*   
*     from template repo:   https://github.com/forcedotcom/SalesforceMobileSDK-Templates#v6.0.0
*          template path:   HybridLocalTemplate
*          plugin repo:     https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v6.0.0
*
********************************************************************************

Creating a new cordova project.
/Users/audocastedo/TrailHybridApps /Users/audocastedo
+ shelljs@0.7.0
added 16 packages in 2.251s
/Users/audocastedo
/Users/audocastedo/TrailHybridApps /Users/audocastedo
Using cordova-fetch for cordova-ios@4.5.4
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.mytrail.hybrid
	Name: MyTrailHybridLocal
iOS project created with cordova-ios@4.5.4
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Saved plugin info for "cordova-plugin-whitelist" to config.xml
--save flag or autosave detected
Saving ios@~4.5.4 into config.xml file ...
/Users/audocastedo
/Users/audocastedo/TrailHybridApps /Users/audocastedo
Using cordova-fetch for cordova-android@7.0.0
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.mytrail.hybrid
	Name: MyTrailHybridLocal
	Activity: MainActivity
	Android target: android-26
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@7.0.0
Android Studio project detected
Android Studio project detected
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
          
--save flag or autosave detected
Saving android@~7.0.0 into config.xml file ...
/Users/audocastedo
/Users/audocastedo/TrailHybridApps /Users/audocastedo
Installing "com.salesforce" for android
Plugin dependency "cordova-plugin-whitelist@1.3.3" already fetched, using that version.
Dependent plugin "cordova-plugin-whitelist" already installed on android.
Failed to install 'com.salesforce': CordovaError: Failed to fetch plugin cordova-plugin-device@1.0.1 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:205:33
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:864:24)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
/Users/audocastedo
forcehybrid failed

Command failed: cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v6.0.0 --force
Error: Failed to fetch plugin cordova-plugin-device@1.0.1 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module

**Comment by bhariharan** [comment]
@AudoVeliz Which version of `node` are you using? `node@6.x` is supported, but `node@8.x` is unsupported.

**Comment by DavinCasey** [comment]
I'm also getting this error:

`forcehybrid failed

Command failed: cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v6.1.0 --force`

Node v6.2.2
NPM v5.7.1
MacOS v10.13.3

Any ideas?

**Comment by bhariharan** [comment]
Could you post the verbose full output of the CLI?

**Comment by JuanCiordia** [comment]
Hi @bhariharan do you know when node@8.x will be supported?

**Comment by bhariharan** [comment]
@JuanCiordia It's already supported in our latest release (`6.2.0`).

**Comment by JuanCiordia** [comment]
@bhariharan I still get the "Command failed: cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v6.2.0 --force" error

any tip?

**Comment by bhariharan** [comment]
@JuanCiordia What's the full console output?
