### ISSUE TITLE
GET requests not returning anything in 5.3.0

### ISSUE THREAD

**Issue by mcekol** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#353]
I have an issue when querying a custom apex rest resource on salesforce after the upgrade to 5.3.0:
I'm using 
`force.apexrest('/services/apexrest/TestRestApi*', function(a) {  console.log(a); });`
from the console and logging the output.

This works:
```
@RestResource(urlMapping='/TestRestApiSObject')
global with sharing class TestRestApiSObject {

    @HttpGet
    global static Account get() {
        Account a = [SELECT Id, Name, Phone, Website FROM Account LIMIT 1];
        
        return a;
    }
}
```

It returns an account record.

This fails:
```
@RestResource(urlMapping='/TestRestApiBoolean')
global with sharing class TestRestApiBoolean {

    @HttpGet
    global static Boolean get() {
        return true;
    }
}
```
It returns null instead of true.

this also fails:
```
@RestResource(urlMapping='/TestRestApiDate')
global with sharing class TestRestApiDate {

    @HttpGet
    global static Date get() {
        return Date.today();
    }
}
```
It returns null instead of the date.

this also fails:
```
@RestResource(urlMapping='/TestRestApiString')
global with sharing class TestRestApiString {

    @HttpGet
    global static String get() {
        return 'Hello World!';
    }
}
```
It returns null instead of 'Hello World'.

I haven't tested other data types. Is this expected behavior? Everything was working before the upgrade (I was using 4.1.1).

forceios version 
5.3.0
cordova -v 
7.0.1

Please let me know if you need additional information.

**Comment by wmathurin** [comment]
Starting with 5.0 you need to use [force.js](https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/master/libs/force.js) instead of [forcetk.mobilesdk.js](https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/3fbc536965cd3611ddce5444b3d41fdb2824f269/libs/forcetk.mobilesdk.js).
With force.js, the network calls are routed through the native network stack.
forcetk.mobilesdk.js was using XHR from the webview directly which won't work (because of CORS enforcements in WKWebView).

**Comment by mcekol** [comment]
I am using force.js instead of forcetk.mobilesdk.js. And I do see network call routed through the native network stack.

What can I do to better demonstrate the issue I'm facing?

**Comment by wmathurin** [comment]
We will investigate. Thanks.

**Comment by an-rahulpandey** [comment]
Any update on this, I am also facing the same when return the string data.

**Comment by FawadNL** [comment]
Hello, we are also facing the same issue. Any updates?

**Comment by fishme** [comment]
Waiting also for some good news

**Comment by areichert** [comment]
@wmathurin - Long time since October 3 - any updates?

**Comment by sevem** [comment]
facing the same problems ... getting more and more seriously

**Comment by an-rahulpandey** [comment]
Is there any source available for iOS SDK?

**Comment by fishme** [comment]
looks not - only for android is the source code available. :(

**Comment by wmathurin** [comment]
The source code is also availabe for iOS - it lives in the SalesforceMobileSDK-iOS repo.
The class of interest here is: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceHybridSDK/SalesforceHybridSDK/Classes/Plugins/SFNetworkPlugin/SFNetworkPlugin.m

**Comment by wmathurin** [comment]
Fix for iOS: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2287
Fix for Android: https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1557
Will be in the next release.

**Comment by FawadNL** [comment]
How can I install the plugin with the Salesforce SDK containing the above fix which you added?

**Comment by wmathurin** [comment]
You need to clone the main iOS and Android repo, cherry pick the fixes to the master branch.
Then you need to clone the forcedotcom/SalesforceMobileSDK-CordovaPlugin repo. 
Change tools/update.sh to point to your forks (replace "forcedotcom" with your github org).
Run ./tools/update.sh to build the static libraries for iOS etc.
Finally in your application you should cordova plugin add --path-to-your-fixed-cordova-plugin-repo--.

Or you could wait for our next release that should be out in a few weeks. #safeharbor
