### ISSUE TITLE
SFSDKHybridLogger throwing "EXC_BAD_ACCESS (code=1, address=0x0)" after log in

### ISSUE THREAD

**Issue by danishwilliams** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#354]
Hi, I used forceios to create a remote_hybrid app.

I have made no other code changes after running "forceios create". 

When running the app on an iOS 11 (tried 10.3 too) device, after successful SF log in, the mentioned error is immediately thrown. Strangely the error does not occur on simulated devices, only when running on physical devices. Please see following info and screenshot.

**Cordova 7.0.1 Plugins**:

com.salesforce 5.3.0 "SalesforceMobileSDK Plugins"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.3 "Cordova WKWebView Engine"
phonegap-plugin-push 1.5.1 "PushPlugin"

**Stack trace is as follows**:

#0	0x0000000184fc31cc in strlen ()

#2	0x000000018555b658 in _CFStringCreateWithFormatAndArgumentsAux2 ()

#3	0x00000001011bed70 in +[SFSDKHybridLogger log:class:message:args:] at /Users/wmathurin/Development/github/wmathurin/SalesforceMobileSDK-CordovaPlugin/SalesforceMobileSDK-iOS/libs/SalesforceHybridSDK/SalesforceHybridSDK/Classes/SFSDKHybridLogger.m:82

#4	0x00000001011bece0 in +[SFSDKHybridLogger d:format:] at /Users/wmathurin/Development/github/wmathurin/SalesforceMobileSDK-CordovaPlugin/SalesforceMobileSDK-iOS/libs/SalesforceHybridSDK/SalesforceHybridSDK/Classes/SFSDKHybridLogger.m:77

#5	0x00000001011cdc28 in -[SFHybridViewController webView:decidePolicyForNavigationAction:decisionHandler:] at /Users/wmathurin/Development/github/wmathurin/SalesforceMobileSDK-CordovaPlugin/SalesforceMobileSDK-iOS/libs/SalesforceHybridSDK/SalesforceHybridSDK/Classes/SFHybridViewController.m:540

#6	0x0000000194603254 in WebKit::NavigationState::NavigationClient::decidePolicyForNavigationAction(WebKit::WebPageProxy&, API::NavigationAction&, WTF::Ref<WebKit::WebFramePolicyListenerProxy>&&, API::Object*) ()

<img width="1181" alt="screen shot 2017-09-27 at 21 50 53" src="https://user-images.githubusercontent.com/14197808/30934997-9a3544c6-a3cf-11e7-890d-bb9fa50a4428.png">

**Comment by wmathurin** [comment]
Could uninstall / reinstall forceios and try again? (There was a glitch when we released 5.3, which we fixed a few days later).

**Comment by danishwilliams** [comment]
Thanks for the reply. I tried that over the weekend with no luck. I created a new forceios project on a totally new machine, and even pointed it to a different lightning application.

This is how you can recreate the issue:

1) Create a new Cordova project using forceios
2) Point it to any Lightning application
3) Open the project in Xcode (Version 9.0 (9A235)) base SDK iOS 11
4) Run the the build on a physical device (not simulated)
5) Log in with valid SF creds
6) iOS app will crash after successful log in

Please let me know if you need any other info

**Comment by wmathurin** [comment]
It's getting fixed in dev (see PR referenced) and will be in our next release.

**Comment by curtisshipley** [comment]
We are encountering this issue as well. 

A couple of questions:

When will this be fixed in master? When will the next release be out?

**Comment by bhariharan** [comment]
The next release is slated for the end of this year. #safeharbor
