### ISSUE TITLE
Consider Support for Cordova iOS 4.5.1

### ISSUE THREAD

**Issue by scottbcovert** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#355]
With the release of iOS11 & XCode 9 cordova emulate fails for iOS phonegap/ios-sim#218

The Apache team created a [bug for tracking](https://issues.apache.org/jira/browse/CB-12888) and released [4.5.1](https://cordova.apache.org/announcements/2017/09/25/ios-release.html) to fix the issue but the Salesforce Mobile SDK has a dependency on 4.4.0

**Comment by bhariharan** [comment]
Thanks for reporting. We're aware of this and are evaluating the upgrade.

**Comment by wmathurin** [comment]
It will be in our next release. See https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/pull/365

**Comment by scottbcovert** [comment]
Great, thanks @wmathurin & @bhariharan!
