### ISSUE TITLE
Attachments in force.js

### ISSUE THREAD

**Issue by mopi1402** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#356]
Hello,

in force.js, there is a function getAttachment, that is calling requestBinary.
requestBinary is not assigned, so this function is not working at all :
```
function getAttachment(id, successHandler, errorHandler){
        requestBinary(
            {
                path: '/services/data/' + apiVersion + '/sobjects/Attachment/' + id + '/Body'
            },
            successHandler,
            errorHandler
        );
    }
```

I try to alter this function that way :
```
function getAttachment(id) {
            return request(
                {
                    path: '/services/data/' + apiVersion + '/sobjects/Attachment/' + id + '/Body',
                    accept: 'text/plain'
                }
            );
        }
```
And, in the requestWithBrowser function, I'm checking if accept is text/plain to avoid JSONify the data.
This is working in a browser.

Unfortunately, this is not working on the iPad, and there is no error.
The request resolve with a null response, instead of return the content of the attachment. This is plain text, so, it should not be a trouble.

Is there a way to retrieve attachments with another way please ?
Thanks.

**Comment by mopi1402** [comment]
I didn't find documentation for com.salesforce.plugin.network, so for people who are in the same case than me, this is my dirty quick fix, and I'm using Cordova Advanced HTTP (https://www.npmjs.com/package/cordova-plugin-advanced-http) to do this task :

```
/** ugly : Temporary fix for SFDC Mobile SDK **/
        function requestBinary( obj ) {
            if ( window.cordova ) {

                var deferred = $q.defer();

                // dev friendly API: Add leading '/' if missing so url + path concat always works
                if (obj.path.charAt(0) !== '/') {
                    obj.path = '/' + obj.path;
                }

                var url = getRequestBaseURL() + obj.path;
                var headers = { "Authorization" : "Bearer " + oauth.access_token };

                cordova.plugin.http.get( url, null, headers, onSuccess, onFailure);

                function onSuccess( data ) {
                    deferred.resolve( data.data );
                }

                function onFailure( data ) {
                    deferred.reject( data );
                }

                return deferred.promise;

            } else {
                return request( obj );
            }
        }
```

**Comment by fishme** [comment]
I had the same issue with Android. The problem is that the SF Plugin need a JSON back, but the /body calls return it in binary. 

@bhariharan can you fix this issue? I did also a workaround with another HTTP call.
If someone is looking for a force.js fix take the https://github.com/ccoenraets/forcejs

**Comment by bhariharan** [comment]
@mopi1402 Thanks for reporting this issue. We will take a look.

**Comment by fishme** [comment]
Awesome!

**Comment by wmathurin** [comment]
Binary download will be supported in the next release (6.0) that should go out before the end of the year.
See https://github.com/forcedotcom/SalesforceMobileSDK-Shared/pull/461
