### ISSUE TITLE
White Screen on each day when I open the remote hybrid app first time.

### ISSUE THREAD

**Issue by merajulhasan** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#357]
Hi,

Everyday, first time when I launch the app that uses SFMobile SDK-CordovaPlugin (ver 5.0.0), I always see the app gets stuck at a white screen . It is resolved by pressing home button twice, swiping up to close the app, and re-launching it. Please help me out, Its very urgent!!!!

**Comment by bhariharan** [comment]
Have you tried our latest version (`5.3.0`)? What do the logs indicate? Could you post the device logs here?

**Comment by merajulhasan** [comment]
I tried with new sdk as u mentioned but no luck, kindly help in it.

**Comment by merajulhasan** [comment]
I have to use this app in both the platforms(ios,android) but this error is coming in android only.

This is salesforce customer community portal, which i am using inside this hybrid mobile app, so i created remote_hybrid app and mentioned the home page url of this portal as a start url in remote_hybrid app, this customer community portal is developed on salesforce using napli, i am assuming u r aware of salesforce cutomer community and napli,  
yes in this portal I am having some custom lightning components.

**Comment by bhariharan** [comment]
Lightning components are not supported within the Mobile SDK at the moment.

**Comment by va1bhav** [comment]
Hi,

When I launch the app that uses SFMobile SDK-CordovaPlugin (ver 6.0.0), I always see the app gets stuck at a white screen . I am using web view so i have modified below function in AppDelegate+SalesforceHybridSDK.m file in Xcode.

**SDK VERSION OF FILE**
- (void)setupRootViewController
{
    self.viewController = [[SFHybridViewController alloc] initWithConfig:(SFHybridViewConfig*)[SalesforceSDKManager sharedManager].appConfig];
    self.window.rootViewController = self.viewController;
}

**UPDATED**
- (void)setupRootViewController
{
    self.viewController = [[SFHybridViewController alloc] initWithConfig:(SFHybridViewConfig*)[SalesforceSDKManager sharedManager].appConfig useUIWebView:YES];
    self.window.rootViewController = self.viewController;
}

I was able to fix the white screen issue in same project with SDK 5.3 with this solution.

**Comment by bhariharan** [comment]
@va1bhav We discovered some issues that were preventing `UIWebView` from working as expected. Those issues have been fixed [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2438) and this will be a part of our upcoming release, `Mobile SDK 6.1`.
