### ISSUE TITLE
Malformed JSON Exception

### ISSUE THREAD

**Issue by FawadNL** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#361]
We are getting following error even when the json string is valid:

```
Error while parsing response
org.json.JSONException: Value {"status":{"message":"OK","code":200},"org":[{"org_relation":"Administrator","org_name":"Sunshine","org_id":"a347E000007HrZQAU"},{"org_relation":"Administrator","org_name":"The second sun","org_id":"a347E000007OffQAE"}],"profile":{"profile_photo_url":"http://enadcity.org/enadcity/wp-content/uploads/2017/02/profile-pictures.png","profile_photo_id":"0697E000002XvPQAU","middle_name":null,"last_name":"Minkels (Adm.)","full_name":"Esmée met een lange naam Minkels (Adm.)","first_name":"Esmée met een lange naam","email":"test@gmail.com","contact_id":"0037E0000SX8T4QAL"},"network_id":"0DBw000000GnbDGAS"} of type java.lang.String cannot be converted to JSONObject
                                                                                                   
at org.json.JSON.typeMismatch(JSON.java:111)
at org.json.JSONObject.<init>(JSONObject.java:160)
at org.json.JSONObject.<init>(JSONObject.java:173)
at com.salesforce.androidsdk.rest.RestResponse.asJSONObject(RestResponse.java:213)
at com.salesforce.androidsdk.phonegap.plugin.SalesforceNetworkPlugin$1.onSuccess(SalesforceNetworkPlugin.java:127)
at com.salesforce.androidsdk.rest.RestClient$1.onResponse(RestClient.java:355)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
```

**Comment by bhariharan** [comment]
Which version of Mobile SDK are you using? Could you try the latest from our `dev` branch?

**Comment by FawadNL** [comment]
I have tried the dev branch, it still doesn't work. I am sending the message as string from SF server.

**Comment by wmathurin** [comment]
Are you sending back `"{...}"` or `{...}` in the body of the response?
In other words, are you sending back the json or the stringified version of the json?

**Comment by FawadNL** [comment]
We are sending the body as stringified version of the json
i.e "{...}"
We have also the same issue on iOS here: https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/353

I may have fixed the issue for now on Android source, however in iOS there is no source file to work with.

**Comment by wmathurin** [comment]
The code is currently expecting a map or array on Android (see [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SalesforceNetworkPlugin.java#L127). On iOS, however, it should return a string if it can't parse the body as a map or array (see [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceHybridSDK/SalesforceHybridSDK/Classes/Plugins/SFNetworkPlugin/SFNetworkPlugin.m#L115)).

Anyway we will look at both implementations to make sure they are consistent and that they indeed handle a raw string gracefully.

In the meantime, if it is an option for you, I would recommend you send back the json object from the server.

**Comment by wmathurin** [comment]
Fix for iOS: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2287
Fix for Android: https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1557
Will be in the next release.
