### ISSUE TITLE
Not getting the response from loginWithCompletion on re-login without restarting the app

### ISSUE THREAD

**Issue by cepaul** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#370]
I think this is the same issue indicated in this bug report (SalesforceMobileSDK-iOS repo): https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/1684

Version of Mobile SDK Used: 5.3
Issue found in Native App or Hybrid App: Hybrid App
OS Version: iOS 10.0
Device: iPad Air2
Steps to reproduce:

Launch SF Log in screen and log in
App syncs
Log out of Salesforce
stepping through the code, it gets to:
- (BOOL)loginWithCompletion:(SFOAuthFlowSuccessCallbackBlock)completionBlock
                    failure:(SFOAuthFlowFailureCallbackBlock)failureBlock;
and then nothing happens

Expected Behavior: - (void)authManager:(SFAuthenticationManager *)manager willDisplayAuthWebView:(UIWebView *)view  should be called as happens the first time we log in

Error Log: I don't see an error, just no response after loginWithCompletion

If I re-run the app from Xcode, clicking sign-in works as expected again.

Another bug indicates that a lot of work has been done in the log in area and the developer should update to 6.0 of the native iOS SDK. I can see in the dev branch of this repo that a lot of work has been done in this area as well indicating that it's been brought over from 6.0. Any idea when these changes will be merged into master?

**Comment by bhariharan** [comment]
@cepaul Are you able to reproduce this on our sample apps in our workspace? We have done a lot of work on this front as you have noticed and this will be released in the next couple of weeks in `Mobile SDK 6.0`. #safeharbor

I recommend trying `Mobile SDK 6.0` and re-opening this issue if it still persists.

**Comment by wmathurin** [comment]
Please try with our most recent version (6.1) and let us know if the problem still exists.
