### ISSUE TITLE
Release Notes 7.0.0

### ISSUE THREAD

**Issue by fishme** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#376]
Hi @bhariharan

thanks for the new version. Do you have somewhere release notes to this version?
I'm look forward :)

Best regards 

David

**Comment by bhariharan** [comment]
Our release notes are available in our source repos:
- [iOS](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/v6.0.0/readme.md#whats-new-in-60)
- [Android](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/v6.0.0/README.md#whats-new-in-60)

**Comment by fishme** [comment]
Thank you for the links
