### ISSUE TITLE
Not able to add plugin for cordova ios 4.2.0

### ISSUE THREAD

**Issue by ramanRajSaxenaTry** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#377]
Plugin doesn't support this project's cordova-ios version. cordova-ios: 4.2.1, failed version requirement: 4.5.4
Skipping 'com.salesforce' for ios

cordova version 6.5.0

**Comment by wmathurin** [comment]
Please upgrade cordova cli to 7.0 - it’s the min required version for Mobile SDK 6.0.
