### ISSUE TITLE
Unable to run 'cordova prepare' 

### ISSUE THREAD

**Issue by kanavkhurana** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#383]
Hi,

I am trying to run the dreamhouse ionic app:
https://github.com/dreamhouseapp/dreamhouse-mobile-app

While running the 'cordova prepare' command, I'm getting the following log:

> Discovered plugin "com.salesforce.mobilesdk" in config.xml. Adding it to the project
> Fetching plugin "https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin" via git clone
> 2Repository "https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin" checked out to git ref "master".
> Installing "com.salesforce" for ios
> Plugin doesn't support this project's cordova-ios version. cordova-ios: 4.2.0, failed version requirement: 4.5.4
> Skipping 'com.salesforce' for ios

I then tried the following:
Vidurs-iMac:dreamhouse-mobile-app VK$ cordova plugin save
Vidurs-iMac:dreamhouse-mobile-app VK$ cordova platform rm ios
Vidurs-iMac:dreamhouse-mobile-app VK$ cordova platform add ios@4.5.4

But now I'm getting this issue:

> Adding ios project...
> Creating Cordova project for the iOS platform:
> 	Path: platforms/ios
> 	Package: org.coenraets.dreamhouse
> 	Name: DreamHouse
> iOS project created with cordova-ios@4.5.4
> Error: cordovaProject.projectConfig.getFileResources is not a function
> 

Can you please assist?

**Comment by bhariharan** [comment]
@kanavkhurana Please file the issue [here](https://github.com/dreamhouseapp/dreamhouse-mobile-app/issues).

**Comment by bhariharan** [comment]
@kanavkhurana Our recommended approach to generating hybrid apps is using our CLI, [forcehybrid](https://www.npmjs.com/package/forcehybrid). You should be able to generate a new hybrid app using `forcehybrid` and move the web assets under `www` in the generate project and run `cordova prepare`.
