### ISSUE TITLE
App Data Size increases gradually on each sync

### ISSUE THREAD

**Issue by vivekweb** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#384]
I have an Ionic app, added 5.3 version and configured 15+ objects to do sync operations in sequential order.

On app install & log-in with a user, total size (app, data & cache) is around 30MB in both iOS & android. When sync runs app received 20k+ records in total for all objects and size increased to 50+ MB. Sync Down is running through SOQL

If I run sync again, same volume of data will be received. Assuming no changes made in database level as no new records downloaded. But app size got increased around 5-10MB and getting increased on each consecutive sync. I have tried creating a custom method "Clear Cache" to clean data in local soups and sync. but couldn't find any difference.

Any suggestions/ideas to figure out what could be the issue or optimization to be done?
Thanks

**Comment by wmathurin** [comment]
Are you doing a `reSync` for the subsequent sync?
Could you run the smart sql query `select count(*) from {soup_name}` to see if there are indeed more records in the table?

**Comment by vivekweb** [comment]
i am not using reSync. usual syncDown, response handler (plugin's emitted event handler) to detect sync completion for a soup and initiate next. also i tried to log the records count in each soup as you said, but getting same count every time

if duplicate records upserted to soup then surely i must have got some issues in data-driven pages.

**Comment by wmathurin** [comment]
Could you move to the latest version of the SDK (6.0)?
We added a dev support dialog, which should allow you do query the database from the app (on device or simulator) without requiring any app change. (See https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/tools_dev_support.htm).

**Comment by vivekweb** [comment]
@wmathurin sorry for late reply. i am not sure whether this could help to identify the issue. I have doubts in SmartStore & SmartSync caching methods which may cause increase in size on each sync.
any cleanup methods available? I have tried to find some references on how to use CacheManager but didn't find any for hybrid app.
Thanks

**Comment by vivekweb** [comment]
While doing Profiling Analysis on I/O activity, i have noticed Cache files are getting write on SmartStore, SmartSync, SalesforceHybrid, etc. I suspect this might be one of the reason to get app size increase

<img width="1013" alt="screen shot 2018-02-26 at 6 52 03 pm" src="https://user-images.githubusercontent.com/17842048/36668526-8ef1e02c-1b2c-11e8-960e-c49faa41f33b.png">

Later found setLogLevel() in "www/com.salesforce.plugin.smartstore.js" but don't have option to turn-off logging. could suggest a way to control Logging framework (SalesforceAnalytics)?

I have tried to draft a custom method to set Logging off. please advice to make it work with right parameters or share scripts if any already available. Thanks

```javascript
import { Injectable } from '@angular/core';

declare var cordova;

@Injectable()
export class CustomSFPluginService {

    SALESFORCE_MOBILE_SDK_VERSION = "5.3.0";
    SERVICE = "com.salesforce.smartstore";

    sfExec() { return cordova.require("com.salesforce.util.exec"); }

    constructor() {
        //
    }

    setLoggingStatus(newStatus?) {
        newStatus = newStatus || 'OFF';

        this.sfExec().exec(
            this.SALESFORCE_MOBILE_SDK_VERSION,
            function(response) {// successCB
                console.log(response);
            }
            ,
            function(error) {// errorCB
                console.log(error)
            }, this.SERVICE,
            "setLogLevel",
            [{ "level": newStatus }]
           );
    }

}
```

**Comment by vivekweb** [comment]
@bhariharan thanks for your comments. let me try upgrading and see the difference in behavior. hope this works fine in android too

> sample code i have given earlier was just a draft and myself thought that this won't work. just wanted to get some ideas if this flow can be enhanced to make it work

**Comment by bhariharan** [comment]
@vivekweb Were you able to upgrade to `Mobile SDK 6.0`? Are you still seeing the issue?

**Comment by vivekweb** [comment]
@bhariharan sorry for late response. i have setup new SDK in my DEV, tested in iOS & android in process. but didn't find much difference on app size increase. please find the observed info below
* iOS: App Size - 33.1MB
* On install, Data - 3.3MB
* Initial Login, Data - 18.2MB (downloading data to few Global soups)
* number of records downloaded per sync: 733
  * Initial Sync - 23.4MB
  * 2nd Sync - 23.7MB

Seems size increase differ based on number of records queried in sync. I still need to compare the behavior with 5.3 on both platforms.

**Comment by jodybrewster** [comment]
Its in 6.1.0 on Android, we're seeing that issue as well.

**Comment by vivekweb** [comment]
Yes @jodybrewster yesterday i did testing in android and found no big differences.

@bhariharan is there any specific reason or usage for sync & smartstore log files?
could you please provide some samples to make native API calls to disable FileLogging?

Thanks
