### ISSUE TITLE
Requestbody empty on POST requests

### ISSUE THREAD

**Issue by Wizardum** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#386]
SalesforceMobileSDK: v6.0.0

I'm currently building an app for iOS platform and I'm having a problem performing a request to an ApexRest API on our Salesforce instance.

The request sends a PDF base64 encoded and looks something like this:
```
{
  "endPoint": "/services/apexrest",
  "fileParams": {},
  "headerParams": {},
  "method": "POST",
  "path": "/document?name=PdfName&accountid=xxx",
  "queryParams": "data:application/pdf;base64,JVBERiPRg==",
  "returnBinary": false
}
```
_accountid and queryParams are presented as dummy data here._

Upon receiving the request, in the Apex controller, the RestContext.request.requestbody is empty. This was confirmed using debug logs on Salesforce.

The POST method is setup like this:
```
    @HttpPost
    global static void doPost() {}
```
So I don't have any parameters SF should try to map the coming data into.

As I understand, this happened on versions prior to 5.2.0 as stated in issue #331 but since I'm using v6.0.0 shouldn't it be fixed here as well? Or is this something else?

Let me know if you need additional information.

Thanks.

**Comment by bhariharan** [comment]
@Wizardum I assume you're running a `hybrid` app on `Mobile SDK`? Are you using `force.js` to construct the request? Could you share the code that makes the request?

**Comment by Wizardum** [comment]
@bhariharan Yes that's correct.

Here you go:
```
function sendPDFDocument(documentName, documentDataUri, accountId) {
    var deferred = $.Deferred();
    var params = {
        path: "/document?name="+encodeURI(documentName)+"&accountid="+accountId,
        method: "POST",
        contentType: "text/plain",
        data: documentDataUri
    };
    window.force.apexrest(params, success, error);
    return deferred.promise();

    function success(response) {
        Log.debug("Success send doc");
        deferred.resolve();
    }
    function error(err) {
        Log.debug("error send doc" + JSON.stringify(err));
        deferred.reject(err);
    };
}
```

**Comment by wmathurin** [comment]
The mobile sdk network plugin expects `data` to be json.
Could you change your `params` to be something like:
```javascript
var params = {
    path: "/document",
    method: "POST",
    data: {"name": documentName, 
           "accountId": accountId,
           "documentBody": "data:application/pdf;base64,JVBERiPRg=="
          }
};
```
Of course, the `apexrest` endpoint would have be changed accordingly.

**Comment by Wizardum** [comment]
Thanks for the information.
That helped a lot.
Closing this now.
