### ISSUE TITLE
Lighting component throwing error when running after an inactivity of some hours on Mobile application.

### ISSUE THREAD

**Issue by Manish-Kr09** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#392]
Salesforce Mobile SDK 6.0 
Platform iOS/Android
Device: Android Pixel XL.

We are having a hybrid mobile application developed with Salesforce Mobile SDK 6.0. We do support configuration of a lightning component in our application. Currently, we are facing an issue whenever apps session got refreshed. In this case, when creating the lightning component with the newer session, it throws following error. 

"Your lightning application related to component 'xxx' was not properly initialized. Please configure your component correctly and try again"

When the mobile application's session is expired, the app creates a new session using refresh token workflow. While applying this new session for creating Lighting component we have following observations

1. With one of our clients environment, it was observed that instead of reloading of the app a **lightning error occurred** as described above. **This is a critical bug for us to fix.**

2. The Lighting framework automatically reloads the whole app when it identified that session has been refreshed. Durig our analysis we found that the call's made to @Aura enabled method got failed with the newer session. 

@bhariharan any help on this? I know mobile SDK does not support lighting components, but can i have some direction on how to resolve this issue?

**Comment by bhariharan** [comment]
@Manish-Kr09 This is one of the primary reasons why Lightning components are not supported in the Mobile SDK. Lightning components do not provide a way for us to perform session refresh and reload the component in the container. Closing this issue since Lightning components are not supported within the Mobile SDK.
