### ISSUE TITLE
Issue with PIN security with Latest SDK

### ISSUE THREAD

**Issue by Manish-Kr09** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#393]
Hi all, 

We have identified following critical issue with pin security feature with the latest SDK on Android device. 
- If user use "Forgot passcode" workflow at any time then second time onwards after login, It will not ask for pin code
- When user set passcode as fingerprint and do not enter pin, the app will always show "Use Passcode" Alert when the app starts. Now other users can also create a new passcode which breaks the first user's security. 
Here is the description of the problem's platform

Android SDK - 6.0
Application Type: Hybrid
Device: One +5T, Pixel XL

@bhariharan can you put some light on these issues, are they still exist with latest 6.1? 
any workaround that you would suggest?

Regards,
Manish Kumar

**Comment by bhariharan** [comment]
@Manish-Kr09 This should be fixed in `Mobile SDK 6.1` (see my comment in [this pull request](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1602/files#diff-12379ab3d40f00ac0184d451612dbe67R119)).
