### ISSUE TITLE
Unable to do proper error handling

### ISSUE THREAD

**Issue by fnijenhuis** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#394]
Since Salesforce Mobile SDK version 5.0 REST calls have moved from the javascript code to the native code. When a REST calls receives an error response, the native code, however, does not send error information back to the javascript code. The only thing that’s sent to the javascript code is a message in this format:
 
“The operation couldn’t be completed. (url) error xxx.”
 
This makes error handling very hard, since all relevant information is lost. Let me give an example. If a REST call (using standard REST) fails on a validation rule, Salesforce will send an error response containing (among other information) the error message of the validation rule that failed. This information does never reach the app, however, leaving the app completely in the dark on what actually went wrong and not able to accurately provide information to the user.
 
Is there a way to get more information available in the javascript code, preferably just the body of the error response?

Currently, we're using version 5.2.0 of the SDK.

Thanks.

**Comment by bhariharan** [comment]
@fnijenhuis Is this on `Android` or `iOS`?

On `Android`, we send back the HTTP response even on failure:
```
// Not a 2xx status
if (!response.isSuccess()) {
    callbackContext.error(response.asString());
}
```

On `iOS` as well, as long as there's an HTTP response received from the server, we send it back through the plugin:
```
// Some response
else if (response) {
    if ([response isKindOfClass:[NSDictionary class]]) {
        pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsDictionary:response];
    } else if ([response isKindOfClass:[NSArray class]]) {
        pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsArray:response];
    } else {
        NSData* responseAsData = response;
        NSStringEncoding encodingType = rawResponse.textEncodingName == nil ? NSUTF8StringEncoding : CFStringConvertEncodingToNSStringEncoding(CFStringConvertIANACharSetNameToEncoding((CFStringRef)rawResponse.textEncodingName));
        NSString* responseAsString = [[NSString alloc] initWithData:responseAsData encoding:encodingType];
        pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:responseAsString];
    }
}
```

This should be fixed in the latest version, `Mobile SDK 6.1`. Please try `6.1` and let us know if the issue still exists.

**Comment by fnijenhuis** [comment]
@bhariharan Just a question to make sure I understand your answer. Do you mean that this actually has been changed in 6.1 with respect to 5.2? Or should it already have worked with 5.2 and is your suggestion to try 6.1, although there shouldn't be any difference?

**Comment by fnijenhuis** [comment]
By the way, we get this behaviour on Android as well as on iOS.

**Comment by bhariharan** [comment]
@fnijenhuis The code has changed significantly in 6.1. Please upgrade to 6.1 and let us know if the issue still exists.

**Comment by wmathurin** [comment]
Please re-open if you still have the issue.

**Comment by fnijenhuis** [comment]
It's been a while since I raised this issue. Meanwhile we're running version 6.2 of the SDK. Unfortunately, this did not resolve the issue.
On Android we do see improvement, because we get more information. We now get the body of the response, but still no other information about the response. And actually we lost the HTTP status code.
On iOS we still get the same error message, only now it's translated to Dutch...

If I do the same request with the Salesforce workbench, I get the actual error response (of which we now get the body on Android).

Any help would be appreciated.

**Comment by wmathurin** [comment]
See my comment [here](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/426#issuecomment-441760251)
