### ISSUE TITLE
Inappbrowser session not shared

### ISSUE THREAD

**Issue by macu39** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#395]
In my current app I need to open some parts of salesforce in an inappbrowser window but I can't find how to share the session between the ionic app and the inappbrowser. Any ideas?

My bootstrap.config

```
{
  "remoteAccessConsumerKey": "...",
  "oauthRedirectURI": "testsfdc:///mobilesdk/detect/oauth/done",
  "oauthScopes": [
    "web",
    "api",
    "full"
  ],
  "isLocal": true,
  "startPage": "index.html",
  "errorPage": "error.html",
  "shouldAuthenticate": true
}
```
I'm using SF SDK 6.1
Thanks

**Comment by macu39** [comment]
I'm using IOS.
I need it to open some parts of salesforce that the client don't want to implement in the app, just want to open a sf window so thats why the use of inappbrowser. No using visual force just rest apis.
After searching a lot I came to the solution of using frontdoor.jsp

`https://instance.salesforce.com/secur/frontdoor.jsp?sid=accessToken&retURL=optional_relative_url_to_open`

But in the way of finding the solution, my idea was that the salesforce sdk stores the auth in some cookie/session storage and that it showld share it to the inappbrowser. Is it right? or I'm totally in the wrong way about that.
Thanks a lot for the help.

**Comment by wmathurin** [comment]
The Mobile SDK stores the oauth tokens securely in "native-land" (keychain on iOS, encrypted in account manager on  Android). Using our oauth cordova plugin, you can get the oauth access token in the web view.
The inappbrowser doesn't have access to cordova APIs however, and for that reason can't use the Mobile SDK oauth plugin (or others).

**Comment by wmathurin** [comment]
Closing the issue since I don't think we have unearthed a bug.
To further discuss the topic, please post to our [google + community](https://plus.google.com/communities/114225252149514546445)
