### ISSUE TITLE
Failed to fetch plugin phonegap-plugin-push@1.4.5 via registry

### ISSUE THREAD

**Issue by atnmorrison** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#396]
Failed to fetch plugin phonegap-plugin-push@1.4.5 via registry

I'm getting this error when I try and install the mobileSDK plugin, can I update the dependency some how?

**Comment by bhariharan** [comment]
@atnmorrison Which version of `node` are you using? Could you post the full CLI output?

**Comment by wmathurin** [comment]
You have two options:
- use node 6 (works with cordova cli 7 and 8)
- use cordova cli 8 (works with node 6 and 8)

Using node 8 and cordova cli 7 doesn't work, it produces the error you reported.

In the next release (6.2.0), we will require cordova cli 8 (right now the min version required in cordova cli 7).

**Comment by wmathurin** [comment]
PR with fix: https://github.com/forcedotcom/SalesforceMobileSDK-Package/pull/104
