### ISSUE TITLE
Intents are not protected by permissions

### ISSUE THREAD

**Issue by evifavaits** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#398]
Hi, we have a hybrid app using the Salesforce mobile SDK version 5.3. A security check was performed on our Android app and there has been a small vulnerability found. Our application accepts Android intents from all applications even when some intents are intended for inter-application communication.

**Affected item**
The Intent receiver for the com.salesforce.androidsdk.auth.AuthenticatorService service crashes the application if it is called without an "action" field. This allows other applications to crash the application.

**Reproduction**

1. Install the drozer testing tool to the device and a Linux test system.
2. Connect drozer to the agent on the phone.
3. Run the command "run app.service.send com.company.appname com.salesforce.androidsdk.auth.AuthenticatorService --msg 1 2 3" in drozer console.
4. Observe how the application crashes: 
java.lang.RuntimeException: Unable to bind to service com.salesforce.androidsdk.auth.AuthenticatorService@8527513 with Intent { cmp=com.company.appname/com.salesforce.androidsdk.auth.AuthenticatorService }: 
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
at android.app.ActivityThread.handleBindService(ActivityThread.java:3445)
at android.app.ActivityThread.-wrap2(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6541)
at java.lang.reflect.Method.invoke(NativeMethod)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.NullPointerException:
Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
at com.salesforce.androidsdk.auth.AuthenticatorService.onBind(AuthenticatorService.java:86)
at android.app.ActivityThread.handleBindService(ActivityThread.java:3431)
... 8 more

I suggest it's caused by this line in the SalesforceSDK\AndroidManifest.xml file:
```
<!-- Service required for authentication -->
<service android:exported="true"
	android:name="com.salesforce.androidsdk.auth.AuthenticatorService">
	<intent-filter>
		<action android:name="android.accounts.AccountAuthenticator" />
	</intent-filter>
	<meta-data android:name="android.accounts.AccountAuthenticator"
		android:resource="@xml/authenticator" />
</service>
```

Do you have recommendations for a fix?

**Comment by bhariharan** [comment]
@evifavaits This is not a vulnerability. The `AuthenticatorService` is a way to bind to `AbstractAccountAuthenticator`, which is the standard `Android` way to handle authentication requests of a certain account type (see [here](https://developer.android.com/reference/android/accounts/AbstractAccountAuthenticator.html)). I checked the latest code in `Mobile SDK 6.1` and the binding looks like this:
```
@Override
public IBinder onBind(Intent intent) {
    if (AccountManager.ACTION_AUTHENTICATOR_INTENT.equals(intent.getAction())) {
        return getAuthenticator().getIBinder();
    }
    return null;
}
``` 
An incoming intent should never be `null` in a real use case, so the value of `intent` within the `equals(...)` call should never be `null` as indicated above.
