### ISSUE TITLE
getAuthCredentials does not return an updated access token for iOS

### ISSUE THREAD

**Issue by alsocalledchris** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#401]
Version: Latest with Salesforce SDK 6.1

iOS version: iOS 10 +

Reproduce by:

- In the Salesforce Org set session timeout to be 15 min
- Have a Salesforce SDK Hybrid Remote application and login
- Calling getAuthCredentials (from cordova.require("com.salesforce.plugin.oauth")) returns the credentials details
- After the original token has expired but the App is still in use (so the user's sessions have been updated due to their continued use and for longer than 15min), call it again and you will not get the latest credential values - it returns the old access token (even though the OAuth token session has been updated in Salesforce - assuming it's old as calling any APIs return a 401.

(FYI calling .authenticate() instead of getAuthCredentials trashes the user's VisualForce session and thus main Hybrid-Remote application's working)

Expected behaviour:

getAuthCredentials should return updated credential information after the session has been renewed due to continued use and any subsequent call to an API endpoint authorises successfully.

This works fine and as expected for Android.

**Comment by alsocalledchris** [comment]
@bhariharan thanks for the detailed response. Understood that the method returns the existing creds as-is without trying to refresh them - however the behaviour we are seeing in iOS is that if you set the session to expire after 15min (in Salesforce) and use getAuthCredentials before API calls, after 15min of use even though the session has been updated in Salesforce (expiry date moved forward for both the OAuth session and VisualForce session) iOS API calls fail with 401 unauthenticated - Android does not - Android continues fine.

**Comment by bhariharan** [comment]
@alsocalledchris 

> iOS API calls fail with 401 unauthenticated - Android does not - Android continues fine.

How are you making these API calls? Are you using `force.js`?

**Comment by bhariharan** [comment]
How do you specify the `Bearer` token using that plugin? Could you print the `Bearer` token before and after refresh to check if they're different? I'm not sure how that plugin works. We handle any session-related issues as long as you use `force.js` supplied by the Mobile SDK to make requests.

**Comment by alsocalledchris** [comment]
@bhariharan we had some time to investigate this issue again and worked out that Android and iOS are actually the same behaviour - the access token stays the same and does indeed expire so there is not a difference between iOS and Android on this - sorry about that. 

However the investigation has highlighted that using a Remote Hybrid App there are two OAuth2 sessions relating to the user with one of those being linked to the Visualforce session and the other not. The OAuth2 session linked to the Visualforce session is updated as the user navigates around the Remote Hybrid App but the non-linked OAuth2 session is left to expire. 

I believe the OAuth2 session returned by getAuthCredentials should be for the linked OAuth2 session whose expiry date is updated from Visualforce page usage and not the un-linked OAuth2 session which expires after the session timeout time.

**Comment by bhariharan** [comment]
@alsocalledchris Could you clarify what you mean by "linked" and "non-linked" `OAuth2` sessions? Where are these sessions originating from? When we perform an `OAuth2` handshake with the platform, there's typically only 1 active `OAuth2` session and the access token that represents that session is used to make requests. In other words, there's a 1:1 mapping between access token and `OAuth2` session for that user. Where is this other "non-linked" session coming from?

**Comment by alsocalledchris** [comment]
@bhariharan linked is when the session has a parent session or is a parent session as seen in 'Session Management' page in Salesforce. The 2 OAuth2 tokens are coming from the login process of the SDK - we have not done anything special/different - going through the SDK login process seems to create the additional OAuth2 token - happens both with Android and iOS

**Comment by wmathurin** [comment]
This issue is almost 4 years old. The code has changed a lot since then. 
Please open a new issue if you think it is still relevant today.
