### ISSUE TITLE
TouchID problem

### ISSUE THREAD

**Issue by dancuconati** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#405]
Hi,

I am having an issue implementing touchID and have a few questions.

We have a hybrid app that a user can choose to use TouchID with. If they don't enable touchID, when the user foregrounds the app from background, no passkey dialog is shown. If the user enables touchID, then every time the app is foregrounded from background, the touchID dialog is shown. However, if touchID is then disabled again, and the app is brought to the foreground from the background, the passkey dialog is still shown. We believe it is because of the keychain access.
 
In the SFKeychainItemWrapper.m class, there is an init function that sets the security of the keychain access. Is there any way or workaround to modify this to to be changed to a less restrictive option?

Thanks,
Dan

SFKeychainItemWrapper.m
+ (void)initialize {
    if (self == [SFKeychainItemWrapper class]) {
        sKeychainItemWrapperMap = [[NSMutableDictionary alloc] init];
        
        /// Initialize using the most restricted access
        sKeychainAccessibleAttribute = kSecAttrAccessibleWhenUnlockedThisDeviceOnly;
    }
}

**Comment by bhariharan** [comment]
Follow this issue [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2547).
