### ISSUE TITLE
upSync not working correctly

### ISSUE THREAD

**Issue by rootdevelop** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#41]
When using the up sync ability from the new smartsync plugin, you need to specify a field list. 

But if one the objects that needs to be synced has a field from the field list that is empty, the application will crash on a setObjectForKey: object cannot be nil (key: Customfield__c)' exception.

This way it's not possible to have edited multiple items and use the up sync functionality if for example in item A, Customfield__c is edited and in item B it's empty.

**Comment by rootdevelop** [comment]
@khawkins any updates on this issue?

**Comment by wmathurin** [comment]
We have fixed the issue (both in the source code in the ios repo and in the binary libSmartSync.a in the cordovaplugin repo).
Let us know if you still run into problems.
