### ISSUE TITLE
SDK6.1 - Push Notifications sent from Service Cloud not received on Android 8 devices

### ISSUE THREAD

**Issue by va1bhav** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#415]
We have build a hybrid mobile application using SF Mobile SDK 5.0 for Android, Now after upgrading to SDK 6.1, the push notifications sent from service cloud are NOT received on specifically Android 8 devices. 

Push notifications and all other functionalities are working as expected on android devices with OS version <8. 

All other functionalities(except Push notifications sent from service cloud) are working as expected with SDK 6.1 on all devices.

Is this a known issue in SDK6.1? Is this issue resolved in SDK 6.2?

**Comment by wmathurin** [comment]
It sounds like this (resolved) issue: https://github.com/phonegap/phonegap-plugin-push/issues/1949

**Comment by va1bhav** [comment]
@wmathurin Thank you for the input, i can test this if you can just answer below questions.
SDK 6.1 installs phonegap-plugin-push v1.4.5 as a dependency. Latest version of phonegap-plugin-push do not work with SDK6.1.

Do you happen to know which version of phonegap-plugin-push can i test this with SDK6.1?
OR Is this fixed with SDK 6.2 dependencies?

**Comment by wmathurin** [comment]
In both 6.1 and 6.2 the Mobile SDK plugin depends on the push plugin v1.4.5. 
However in our next release, that dependency is gone which will allows the app to use the newer version of the push plugin (which have the fix for Android 8).
For more information see: https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/pull/413

**Comment by va1bhav** [comment]
@wmathurin What is the timeline planned for release of the SDK which would include this fix?

**Comment by wmathurin** [comment]
November or december. #safeharbor

**Comment by va1bhav** [comment]
@wmathurin  Could you please provide planned release date if it has been finalized?

Thanks!

**Comment by wmathurin** [comment]
You should pick up 7.0.0-rc we released last year, we don't expect any code changes between 7.0.0 and 7.0.0-rc (beyond a few bug fixes).
