### ISSUE TITLE
SDK 6.1 Application crash on iOS, Threading issue.

### ISSUE THREAD

**Issue by va1bhav** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#416]
We have built a hybrid mobile app using SDK 6.1 for iOS and using the force.js provided with SDK for user authentication.

When user session expires and "oauthPlugin.authenticate" function is called to refresh token. This first call to the function crashes the app with below Thread warning.

"Tried to obtain the web lock from a thread other than the main thread or the web thread. This may be a result of calling to UIKit from a secondary thread. Crashing now..."

When the app is launched after crash, same function is executed for refresh token and app works as expected.

Is this a known issue? Could you please help with fix for this?

Let me know if you need more details.

**Comment by wmathurin** [comment]
What device are you running the application on (what iOS version is it using)?

**Comment by va1bhav** [comment]
I have tested this on iPhone 6 and X on iOS 11.4.

**Comment by va1bhav** [comment]
@wmathurin This was an issue with SDK 6.1.0
I have integrated our app with SDK 6.2 and this issue is fixed.
Could you please provide a URL/list with known issues of SDK 6.2 which we can look out for? This will be a great help.
Thank you for your support.

**Comment by brandonpage** [comment]
@va1bhav Thank you for checking the latest version of the sdk, it is really appreciated.  At this point we have no known issues in 6.2 related to iOS and Cordova other than build errors with the current Xcode 10 beta.  That will be a focus of our next release, after iOS 12 is launched #safeharbor.  Thank you for using the product!
