### ISSUE TITLE
Dev support enabled in release build on iOS in SDK version 6.2

### ISSUE THREAD

**Issue by fnijenhuis** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#419]
Hi,

I'm currently using version 6.2.0 of the SalesforceMobileSDK. Now when I make a release build for iOS, Dev Support is enabled, so when a user shakes the phone the Dev Support menu pops up.

On Android it works fine (disabled on release builds). I can't find what I'm doing wrong or how to disable it. What should I do? Or could this be a problem with the latest version of the SDK?

**Comment by fnijenhuis** [comment]
Where should I include this code?

**Comment by fnijenhuis** [comment]
That worked, thanks.

**Comment by wmathurin** [comment]
In the next version of the SDK (7.1), you won't need to add code to your AppDelegate thanks to https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Hybrid/pull/29.
