### ISSUE TITLE
Rest response in force.js not available in case of error status codes

### ISSUE THREAD

**Issue by vsvikram** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#426]
I've migrated the hybrid project from SDK 4.3 to v6.2 and using SDK 6.2 with the force.js apexrest method for rest API calls in an iOS hybrid app. I'm able to get the custom JSON response sent from API in successful cases but in case of error codes like 400 or 501 etc, the JSON response which was sent from API is not available in apexrest error handler method, instead, a general error log is available: "_The operation couldn’t be completed. (https://xxxxxxxxx/services/apexrest/mobileSyncService error 400.)_"

Could you please confirm if this is an implementation issue or an issue with new SDK because in older 
SDK version 4.3, it is working as expected.

Please find attached screenshot for your reference.

Success Response from API: JSON object with one key 'status'

![screen shot 2018-11-19 at 6 08 15 pm](https://user-images.githubusercontent.com/17747628/48882726-db0ac080-ee41-11e8-87de-c2b5658de47f.png)

Error Response: JSON object not available: only standard string, 'status' key is sent in JSON object in this case too:

![screen shot 2018-11-20 at 1 08 56 pm](https://user-images.githubusercontent.com/17747628/48882734-e958dc80-ee41-11e8-9276-6b1a38609752.png)

Please help clarify this.

**Comment by vsvikram** [comment]
1. I'm using the 6.2 version which is shipped with Cordova plugin of Salesforce Mobile SDK 6.2 in Cordova project created with forcehybrid (same as above link given by @wmathurin ).

2. 400 is sent by my custom code using RestContext.response in Apex Class explicitly. Actually, the request is properly formed and class executes just fine but the issue is if I send custom JSON in response with error codes 4XX or 5XX, the JSON object is masked and is not available in the response received in the error handler of force.apexrest. Although it works fine and JSON object is available in response in older SDK version (tested with 4.3.1).

3. In new SDK, JSON object is available in API response only if status codes are specified 2XX like 200 but in older SDK, the JSON response is available for all error codes.

4. These are all the cases where request completes and based on business logic or validations, explicitly exception is thrown in the API which then gets captured in force.apexrest by means of status codes but JSON responses are not available for 4XX and 5XX in new SDK.

**Comment by wmathurin** [comment]
Unfortunately that is the behavior of the underlying network plugin (since 5.0): see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceHybridSDK/SalesforceHybridSDK/Classes/Plugins/SFNetworkPlugin/SFNetworkPlugin.m#L120

**Comment by vsvikram** [comment]
The response handling behavior of the plugin can be overridden or is it implemented this way due to some constraint?

**Comment by wmathurin** [comment]
The body of the response for non 2xx responses is not passed through by the underlying code (SFRestAPI). That would need to change to support your use case.

It was working in 4.x because the web view was doing the network call directly instead of going through the network plugin. That's no longer an option because same origin policy is enforced by WkWebView (and wasn't with UIWebView).

Maybe you should look at https://github.com/silkimen/cordova-plugin-advanced-http to do your network calls. You will have to set the request header yourself though.

**Comment by wmathurin** [comment]
The error callback is called for non successful requests (requests that don't have a 2xx status code or requests that fail to get a response).
In the next version of the mobile sdk (8.2) soon to be released, we are sending back more than just the error through the error callback.

```json
{
  "response": { 
    "headers": { ... }, 
    "statusCode": 400, 
    "body": "response-body"
  }, 
  "error": "error message - when no response was received e.g. when the server could not be reached"
}
```
For more information see:
* https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3237
* https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2095
