### ISSUE TITLE
SmartStore Soups not available after upgrading the mobile SDK

### ISSUE THREAD

**Issue by vsvikram** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#429]
I've upgraded the mobile SDK plugin from v4.3.1 to v6.2 and my global soups are not available in the newly created build and all the soups are created as it was a fresh new build even though the store.sqlite files are available in device's documents directory.

This issue is not observed if I tried replicating the issue while upgrading the SDK from v6.1 to v6.2. The only difference in both the case is that while upgrading from v6.1 to v6.2, the Xcode version was same (Xcode 9.4.1) but in the earlier case while upgrading from v4.3.1 to v6.2, the Xcode version is also updated from v8.3 to v9.4.1.

Is the soup encryption method changed in both the version?

Currently, my production application uses v4.3.1 and if we go ahead and upgrade to v6.2, data stored in soups for users will be lost (or not accessible) and they will have to redownload the data. 

Is it an issue with SDK or the encryption implementation is different in both the version?
Is there any good documentation on SmartStore encryption and what happens to the data across SDK version in such a case?

Xcode 9.4.1 logs are attached below after upgrading the app from v4.3.1 to v.6.2.
[Xcode-logs-SDK4.3.1-to-SDK6.2.txt](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/files/2653450/Xcode-logs-SDK4.3.1-to-SDK6.2.txt)

**Comment by wmathurin** [comment]
We typically recommend you don't skip major releases when upgrading. 
In your case, if you do 4.3 -> 5.x -> 6.x, you shouldn't see any upgrade issues.

**Comment by vsvikram** [comment]
Thanks, @wmathurin for your reply, can you confirm if the encryption method or technique is changed in these releases and can you point to a documentation if it is documented?

**Comment by wmathurin** [comment]
Details over current encryption methods is here: https://resources.docs.salesforce.com/sfdc/pdf/salesforce1_mobile_security.pdf
