### ISSUE TITLE
Passcode screen not displayed on app relaunch - SDK 7, iOS

### ISSUE THREAD

**Issue by va1bhav** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#438]
Cordova version : 8.1.2
SDK version : 7.0.0
Platform : iOS

**Description**
If PIN is enabled from service cloud, user has to setup passcode after login to the app.
User should be displayed passcode screen on ideal timeout and relaunch of the app.

**Issue**
When app is relaunched, passcode screen is not displayed.

**Comment by wmathurin** [comment]
What did you mean by "If PIN is enabled from service cloud" ?

**Comment by brandonpage** [comment]
Hi @va1bhav, apologies for the late response.  Can you please provide a little more information?  I am not able to reproduce the issue you describe.  I have tried the following scenarios:
- Background then Foreground -> passcode screen shows up after the timeout
- Kill app -> passcode screen shows up immediately
- Rebuild app -> passcode screen shows up immediately

**Comment by va1bhav** [comment]
Hi @brandonpage Could you please specify what kind of more information you are looking for here, for the scenarios you listed, below are my test results:

Background then Foreground -> passcode screen shows up after the timeout - [Working with SDK 7]

Kill app -> passcode screen shows up immediately - [Not working with SDK 7, kill app and relaunch, passcode screen is not displayed.]

Rebuild app -> passcode screen shows up immediately - [Rebuild app in xcode and override on existing app, not working with SDK 7]

App info: I have my hybrid app built with SDK 6.2 with some cordova plugins in which all the above scenarios are working as expected. I have now integrated same app with SDK 7 and the mentioned scenarios are not working now.

**Comment by wmathurin** [comment]
Closing - old issue - not reproducible.
