### ISSUE TITLE
 logout problem

### ISSUE THREAD

**Issue by wpf329739489** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#441]
Hi,
From Mobile SDK v6.2,in Ios, When I entered my account password and logged in successfully,Whether to keep logon pops up,I chose Yes,like this 
![screen shot 2019-02-15 at 2 49 45 pm](https://user-images.githubusercontent.com/38965917/52839441-1c54f880-3131-11e9-9b0f-0b785627ce41.png)

After I logged out, I wanted to switch my account,But the problem is that salesforce has been using the account I logged in before to log in directly without popping up the login box or the account switching bar,have tried logging out with both these methods: 
cordova.require("com.salesforce.plugin.sfaccountmanager").logout();
and
cordova.require("com.salesforce.plugin.oauth").logout();
But it's no use, so i want to know how to logout and Click login to use login page instead of direct login

**Comment by wmathurin** [comment]
Are you on iOS or Android? Are you using [advanced authentication](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/auth_ios_advanced.htm)?

**Comment by wmathurin** [comment]
Also what version of iOS or Android are you seeing the issue on?

**Comment by wpf329739489** [comment]
hi
on IOS,Android is no proplem
When I first Login,I used like this 
const sfOauthPlugin = function(){return cordova.require('com.salesforce.plugin.oauth')};
sfOauthPlugin().authenticate();
then i use 
import { OAuth, DataService } from 'forcejs';
const Oauth = OAuth.createInstance();
Oauth.login()
I successfully logged in,Then i click LoginOut Button,The way to exit the landing is SfOauthPlugin().logout();
But when I landed again,I logged in before to log in directly without popping up the login box or the account switching bar, I want to chose the other account,
the forceJS version is 2.2.1 ,Cordova IOS version is 4.5.4,IOS version is 12.0.0 thank you

**Comment by wmathurin** [comment]
Where are you getting force.js from?
I am suspecting that the following
```javascript
import { OAuth, DataService } from 'forcejs';
const Oauth = OAuth.createInstance();
Oauth.login()
```
Does a login into the webview not tied to the container.

You should use the salesforce mobile sdk plugins for oauth and for switching user (see https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/multiuser_hybrid.htm).

**Comment by wpf329739489** [comment]
ok 3q
