### ISSUE TITLE
Incorrect instanceURL appended on the network plugin

### ISSUE THREAD

**Issue by jmanuelvmtz** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#449]
Cordova version : 8.1.2
SDK version : 7.0.0

App description:
we got a SF web app URI being processed by an akamai service for redirection from the sf fqnd to an specific public URI that we user for authentication on our ionic/cordova hybrid app and retrieve the accesstoken along with the instanceURL for later usage on the query/update requests

Issue:
once the accesstoken is already in place on the mobile SDK, when we attempt to execute an update(patch) request, for android the instanceURL never gets appended after we call an update request by network plugin,  for ios we noticed the instanceURL that we got from the login is not used either, instead the loginURL is what get appended as the prefix for the update request, any suggestion on how to define what gets sent/appended as instanceURL by the mobileSDK network plugin, or how to work around this issue?

**Comment by bhariharan** [comment]
@jmanuelvmtz The plugin will use the `instanceUrl` that comes back from the `/token` endpoint, after authentication. Could you check what value is stored there/returned from the service? Also, what's the configured value for `loginUrl` in your app?

**Comment by jmanuelvmtz** [comment]
@bhariharan the token we get back from the authorization endpoint contains the instanceUrl as "https://ibmsf.my.salesforce.com" which is right, as for the loginURL we are using “www.ibm.com/mysupport”, we have tested the update functionality that the plugin provides on our staging salesforce instance "loginUrl":"https://int-ibmsf.cs90.force.com/mysupport", "instanceUrl":"https://ibmsf--Int.cs90.my.salesforce.com" and everything works correctly, the only difference for the production instance is that the loginURL runs through a redirection akamai service, but the token we get  contains the right instanceURL, like i said when we debug on the plugin until the point of the pgSendRequest instruction : for android we believe the instanceURL never gets appended to the request url, in order to test, if we append  manually the instanceURL to the path at the exec call args on the plugin, the update request gets correctly sent and executed, for iOS if we try to just execute the request call,  we get a response from the plugin which reads as follows: operation couldn’t be completed. (https://www.ibm.com/mysupport/services/data/v42.0/sobjects/Case/casenumberid) which is using the loginURL to construct the path.

**Comment by jmanuelvmtz** [comment]
After further review , we noticed the plugin is taking the communityURL instead of the instanceURL to resolve the rest endpoint URL, we actually need to use instanceURL over communityURL, the change seems to be easy to manage for android but not so sure where to change it for iOS, any suggestions?

**Comment by bhariharan** [comment]
Right, so if `communityUrl` is present, that indicates that the user is logged in to a community, so the URL must be prefixed with `communityUrl`. In the absence of `communityUrl`, we will use `instanceUrl` as the base URL. I assume your app is a hybrid local app? How are you making the request? Have you considered using `force.js`, which comes with the hybrid SDK? This allows you to easily make REST requests. If you look at the implementation [here](https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/master/libs/force.js#L95), the base URL should be `instanceUrl`.

**Comment by jmanuelvmtz** [comment]
we are making the request using the   `networkPlugin.sendRequest() `method to call the plugin, we can control the path that is sent as the first parameter which goes in the form of "/services/data/v42.0/sobjects/" after that the plugin assumes that out rest api endpoint needs to use `communityURL` as the prefix but in reality for our case scenario it does use the `instanceURL` as the prefix, if we call the method `getRequestBaseURL` the value we are getting comes with `instanceURL` as the endpoint prefix but internally the plugin is still sending `communityURL` on the request, still our endpoints use the value for `instanceURL`, since im not sure we can change what is used on the salesforce communities endpoints list, was wondering if there is any work around to manually set the endpoint prefix, on android we found that the plugin can be changed at the SalesforceSDK>src/rest/restClient.java class at line 558, but for iOS it doesnt look that easy to change (due to the library being already compiled/packaged), besides, it does not look that optimal to make changes, then rebuild the ios plugin for each and every update that get released just to fit a couple lines of code to the needs of our project, though, if that is the only workaround we would do it, but we are looking for a more generic workaround.

**Comment by wmathurin** [comment]
1) `networkPlugin.sendRequest()` allows passing a full URL in the path parameter. You could build your full URL with the instance URL in javascript. You can get the instance URL by calling `getAuthCredentials()` on the OAuth plugin (see [here](https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/master/libs/cordova.force.js#L329).

2) I recommend you upgrade to Mobile SDK 7.1. We now consume the SDK from sources on iOS so debugging (or making iOS code changes) is a lot easier.

**Comment by bhariharan** [comment]
Please upgrade to the latest, i.e; `7.3.0`.
