### ISSUE TITLE
SDK support for Hybrid Windows 10 app

### ISSUE THREAD

**Issue by akshayajeevan** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#455]
Hello,

Cordova Version: 8.1.2
SDK Version: 7.0
Ionic-Angular: 3.9.2

I created a hybrid android app with above versions and it's working fine. 
Now I need to create an equivalent app for Windows 10. So I tried the following -

- Added windows (v6.0.1) cordova platform
- Build the app in VS Code 2015 as per this doc [ [link](https://github.com/forcedotcom/SalesforceMobileSDK-Windows/tree/master/docs) ], 
- Run on local machine (Win 10)

**Issue:**
When I am running the app, I am getting the Home page without my connected app's login page. Here I am able to navigate to different pages. 

Does this SDK support for Windows 10 hybrid apps. If yes or no, can someone help me in pointing right direction.

Thanks a lot.

**Comment by bhariharan** [comment]
The Mobile SDK Cordova plugin does not support `Windows 10` - it only supports `iOS` and `Android` currently. [SalesforceMobileSDK-Windows](https://github.com/forcedotcom/SalesforceMobileSDK-Windows) is no longer supported for native `Windows 10` apps either. We stopped supporting `Windows` around 2016, if I'm not mistaken.
