### ISSUE TITLE
Android App crash on session timeout / revoked

### ISSUE THREAD

**Issue by jaygauten** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#463]
plugin version: 7.0
issue: app crashes if session timeout or revoked and then try to reopen the app
           by placing the app in to background and then foreground, or try to fetch new data from 
           server
Seen/occured in: Android 8.0
Crash log found: threading issue in RestClient (see attached file). somehow the logout run 
           before the refresh oauth token occurs

<img width="803" alt="Screen Shot 2019-07-08 at 8 31 36 PM" src="https://user-images.githubusercontent.com/1757953/60866205-564aa680-a25a-11e9-8798-106e48f4eb84.png">

**Comment by brandonpage** [comment]
Hey @jaygauten, sorry for the late response but I am having trouble reproducing this issue.   Is there any additional information you can provide?  Can you reproduce this consistently?  What version of OkHttp are you using?  If possible could you try to reproduce this in a brand new project generated by forcehybrid?

**Comment by jaygauten** [comment]
Yes we can consistently reproduce the issue.

for okhttp, as far as i know the only okhttp installed in our platform is from the SalesforceMobileSDK. I'll verify it and post it here, thanks

**Comment by wmathurin** [comment]
Before we proceed further could you try with version 7.1.2 of the Mobile SDK. It's using a slightly more recent version of OkHttp and see if the issue still reproduces?

**Comment by jaygauten** [comment]
will try the latest sdk, will let you know the result. thanks @wmathurin @brandonpage

**Comment by wmathurin** [comment]
We can't repro the issue here. Please re-open if you can repro it with the latest version (7.3).

**Comment by jaygauten** [comment]
@wmathurin  we'll do if issue persists, will keep you posted thanks
