### ISSUE TITLE
iOS 13 - Login doesn't load in full screen due to modalPresentationStyle default changed in iOS 13

### ISSUE THREAD

**Issue by vsvikram** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#465]
Hi,

I've been testing my Cordova hybrid iOS app on iOS 13 beta released and found that the login screen is loading in a popup modal and not full screen due to the default value of modalPresentationStyle is changed to UIModalPresentationPageSheet for UIViewController. In previous iOS versions, it was set to  UIModalPresentationFullScreen.

It's not technically an issue for mobile SDK but I need to know how can we restore the original behavior of login page to full screen.

 Also, are we going to include this as a config for login page setup to have the options of rendering it to full-screen mode or in the popup.

Below is the screenshot of the login screen behavior in iOS 13 beta 4:

<img width="686" alt="Screenshot 2019-07-26 at 12 34 48 PM" src="https://user-images.githubusercontent.com/17747628/61932868-0a119d00-afa2-11e9-927d-1dcba7cd6a07.png">

**Comment by wmathurin** [comment]
We fixed that in Mobile SDK 7.2 (see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2907).

**Comment by vsvikram** [comment]
@wmathurin Thanks for the information. I've upgraded the SDK to v7.2.0 and the login screen is coming in full screen now. But the connection endpoint selector screen is still coming up in popup modal as the screenshot below. Please confirm if this is the expected behavior of SDK v7.2.0.

<img width="600" alt="Screenshot 2019-08-06 at 3 55 27 PM" src="https://user-images.githubusercontent.com/17747628/62532852-006e1c00-b863-11e9-9407-ca9aa528e322.png">

**Comment by brandonpage** [comment]
Thanks for bringing this to our attention @vsvikram.  This seems like okay (maybe not ideal) behavior for a menu screen.  We will evaluate this in the context of all of the other changes that have come in with iOS 13 for the next release.
