### ISSUE TITLE
Getting salesforce login page instead of custom login screen in IOS

### ISSUE THREAD

**Issue by prasanthmpr** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#466]
Hello,

we have a hybrid cordova app which is using Salesforce Mobile SDK as backend service. we are encountering an issue in IOS like when the user tries to login, they are being redirected to https://login.salesforce.com/ instead of our custom login screen in QA and prod as well.

We have configured the value of SFDCOAuthLoginHost in info.plist but still it is being redirected to login.salesforce.com for few users. Please do let me know if this is a known issue of the plugin and the solution to resolve that.
Also, the callback url is set to the right one. we have not encountered this in Android even once. But in IOS it is intermittent.

Thanks

**Comment by wmathurin** [comment]
What version of the Mobile SDK are you using?

**Comment by prasanthmpr** [comment]
> What version of the Mobile SDK are you using?

We are using 7.0.0 version and the issue is not occurring in android but only in IOS although we have configured everything, it occurs intermittently.

**Comment by wmathurin** [comment]
Would you mind trying with our most recent version of the Mobile SDK (7.2)?
We don't patch old versions of the SDK and we want to make sure that the issue happens on the latest version before investigating further.

**Comment by prasanthmpr** [comment]
@wmathurin We have identified the issue. When the user device has a very slow network, authentication with salesforce is getting failed and so they are navigating to the Salesforce login page instead of custom login. Do we have a solution to this where we can retry the authentication? Thanks in advance.

**Comment by az-oolloow** [comment]
@wmathurin we get the same behaviour if the user opens the login page, then waits > session time (e.g. 30 minutes) and then logs in, instead of 'authorise connected app' screen we are shown salesforce home page.

**Comment by wmathurin** [comment]
The login flow inside the webview is a black box in the Mobile SDK and is entirely driven by the server side oauth code.
I believe the server side team is aware of the issue but it's considered low priority. I can't say when or whether it will get fixed.
