### ISSUE TITLE
iOS - Bumping API version to latest (46.0)

### ISSUE THREAD

**Issue by vivekweb** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#468]
Thanks for the commit on API version upgrade to latest which helped to resolve issues we were experiencing. https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/pull/467 Here I found for Android only but couldn't find any notes related to iOS. Even running "pods update" didn't show any new updates available for MobileSDK pods.
I am using v7.1.2

Is there any update or suggestions on this? Thanks

**Comment by bhariharan** [comment]
@vivekweb We have updated the API version on both `Android` and `iOS`. This will be a part of our next release (`v7.3.0`), which hasn't been released yet. It's slated for later this fall.
