### ISSUE TITLE
RefreshToken / Authenticate did not call any callbacks

### ISSUE THREAD

**Issue by jaygauten** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#483]
_**SDK Version**_: **7.0.0**

**_Issue_**: when session token is expired the app will request new token through refreshTokenWithPlugin and go to oauth.authenticate, but after waiting couple of minutes the callbacks (success, fail) never called. Happened on iOS only.

**_What we did_**: we are currently tracing the cause of the issue but in the logs it doesnt make sense and most of the classes and methods printed in the logs is either not searchable in the workspace or its just a header. Please refer to the screenshot:

<img width="867" alt="Screen Shot 2019-10-29 at 6 42 46 PM" src="https://user-images.githubusercontent.com/1757953/67816042-af796700-fae3-11e9-84f3-1fa912a142fb.png">

> the highlighted in yellow is where the authentication takes place

we also tried generating the sample app via forcehybrid but the sample does not have the oauth.authenticate flow for refreshing session

_**Note**_: this ticket is more of an asking for a guide on how to properly debug ios authenticate flow

Thanks in advance!

**Comment by wmathurin** [comment]
Starting with Mobile SDK 7.1, our Cordova plugin brings the SDK through sources (using cocoapods). 

If possible, could you upgrade the version of the Mobile SDK you are using. Debugging should be a lot easier and also you could see if the issue you are running into still exists.

**Comment by jaygauten** [comment]
We cannot update to 7.1 as of now, but i have a pending sdk upgrade task using 7.3.0, i can give it a try from there.

**Comment by frankvlocity** [comment]
@wmathurin  we need to fix this issue for SDK 7.0, then we will update to 7.3 which is a huge change we finally switch from UIWebView to WKWebView. Is there anyway you can tell us why the refreshToken logic don't work for 7.0, any change?

**Comment by wmathurin** [comment]
We are not aware that it regressed. 7.0->7.3 should not be a major upgrade.

**Comment by jaygauten** [comment]
@wmathurin it is for us - build flow change, plugins compatibility, uiwebview to wkwebview etc. :)

anyway, the refreshToken of sdk 7.0 is working on an old org version, but for the current version of the org its not working properly. We cant verify if its the org or the sdk is causing the issue because we can only see the header files from Salesforce core and not the .m files and cant debug the codes by having breakpoints.

i also tested in 7.3 it is pretty working but after the token is refreshed the resources hosted in salesforce failed to load, probably wkwebview issue on updating the cookies - we will look into that, but we cant release the 7.3 yet and need to resolve the issue in sdk 7.0 environment first.

any tips on how can we debug the authentication flow?

**Comment by wmathurin** [comment]
Internally/externally nobody reported issues with refresh in 7.0. If it's working in one org and not another, it must be an org configuration issue. Could you check the refresh token policy in the connected app in the new org version and make sure it uses "Refresh token is valid until revoked" and not "Immediately expire refresh token".

**Comment by jaygauten** [comment]
@wmathurin checked both orgs and they have the same configuration for connected apps policies

**Comment by wmathurin** [comment]
For your question about debugging, it's one of the reason we did what we did in 7.1 (the move to consuming from sources). Since you are unable to upgrade, here is way to do it:
- checkout https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Hybrid at the v7.0.0 tag
- run ./install.sh
- put your html/js/css in one of the hybrid sample apps (they are under /hybrid/SampleApps)
- run the modified app

The SDK code is "wired" in through a submodule so you should be able to step through etc.

**Comment by jaygauten** [comment]
Thanks @wmathurin, we will try this approach

**Comment by jaygauten** [comment]
Hi @wmathurin we tried your suggested approach but i cant import our artifacts properly, the xcode did not recognized the files i added.

What i tried:
- i added the artifacts through Finder
- added the files through xcode
- replaced the shared-www content in external > shared > samples > <sample app>

What is happening:
- the xcode do not recognize the new files added
- files added through xcode only add the files under the app root
- pbxproj file under the xcodeproj of the app holds all the registered files for the app

im not accustomed with xcode project and not sure what i did wrong when importing our artifacts to the existing xcodeproj

**Comment by wmathurin** [comment]
I'm going to close this issue because it does not seem to be a Mobile SDK bug.
If you still believe it's a bug with the SDK (and you are able to repro it with a recent version of the SDK e.g. 8.1), please re-open an issue.
