### ISSUE TITLE
/platforms/android/app/build/intermediates/merged_manifests/debug/AndroidManifest.xml:43: AAPT: error: resource drawable/sf__icon (aka it.moblize.apps.businesscardscanner:drawable/sf__icon) not found.

### ISSUE THREAD

**Issue by moblizeit** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#486]
I am using the below cordova cli and platform as recommended in the sf mobile sdk.

Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
  Cordova Platforms : android 8.0.0, ios 5.0.1

And steps used to add mobilesdk for cordova are:
cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin --force

It takes some long time but succeeds with no errors. However on doing
ionic cordova run android it fails with below error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  /Users/moblizeit/code-repo/apps/business-card-scanner/businesscardscanner/platforms/android/app/build/intermediates/merged_manifests/debug/AndroidManifest.xml:43: AAPT: error: resource drawable/sf__icon (aka it.moblize.apps.businesscardscanner:drawable/sf__icon) not found.
      
  error: failed processing manifest.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

**Comment by bhariharan** [comment]
@moblizeit Please use `Android Studio` to import and run the project. Could you let us know if that works?

**Comment by moblizeit** [comment]
Thanks for a quick response. Are there any steps to do that? in last 2-3 years of develpment and using 100s of cordova plugin we never needed to go to android studio to build or run  ionic /cordova projects. Please advise

**Comment by moblizeit** [comment]
so i imported it into android studio and it fails with exact same error as below:

> Transform legacy-support-core-utils.aar (androidx.legacy:legacy-support-core-utils:1.0.0) with AarTransform
> Transform legacy-support-core-ui.aar (androidx.legacy:legacy-support-core-ui:1.0.0) with AarTransform
> Transform loader.aar (androidx.loader:loader:1.0.0) with AarTransform
> Transform fragment.aar (androidx.fragment:fragment:1.0.0) with AarTransform
> Transform exifinterface.aar (androidx.exifinterface:exifinterface:1.0.0) with AarTransform
> Transform media.aar (androidx.media:media:1.0.0) with AarTransform
> Transform android-crop.aar (com.soundcloud.android:android-crop:1.0.0) with AarTransform
> Transform legacy-support-v4.aar (androidx.legacy:legacy-support-v4:1.0.0) with AarTransform
> Transform barcodescanner-release-2.1.5.aar (:barcodescanner-release-2.1.5:) with AarTransform
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:mergeDebugResources
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugResources FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings
25 actionable tasks: 4 executed, 21 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  /Users/moblizeit/code-repo/apps/business-card-scanner/businesscardscanner/platforms/android/app/build/intermediates/merged_manifests/debug/AndroidManifest.xml:43: AAPT: error: resource drawable/sf__icon (aka it.moblize.apps.businesscardscanner:drawable/sf__icon) not found.
      
  error: failed processing manifest.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
/Users/moblizeit/code-repo/apps/business-card-scanner/businesscardscanner/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  /Users/moblizeit/code-repo/apps/business-card-scanner/businesscardscanner/platforms/android/app/build/intermediates/merged_manifests/debug/AndroidManifest.xml:43: AAPT: error: resource drawable/sf__icon (aka it.moblize.apps.businesscardscanner:drawable/sf__icon) not found.
      
  error: failed processing manifest.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build android exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.

**Comment by bhariharan** [comment]
@moblizeit Are you able to generate a new app using `forcehybrid` and run it using `Android Studio` successfully?

**Comment by vsvikram** [comment]
@moblizeit Have you tried removing and re-adding salesforce sdk plugin to the project. It is mentioned in the Salesforce SDK guide that after adding all custom plugins, salesforce sdk plugin should be removed and re-added to the project.

@bhariharan could this be the solution for this issue?

**Comment by moblizeit** [comment]
yes we have tried that already multiple times. removing, re-adding plugin and even tried freshly by removing platform and re-adding it does not work. 

It's a big blocker for us and easy to reproduce for any ionic based app.

**Comment by bhariharan** [comment]
The problem is that the post-install hook does not seem to be running. We don't really support `ionic` or running from CLI. We provide our own package called `forcehybrid` to generate an app and get started. This ensures that the post-install hook will get run. Here are my recommended steps:

1. `npm install forcehybrid` and generate a new hybrid app using our CLI.
2. Open the generated app in `Android Studio` and verify that it builds and runs.
3. Close `Android Studio`. Using `Cordova CLI`, remove our plugin (instructions available in our dev guide).
4. Add the plugin that you want to use.
5. Re-add our plugin.
6. Import the project in `Android Studio` again and build and run it.

These steps should work.

**Comment by vsvikram** [comment]
@bhariharan Yeah these steps should do it. But the SDK plugin takes very long if installed using Cordova CLI with GitHub URL. Is there a fast available method to install the plugin? 

It would help if the plugin is added to the NPM registry.

**Comment by bhariharan** [comment]
Unfortunately, that's a one-time cost you will have to pay because it checks out our git repo that contains the plugin. Our plugin is quite complicated unlike most `Cordova` plugins - we can't add it to the registry easily for this reason.

**Comment by moblizeit** [comment]
Sorry little confused.

Please advise,  using your steps would it be possible at all to have this
in ionic application or not?

Our ionic app is our core product with lot of other functionality and
integrations. So we cannot get away from ionic. We are ok for a workaround
way to get this plugin working in ionic app though.

Regards

**Comment by bhariharan** [comment]
@moblizeit The only workaround that I can think of is manually integrating the plugin by copying the required files in their respective appropriate locations. This would be intrusive and difficult to accomplish. We don't support `ionic CLI`.

**Comment by moblizeit** [comment]
Yeah we would stay away hack way to do for our production work,

Kind of sad that one of the most popular hybrid app development platforms
is not support.

**Comment by bhariharan** [comment]
The recommended approach is following the steps I have outlined above.

**Comment by jorgeartigas** [comment]
@moblizeit hey I'm facing the same issue when running "ionic cordova run android" with 

Salesforcemobilesdk-cordovaplugin: 9.2.0
Cordova CLI: 10.0.0 (cordova-lib@10.1.0)
Cordova Platforms : android 10.1.0

did you find any solutions?
