### ISSUE TITLE
Hybrid SDK 7.3 Android - Passcode not saved

### ISSUE THREAD

**Issue by ShreetomaGuchait** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#487]
I am using forcehybrid SDK v7.3 for android app, when app is left idle instead of asking to enter passcode, app asks to generate a new passcode every-time. @bhariharan @wmathurin

**Comment by wmathurin** [comment]
We are not able to reproduce. Please provide more detailed repro steps.
