### ISSUE TITLE
Best approach in displaying error messages from plugin in iOS

### ISSUE THREAD

**Issue by jaygauten** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#490]
1. Version of Mobile SDK Used: 7.3.0
2. OS Version: 12
3. Device: iOS
4. Steps to reproduce:
     1. Login to the app
     2. Trigger any request error
     3. notice the error data
5. Actual behavior: it will return a generic message (NSError localizedDescription)
6. Expected Behavior: will return the error object (NSError userInfo)

Additional info:
when using requestWithBrowser the return error is in json array format with message property, but on requestWithPlugin it is returning a different format on iOS but web and android response is pretty much the same

can you suggest a best approach for this scenario, thanks

**Comment by wmathurin** [comment]
This is getting address in 8.2: see https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Hybrid/pull/138
For an example of the js code see: https://github.com/forcedotcom/SalesforceMobileSDK-Shared/pull/522
