### ISSUE TITLE
unable to install pluguin

### ISSUE THREAD

**Issue by sarathi0333** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#492]
I tried to execute forcehybird create, which is successful. After that i removed the plugin by executing cordova plugin remove com.salesforce

Then i tried to add it back
 
cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin --force
has no response on the terminal and the plugin is not getting installed

Node JS Version: 12.14.0
NPM version: 6.13.4
Cordova version: 9.0.0
forcehybrid version: 8.0.0

**Comment by wmathurin** [comment]
Could you try with cordova CLI 8.1.2 ?

**Comment by sarathi0333** [comment]
Hi @wmathurin . i tried with Cordova CLI 8.1.2 as advised. But still it doesn't work.

**Comment by wmathurin** [comment]
Looks like a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/493

**Comment by wmathurin** [comment]
Let's continue discussing on the other issue.
