### ISSUE TITLE
Unable to install previous versions of mobileSDK

### ISSUE THREAD

**Issue by Pranav-Suresh** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#493]
when trying to install version 7 of salesforceMobileSDK, using cordova plugin add **https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v7.0.0** I am unable to get any logs post the command

Node Version - 12.14.0
Cordova - 9.0.0

**Comment by wmathurin** [comment]
Could you try with cordova CLI 8.1.2?

**Comment by Pranav-Suresh** [comment]
@wmathurin  Thanks for the reply. I tried by downgrading the CLI to 8.1.2, but no luck! Still I am unable to download the exact version of the mobileSDK. 

But I am able to download the version 8 of the SDK by adding the tag #v8.0.0 only, It is not downloading without the tag.

**Comment by wmathurin** [comment]
> But I am able to download the version 8 of the SDK by adding the tag #v8.0.0 only, It is not downloading without the tag.

That sounds like a limitation with the cordova CLI.

**Comment by Pranav-Suresh** [comment]
> > But I am able to download the version 8 of the SDK by adding the tag #v8.0.0 only, It is not downloading without the tag.
> 
> That sounds like a limitation with the cordova CLI.

If that is the case, then #v8.0.0 should also be non-downloadable right just like #v7.0.0?

**Comment by wmathurin** [comment]
Not sure what you mean by 

> If that is the case, then #v8.0.0 should also be non-downloadable right just like #v7.0.0?

**Comment by Pranav-Suresh** [comment]
> Not sure what you mean by
> 
> > If that is the case, then #v8.0.0 should also be non-downloadable right just like #v7.0.0?

I meant to say, if it is a cordova limitation then how am I not able to download #v7.0.0. Because I am able to download the version 8 by adding the tag #v8.0.0 right?

**Comment by wmathurin** [comment]
What Cordova iOS version are you using?
Mobile SDK 7.0 works with 4.5.5 (see https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/blob/v7.0.0/plugin.xml#L34) while Mobile SDK 8.0 works with 5.0.0 (see https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/blob/v8.0.0/plugin.xml#L34).

**Comment by wmathurin** [comment]
We haven't heard back since our last suggestions / questions. Closing issue for now.
