### ISSUE TITLE
CORS issue: Origin null is not allowed

### ISSUE THREAD

**Issue by sarathi0333** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#495]
Hi, 
I am migrating my app to **MobileSDK 8.0.0** where i am facing an issue.
![err](https://user-images.githubusercontent.com/25176128/72159887-3d5fb100-33b5-11ea-96d3-3e31c8c2c974.png)

I am able to pass through the authentication process. After that i have an apex call to an endpoint which fails due to **CORS**.
I checked on the _config.xml_, there `allow Origin` has been configured as `'*'`. But the same end point works seamlessly in Mobile SDK version 4.0.0.

Testing on code base created using forcehybrid CLI 8.0.0, Cordova 8.1.2. on iOS 12 and 13.

**Comment by wmathurin** [comment]
In Mobile SDK 4.0, the web view used was UIWebView which does not prevent cross origin calls.
In newer versions of Mobile SDK, the web view is now WKWebView (Apple has deprecated UIWebView years ago and will no longer accept apps using it later this year). WKWebView prevents cross origin calls, so a hybrid local application cannot make XHR calls to the server directly. Instead it should use our network plugin directly or through force.js.
