### ISSUE TITLE
Cross Origin requests are only supported for HTTPS.

### ISSUE THREAD

**Issue by sarathi0333** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#496]
Hello,

I am migrating my application from Mobile SDK 4.0.0 to latest version 8.0.0. I am able to make xhr calls when using apex request via force.JS as advised. [Thanks for that].

Now the problem is that the application is based on Ionic 1 - angular 1. when i try to route to different path, I am get **CORS** error.

![error2](https://user-images.githubusercontent.com/25176128/72240238-6b263f00-35db-11ea-8ca3-9e356d951517.png)

As the app is trying to fetch a html template `file://.../*.html`

Does Mobile SDK 8.0.0 supports Single page application like **Angular JS 1** ?

**Comment by wmathurin** [comment]
The web view the web app is rendered into has changed from UIWebView to WKWebView. Apple has deprecated UIWebView (for more information see: https://developer.apple.com/news/?id=12232019b).
Unlike most browsers, UIWebView does not prevent CORS so one can make XHR call to the server from a locally loaded resource. WKWebView however does prevent CORS.

When you use force.js, the call is actually going through the container's network stack which does not have CORS limitation.

So there is only two solutions:
1) If you have an hybrid local app (i.e. with locally loaded resources), make sure all network calls are done through force.js
2) If that is not possible, convert your application to a hybrid remote application, by hosting all the html/js/css on Salesforce.

**Comment by wmathurin** [comment]
Nothing else we can do in the SDK - see my last comment. Closing issue.
