### ISSUE TITLE
Salesforce mobile sdk based hybrid app using cordova on wk webview fails to load external scrips/images

### ISSUE THREAD

**Issue by Manjeetmetacube** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#499]
Hi,

We have salesforce mobilesdk based cordova hybrid app. Right now we are on SDK version 7.3 which is using UI webview. Now we need to upgrade it to WKweb view. When we did so we faced below issues:

1. Images from server are not loading up
<img src ="path to salesforce backend">

it fails to load the image from server.

2. External script(lets say somewhere at server in static resource) is not loading up in application.
these script are also fails to load up.
Please suggest something on this.

@bhariharan

**Comment by wmathurin** [comment]
It is not a bug with Mobile SDK. It's due to CORS enforcement by WKWebView.
* Hybrid local apps should only have local resources and do networking through the Mobile SDK network plugin (or through force.js which makes use of it).
* Hybrid remote apps can only interact with the server they are hosted on.

**Comment by Manjeetmetacube** [comment]
These resources javascript files and images are coming from server only. We are using forctk library for getting data which is working fine with us but images and scripts are not loading up. Lets suppose I need to load some file framework.js which is on same server as below URL

https://*******--*******--c.cs7.visual.force.com/resource/1580396737000/Framework/js/framework.js

But it fails to load and says some session problem. 

Same happens with the images also 
https://*******--*******----c.cs7.content.force.com/servlet/rtaImage?eid=003M0000010MZv6&feoid=00NM0000001UiLw&refid=0EMM0000000DGJP

These images fails to load. 

These all images and javascript files were loading properly on UIWebview.

**Comment by wmathurin** [comment]
You have an hybrid local app?

**Comment by Manjeetmetacube** [comment]
Yes its hybrid local app

**Comment by wmathurin** [comment]
That violates CORS (UIWebView does not enforce CORS). 
Hybrid local app is served from file:/// so it can't get resources from https://------c.cs7.content.force.com. You should not fetch them through the network plugin and "inject" them in your page.

**Comment by Manjeetmetacube** [comment]
So what is suggested way then for this in hybrid local app ? like I want to display server images in my app. 

Will it work in hybrid remote app?

**Comment by Manjeetmetacube** [comment]
By below these two plugins we were able to load the local images in app which was not working earlier : 

https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix
cordova plugins add cordova-plugin-wkwebview-file-xhr

**Comment by wmathurin** [comment]
It will work in an hybrid remote app.
For an hybrid app, you could get the image binary through the network plugin then inline them in the page (like http://www.websiteoptimization.com/speed/tweak/inline-images/).

**Comment by Manjeetmetacube** [comment]
you could get the image binary through the network plugin . What do you mean by this?Will  these plugin able to load/download the image from given image URL? 
and then I convert it to the image data url at run time. which will then able to show the image properly?

**Comment by Manjeetmetacube** [comment]
one more thing will these network plugin be able to load script files also? and then I run these scripts at run time ?

**Comment by wmathurin** [comment]
Best way to use the network plugin is by using `force.js`.
To download binary resource from some URL, you could use the [anyrest](https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/master/libs/force.js#L941) method.
When you pass true for the returnsBinary parameter, the response passed to your callback is returned as `{encodedBody:"base64-encoded-response", contentType:"content-type"}`.

To inline a script, you could do:
```javascript
var script = document.createElement("script");
script.innerHTML = content; /* response's body of your anyrest call */
document.body.appendChild(script);
```

To inline an image, you could do:
```javascript
var img = document.createElement("img");
img.src = "data:image/png;base64,xxx"; /* xxx is the base 64 encoded response's body of your anyrest call */
...
```

**Comment by Manjeetmetacube** [comment]
Is such 'anyrest' method exist in forcetk.js library also? Currently we are using forcetk.js library in project.

**Comment by wmathurin** [comment]
[force.js](https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/master/libs/force.js) is a replacement for forcetk.js that we introduced several years ago.
It works both in a browser and within an hybrid app.
It will use the network plugin if available and xhr otherwise.
It has the same methods plus a few additional ones like anyrest.
You should use force.js and not forcetk.js.

**Comment by Manjeetmetacube** [comment]
hI @wmathurin ,

Just to update the above approach does not work directly, I had to make a frontdoor call at start of application. After that only resources started loading.

**Comment by va1bhav** [comment]
@Manjeetmetacube  Could you please elaborate how did you make this work for you? I am facing the same issue.

**Comment by Manjeetmetacube** [comment]
Hi Sorry missed your reply @va1bhav .
are you still facing this issue?

**Comment by va1bhav** [comment]
@Manjeetmetacube Yes I am, can you please elaborate how did you make hybrid local app scripts work for you?

**Comment by Manjeetmetacube** [comment]
Do the authentication using force.js library . After this you can specifically give the session to your DOM elements, so that all the browser load call can load the resources properly.You can use frontdoor for this.

You can create an image tag and then give it src with front door appended in it.

**Comment by va1bhav** [comment]
@Manjeetmetacube Thanks for the details however I could not fully understand how this would work for me, can we connect offline for this, could you please send me a meeting invite at vaibhavgoel1212@gmail.com to talk through?

Thanks!

**Comment by Manjeetmetacube** [comment]
Sure. manjeetmnit1986@gmail.com
