### ISSUE TITLE
`4.2.0` supports only `UIWebView`. `4.3.1` supports both `WKWebView` and `UIWebView`, but defaults to `UIWebView`. You can override the default setting and use `WKWebView` though. In our next release, we will support only `WKWebView` (check out the latest on our `unstable` branch for a sneak preview).

### ISSUE THREAD

**Issue by Manjeetmetacube** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#500]
`4.2.0` supports only `UIWebView`. `4.3.1` supports both `WKWebView` and `UIWebView`, but defaults to `UIWebView`. You can override the default setting and use `WKWebView` though. In our next release, we will support only `WKWebView` (check out the latest on our `unstable` branch for a sneak preview).

_Originally posted by @bhariharan in https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/229#issuecomment-250240763_

**Comment by bhariharan** [comment]
Why is this open as an issue? `Mobile SDK 4.x` was released over 4 years ago, we're on `Mobile SDK 8.1.0` now. Apple has stopped accepting apps that use `UIWebView` in the App Store. As a result, we only support `WKWebView` going forward.
