### ISSUE TITLE
Migration of existing apps from AngularJS to Angular

### ISSUE THREAD

**Issue by vsvikram** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#502]
Hi,

We have an existing app running on `Cordova 9.0.0`, `forcehybrid CLI 7.3.0` and `Salesforce SDK 7.2.0` which is built using `AngularJS v1.7.5`.

As it is known that AngularJS is deprecated and is not actively supported (`v1.7.x` is in LTS till July 2021), we have to migrate our existing apps to the Angular latest version (`v9.0.0`).

We are trying to figure out a recommended approach for creating a `Cordova` project with `Angular` and `Salesforce Mobile JS SDK`.

Below is one such approach which doesn't mention anything about Salesforce Mobile SDK integration in the project:

`https://medium.com/@EliaPalme/how-to-wrap-an-angular-app-with-apache-cordova-909024a25d79`
 
@wmathurin @bhariharan , Can you please guide us on the recommended approach to migrate our existing AngularJS apps to Angular (Typescript) based app using Salesforce Mobile SDK?

Should we still use `forcehybrid` CLI for creating the starter project?

**Comment by wmathurin** [comment]
We recommend you start with forcehybrid.
For more help with Angular, we recommend you post your question on our [stackexchange](https://salesforce.stackexchange.com/questions/tagged/mobilesdk). Github issues are reserved for bugs/issues in the SDK.
