### ISSUE TITLE
Salesforce mobile sdk 8.1.0 configure request timeout interval.

### ISSUE THREAD

**Issue by Manjeetmetacube** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#503]
Hi
We have a Salesforce mobile sdk based hybrid local app using cordova. We are making request through force js which uses network plugin. Is there way we can configure the request timeout from our javascript side and pass it on to network plugin?

Right now I think currently request timeout is configured to be 2 mins. 

@wmathurin

**Comment by wmathurin** [comment]
You can't do it from the javascript side. But you could do it from the java side of your application.
See https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1476

**Comment by Manjeetmetacube** [comment]
Hi,

We are using ios mobile app also. Where can we do in ios app?

**Comment by Umesh079** [comment]
@Manjeetmetacube  can you give your project info?? what tech stack are you using Cordova + angular js or plain javascript

**Comment by Manjeetmetacube** [comment]
Hi @Umesh079  Sorry missed your message. My project is a hybrid app. Which usage below technologies :
Cordova
Ext JS
and few other Javascript frameworks included in that.

**Comment by Manjeetmetacube** [comment]
Hi, 
@wmathurin 

Can you please guide on the below question? 

We are using ios mobile app also. Where can we do in ios app?

We want this timeout value as configurable. We want to read this value from backend and accordingly change the request timeout.

**Comment by wmathurin** [comment]
On iOS, you can provide your own NSURLSessionConfiguration: see [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/RestAPI/SFNetwork.h#L95).

It's through the NSURLSessionConfiguration that you can configure the request timeout: see [here](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1408259-timeoutintervalforrequest?language=objc).

**Comment by rahuljangid19** [comment]
> You can't do it from the javascript side. But you could do it from the java side of your application.
> See [forcedotcom/SalesforceMobileSDK-Android#1476](https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1476)

Hi,
We have followed the above steps in the link. But we can't find any setters for connectTimeout or readTimeout in okHttpClient class. Is there any other way we configure the request timeout for android?

**Comment by wmathurin** [comment]
You can provide your own ok http client (see https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/ef3e494c1ecf8c346dcf9b3cdefaf8e4b6881720/libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestClient.java#L178).
There are plenty of example online on how to set the timeout. See https://www.baeldung.com/okhttp-timeouts for example.
