### ISSUE TITLE
Salesforce mobile sdk 8.1.0 app stays in background after logout.

### ISSUE THREAD

**Issue by Manjeetmetacube** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#504]
Hi
We have a Salesforce mobile sdk based hybrid local app using cordova. After we logout our app page stays in background. And it can be seen whenever we switch from production to sandbox screen or vice versa. How can we destroy the page completely?

**Comment by wmathurin** [comment]
How are you logging out?

**Comment by wmathurin** [comment]
We need more information. Closing issue for now.
