### ISSUE TITLE
Salesforce mobile sdk 8.1.0 retrive request failure message

### ISSUE THREAD

**Issue by Manjeetmetacube** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#505]
Hi 
We have a Salesforce mobile sdk based hybrid app using cordova. We are making request through force js which uses network plugin . The error message we get when the request fails is ‘The operation couldn’t be completed. (Path error errorcode.)’

Is there a way we can retrieve the error code and message behind the failure.I man the complete failure message which can give more information about failure. 

Right now for that we had to some backend changes which I don’t want to do. Can you please suggest something for which we don’t do any custom changes at backend side.

**Comment by wmathurin** [comment]
Unfortunately, right now only the message of the java exception is being sent back to the error handler.
Maybe something we could enhance in the future.
Thanks for the feedback.

**Comment by wmathurin** [comment]
Are you having the issue on iOS or Android?

**Comment by wmathurin** [comment]
This was addressed in 8.2.
See https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Hybrid/pull/138 and https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2095.
