### ISSUE TITLE
Salesforce mobilesdk based cordova hybrid app not able to show login page

### ISSUE THREAD

**Issue by Manjeetmetacube** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#506]
Hi,

On ios 13 + SDK version 7.3(which have WKwebview as default) issue is coming. Application is not showing the login page.

It shows a error popup and message as below: 
Can't connect to the server:The operation couldn't be completed.Operation not permitted.

This error pop up is coming from salesforce mobils sdk code only. 
I can see localizable.string file contain this string as below :

"authAlertConnectionErrorFormatString" = "Can't connect to the server: %@";

Any idea what can cause this error?

**Comment by Manjeetmetacube** [comment]
@wmathurin

**Comment by wmathurin** [comment]
What login server do you have configured?

**Comment by Manjeetmetacube** [comment]
the login server is login.salesforce.com. 

First it makes below logs 
FrameLoader::prepareForLoadStart: Starting frame load 
then progress stated 
and after this one error as below comes : 
containermanagerd <Notice>: command=<private>, client=<private>, error=<private>

Dont know why its throwing this error?

and after this pop up messages for can not connect to server comes up.

**Comment by wmathurin** [comment]
Did you generate your application with forcehybrid?
If you didn't, could you try generating an application with forcehybrid and try that first.
Also could you use the latest our latest version (8.1).

**Comment by wmathurin** [comment]
Didn't hear back / unable to repro here so closing issue. Please re-open issue if this is still happening with the latest version of Mobile SDK.
