### ISSUE TITLE
Problem regarding Smartstore with Android

### ISSUE THREAD

**Issue by akshayajeevan** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#508]
Hi,

Currently our app is running with older version(6.1.0) of Salesforce Mobile SDK (migrating to new version is in-progress). Recently, we are facing an issue with the smart store in the app. 

When user works on the app, all the data are stored in different soups (and all these are in user-based stores). Now when app queries the data to send it to Salesforce server, the query returns 0 records. But when user re-login, the same query is returning all expected records.

Could this something related to user session or amount of data in soups? 
I am still investigating as this is happening intermittently in our prod env.

Please help if you have come across similar problem. Thank you!

**Comment by wmathurin** [comment]
6.1 was released over two years ago. Any chance, you could try with the latest version of the SDK (8.1)?
Are you seeing errors in the logs?

**Comment by akshayajeevan** [comment]
@wmathurin 
The work for upgrading the SDK to 8.0 is in-progress. 

We are trying to replicate the issue on lower env but not success yet. There is no error on log also.

**Comment by wmathurin** [comment]
We have not seen that issue.
Are you using mobile sync (previously called SmartSync) or just smartstore?
When a user logs out, user stores are wiped, so I'm not sure I follow your repro steps?
Finally have you tried SmartStore inspector to inspect SmartStore content at run time (https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/tools_dev_support.htm)?

**Comment by akshayajeevan** [comment]
We are using smartstore only. 
We have `switchToUser()` from `com.salesforce.sfaccountmanager` option on app where user can enter the credentials again. No user stores are wiped here.
We are looking for a new usecase to try the smartstore inspector.

**Comment by wmathurin** [comment]
Are you holding on to an instance of SmartStore or are you getting the SmartStore instance only when you need it?

**Comment by akshayajeevan** [comment]
I am getting the smartstore instance whenever required. 
Here is the query causing this issue -
```
var smartSql = 'select {_queue:_soup} from {_queue} where {_queue:state} IS NULL or {_queue:state} = "null" order by {_queue:objectName}';
var querySpec = navigator.smartstore.buildSmartQuerySpec(smartSql, 1e8);
navigator.smartstore.runSmartQuery(false, querySpec, successCall, errorCall);
```
In success call, the no of records are zero. After `switchToUser`, this query shows all the records.

**Comment by Manjeetmetacube** [comment]
Have you tried to run this query like by dividing it? or may be without putting any condition?Is that return you record?

**Comment by akshayajeevan** [comment]
Closing this as we have migrated to new version of SDK.
