### ISSUE TITLE
Push Notification registration for logged-in account

### ISSUE THREAD

**Issue by akshayajeevan** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#518]
We enabled the push notification for an existing app. But the app is not registering the tokens in Salesforce. On analyzing we found out SDK registers the push notification when user logs-in successfully. 
But due to business requirement, users don't logout and session is maintained always. 

Is there way to initiate the registration when logged-in user opens the app?

This is not a bug but could be an option to have in SDK.

**Comment by wmathurin** [comment]
Are you on iOS or Android (or both)?
Have you already checked the relevant documentation: https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/push_intro.htm

**Comment by akshayajeevan** [comment]
The app is on Android (hybrid).

The implementation is same as mentioned in the doc.

**Comment by bbirman** [comment]
On Android the SDK handles keeping the token alive by re-registering every six days but you can also use `registerSFDCPush(Context context, UserAccount account)` in `PushMessaging.java`

**Comment by bhariharan** [comment]
As @bbirman mentioned above, the SDK handles periodic re-registration. If you need to explicitly trigger a fresh registration, you could call the API mentioned above.

**Comment by akshayajeevan** [comment]
Hi @bbirman @wmathurin @bhariharan 

When I explicitly trigger a fresh registration using the above API (and also I used force.js to create a record in `MobilePushServiceDevice`), I am getting below error response for users in my PRD env. 

Error response - **[{"errorCode":"NOT_FOUND","message":"The requested resource does not exist"}]**

Do you have any idea why we get this error?

I found this on stack exchange - [link](https://salesforce.stackexchange.com/a/84542/63891) but not sure if this could be a reason.

**Comment by bhariharan** [comment]
@akshayajeevan That message means that your org isn't provisioned with the correct perms required to enable rich push notifications.

**Comment by akshayajeevan** [comment]
Hi @bhariharan 

We checked our org and it has all the perms required for push notification to work. 

We are also trying to find if the logged-in user session (access token) has some role play here. If this is the case then other APIs (like apexrest, describe, etc) should fail with same error, but all are working fine. Do you agree with this?
