### ISSUE TITLE
How to use mobilesdk plugin with ionic capacitor?

### ISSUE THREAD

**Issue by ramanathansj** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#519]
Is it possible to share steps/tutorials to add mobile sdk plugin to ionic capacitor projects? the existing material seems to be updated with cordova only. I understand salesforce doesn't support capacitor, so any help is appreicated.

**Comment by bhariharan** [comment]
This forum is reserved for bugs/issues with our code. For other queries, please use `Salesforce Stack Exchange`. Also, we don't support the `ionic CLI` or `Capacitor` at the moment. You will need to generate a project using `forcehybrid` and then manually add `Capacitor` plugins in to the generated project.
