### ISSUE TITLE
Getting "cross origin requests are only supported for http" error after login  in salesforce based cordova local hybrid app #IOS

### ISSUE THREAD

**Issue by subhendussd** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#520]
### We have salesforce(8.2.0) based Cordova local hybrid app. After login getting "cross origin requests are only supported for http" error during file load. 

configuration
-----------------
Salesforce mobile SDK Cordova plugin version:   8.2.0
Cordova ios:   5.1.1
Type of application:  Local

<img width="990" alt="Screenshot 2020-08-13 at 12 21 30 PM" src="https://user-images.githubusercontent.com/18515928/90470289-b0de5380-e138-11ea-83fd-632c02b06db5.png">

Please help me to resolve the issue.

As per Cordova-ios 6.0.0 official release note, they mention  bellow point 

_**Moved WKWebView support into Cordova-iOS and removed UIWebView code
Due to this change, the cordova-plugin-wkwebview-engine plugin is obsolete and will not work with this release. If you have this plugin installed, it is safe to remove with cordova plugin remove cordova-plugin-wkwebview-engine.

Additionaly, WKURLSchemeHandler support has been introduced with this release. _**Using a custom scheme to serve your app content through fixes CORS issues that exist because of the strict security policies that WKWebView has applied to the file scheme. You can easily configure your Cordova project to use a custom scheme by setting the preference options scheme and hostname in the config.xml file._****_

<preference name="scheme" value="app" />
<preference name="hostname" value="localhost" />

If this is the solution then please provide the new salesforce mobile SDK Cordova plugin which supports Cordova ios 6.0.0.
 @bhariharan
thanks in advance

**Comment by akshayajeevan** [comment]
Meanwhile you can try using plugin [cordova-plugin-wkwebview-file-xhr](https://github.com/oracle/cordova-plugin-wkwebview-file-xhr) for CORS workaround. 
Check [cordova-ios#835](https://github.com/apache/cordova-ios/issues/835#issuecomment-665359984) & [cordova-ios#883](https://github.com/apache/cordova-ios/issues/883#issuecomment-637559770)

**Comment by subhendussd** [comment]
> Meanwhile you can try using plugin [cordova-plugin-wkwebview-file-xhr](https://github.com/oracle/cordova-plugin-wkwebview-file-xhr) for CORS workaround.
> Check [cordova-ios#835](https://github.com/apache/cordova-ios/issues/835#issuecomment-665359984) & [cordova-ios#883](https://github.com/apache/cordova-ios/issues/883#issuecomment-637559770)

After adding the cordova-plugin-wkwebview-file-xhr and modifying the config.XML file still, I am getting the same error. Please suggest me if any things else I have to do apart from adding the plugin and modifying the preference.
` <preference name="InterceptRemoteRequests" value="none" />
    <preference name="AllowUntrustedCerts" value="on" />`

**Comment by bhariharan** [comment]
@subhendussd We will support `Cordova 6.0` in a future release.

**Comment by subhendussd** [comment]
> @subhendussd We will support `Cordova 6.0` in a future release.

Thanks for your reply @bhariharan . it's a kind of blocker for me as we know Apple will no longer accept submissions apps that use UIWebView as of December 2020.

**Comment by subhendussd** [comment]
Hi @bhariharan we are getting below error in the command line when we follow below steps

.1 Run "forcehybrid create"  then select Platform IOS
 2.Run "cordova platform add ios@6.1.1"  then we see below error

`Plugin doesn't support this project's cordova-ios version. cordova-ios: 6.1.1, failed version requirement: 5.1.1
Skipping 'com.salesforce' for ios`

We referred the link:
[](https://trailhead.salesforce.com/content/learn/modules/mobile_sdk_hybrid/mobilesdk_hybrid_getting_started)

**Comment by bhariharan** [comment]
@subhendussd The error message is self-explanatory - we don't support `Cordova 6.1.1` at this time, you'll need to use `Cordova 5.1.1` with the latest version of `Mobile SDK`. Also, this version has no references to `UIWebView`, so it should be safe to submit to the `App Store`.

**Comment by subhendussd** [comment]
@bhariharan Thanks for the quick reply.

I have checked Cordova-ios 5.1.1 seems to have references of UiWebView as given in the release notes please refer the link for the details
https://cordova.apache.org/announcements/2019/12/02/cordova-ios-release-5.1.1.html

I greatly appreciate your help on this issue for a fix of issue.

**Comment by wmathurin** [comment]
You have two options:
1) if you have/want a hybrid local application: only call the server through Mobile SDK network plugin - the easiest way to do that is to use the helper library https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/dev/libs/force.js in you code.
2) use a hybrid remote application meaning host your html/css/js on the server. That way you won't run into CORS issues.

**Comment by wmathurin** [comment]
Closing issue - see my previous comment for work arounds.
