### ISSUE TITLE
SSL Certificate Pinning

### ISSUE THREAD

**Issue by ErickdaCosta** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#522]
Hi everyone, I am trying to implement SSL Certificate Pinning in a Cordova application integrated with SalesforceMobileSDK-Cordova-Plugin. Is there any way to implement this? Thanks in advance.

**Comment by wmathurin** [comment]
What are you trying to do?
You will have to do the work from the native side of the application.

**Comment by wmathurin** [comment]
Github issues are meant for bugs or enhancement requests.
For "how do I implement ?" questions, we recommend you post on [stack exchange](https://salesforce.stackexchange.com/questions/tagged/mobilesdk).
