### ISSUE TITLE
Mutual Authentication on SalesforceMobileSDK

### ISSUE THREAD

**Issue by postmeback** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#523]
We are trying to implement **mutual authentication** in a cordova app. But, we are unable to find any related article / tutorial about it. It is becoming very tough for us to implement it, at the same time we have to do it due to security reasons.

**Please help us out.**

**Comment by wmathurin** [comment]
Please see the documentation here: https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/auth_identity_providers.htm
