### ISSUE TITLE
Browser platform support

### ISSUE THREAD

**Issue by sethking-crisphealth** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#526]
I need to run our mobile app via a browser using `cordova run browser` for demo purposes. I see that there's only Android and IOS currently supported. Is there any way we can get the browser platform?

**Comment by wmathurin** [comment]
The Mobile SDK provides a set of commonly used native mobile libraries for devs that are building apps that use to Salesforce as a back-end. We have the cordova plugin for developers that prefer to build their apps using html/js rendered in a webview. 
It provides no value (and won't work) if you run in the browser. So it does not make sense for use to add the browser platform.
