### ISSUE TITLE
We discovered one or more bugs in your app when reviewed on iPad running iOS 14.1 on Wi-Fi.

### ISSUE THREAD

**Issue by wang317569784** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#527]
We are using Salesforce Mobile SDK for app development. But when we upload the SDK to Apple store, Apple rejected the App for the following reasons 

We discovered one or more bugs in your app when reviewed on iPad running iOS 14.1 on Wi-Fi.

Seems the SDK is not compatible with iPad iOS14.1. Is there anyone who can help?

Thanks a lot!

Regards,
Sam

**Comment by wmathurin** [comment]
Could you provide more information? What are the bugs? Are you sure they are not in your application code?

**Comment by wmathurin** [comment]
Closing issue since no further information was provided.
