### ISSUE TITLE
Cannot enable Login using a Custom Domain Login Screen

### ISSUE THREAD

**Issue by mappmechanic** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#53]
I have a Connected App in Salesforce for which I am creating a Cordova Hybrid App. I want to show a custom branded login page for which I have created a Custom Domain and changed background colour and logo for it.

I was finding it very difficult in the iOS & Android projects to describe the initial login URL. I tried setting it in the ForceJS and even in Cordova plugin but was unable to do so. I finally posted this problem on Google+ & Kevin Hawkins suggested that in iOS there is a hidden plist property that needs to be added.

I added that property and it started working fine for iOS but still I cannot sign in using any user credentials which does not belong to the salesforce org on which the connected app exists. My app is intended to be used by users from other orgs also.

**Comment by wmathurin** [comment]
Please post your question to the Mobile SDK google + community (https://plus.google.com/communities/114225252149514546445).
Github issues are only used for actual bugs (or enhancements requests).
