### ISSUE TITLE
'SalesforceHybridSDK/SFHybridViewController.h' file not found

### ISSUE THREAD

**Issue by limbanmichael** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#531]
Hello, I am having an error when trying to build my project in xcode, this is after upgrading from version 7.*.* to 8.0.0. Please take a look at the screenshot

<img width="1351" alt="Screen Shot 2021-01-03 at 9 49 01 PM" src="https://user-images.githubusercontent.com/22585095/103592861-22277300-4f2f-11eb-9968-b376288e56a8.png">

Ionic:

   Ionic CLI         : 5.1.0
   Ionic Framework   : ionic1 1.3.3
   @ionic/v1-toolkit : 2.0.20

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 28 other plugins)

Utility:

   cordova-res : 0.5.1 (update available: 0.15.2)
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/mlimban/Library/Android/sdk/)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v10.15.3 (/Users/mlimban/.nvm/versions/node/v10.15.3/bin/node)
   npm               : 6.4.1
   OS                : macOS Catalina
   Xcode             : Xcode 11.5 Build version 11E608c

**Comment by wmathurin** [comment]
For upgrades, we recommend you follow the steps outlined in our [documentation](https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/migration_all_82_83.htm): re-create the application using latest forcehybrid, add back your plugins and html/css/js. How did you proceed?

**Comment by wmathurin** [comment]
Waiting to hear back.
Using `forcehybrid` to generate the application, I am unable to repro your issue.

**Comment by CrazyYanger** [comment]
Hello, I am facing the same issue:
<img width="1029" alt="Screen Shot 2021-01-20 at 11 16 48 AM" src="https://user-images.githubusercontent.com/12792848/105122381-103df680-5b11-11eb-99c2-2b981a30dee6.png">
I was following this guidance [https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/hybrid_lightning_web_components.htm]

forcehybrid create
Enter the target platform(s) separated by commas (ios, android): ios
Enter your application type (hybrid_local or hybrid_remote or hybrid_lwc, 
    leave empty for hybrid_local): hybrid_lwc
Enter your application name: flow
Enter your package name: com.acme.apps
Enter output directory for your app (leave empty for the current directory): flow

Then I opened the .xcworkspace file build the project that error happened.
Xcode version: 12.3
forcehybrid version: 8.3
Cordova version: 10.0.0

Can you help me take a look?

**Comment by wmathurin** [comment]
I just tried locally using forcehybrid 8.3, xcode 12.3, cordova 10.0.0 and I was able to build and run the generated app without errors. In XCode, could you go to File -> Workspace Settings and make sure it uses the Legacy Build System (it should do that automatically)?

**Comment by jsitu** [comment]
I am having the same issue...
