### ISSUE TITLE
iOS: Exception - SFHybridViewController setSb_statusBarStyle:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by akshaybabus** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#538]
I am getting the exception "SFHybridViewController setSb_statusBarStyle:]: unrecognized selector sent to instance" when using the Salesforce Mobile SDK with Cordova Statusbar plugin.

Steps to Replicate:
1. Create a forcehybrid project
2. Add the platform cordova-ios@5.1.1
3. Add the plugin cordova-plugin-statusbar
4. Add the plugin Salesforce Mobile SDK Cordova Plugin 8.3.0
5. Set the value of "shouldAuthenticate" as false in the bootconfig.json
5. Run the command "cordova prepare"
6. Build and run the app in the simulator.
7. The issue will be experienced.

Environment:
Node 12.16.3
NPM 6.14.4
Cordova 9.0.0
cordova-ios 5.1.1
Salesforce Mobile SDK Cordova Plugin 8.3.0
cordova-plugin-statusbar 2.4.3
macOS Cataline 10.15.5
Xcode 11.5

I would really appreciate a quick resolution to this issue.

Thanks in advance

**Comment by wmathurin** [comment]
It's breaking because the status bar plugin extends CDVViewController (meaning it adds methods through a category) and Mobile SDK hybrid apps are using SFHybridViewController instead of CDVViewController. 

For more information and a workaround see: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3126#issuecomment-580002570

**Comment by akshaybabus** [comment]
While creating the new file by replacing CDVViewController with the SFHybridViewController. We are facing the 

Definition of 'CDVPlugin' must be imported from module 'SalesforceHybridSDK.CDVPlugin_SFAdditions' before it is required

I made the change and it's working now.

SFHybridViewControlller+Statusbar.h
![image](https://user-images.githubusercontent.com/8925138/105574000-8ea3ce00-5d87-11eb-98e8-81088e88a6ed.png)

SFHybridViewControlller+Statusbar.m
![image](https://user-images.githubusercontent.com/8925138/105574016-a8451580-5d87-11eb-91a3-725083391de4.png)
![image](https://user-images.githubusercontent.com/8925138/105574034-c579e400-5d87-11eb-837b-3ce8fd70a09e.png)
![image](https://user-images.githubusercontent.com/8925138/105574042-d591c380-5d87-11eb-988d-e76b6e8b64e2.png)
![image](https://user-images.githubusercontent.com/8925138/105574058-f0643800-5d87-11eb-9074-efe63016a65a.png)
![image](https://user-images.githubusercontent.com/8925138/105574086-37eac400-5d88-11eb-9f1c-b244592f8ffe.png)
![image](https://user-images.githubusercontent.com/8925138/105574100-4933d080-5d88-11eb-9a5d-81cac6c99db3.png)

Now, after launching the app, the app is stuck on the splash screen. 

[SalesforceSDKCore] CLASS: SFSDKAuthConfigUtil Org config request failed with error: Status Code: 404
