### ISSUE TITLE
iOS: Login Webview is giving error {"Domain":"WebKitErrorDomain","Description":"Frame load interrupted","AuthInfo":"<SFOAuthInfo: 0x282ee89a0, authType=SFOAuthTypeUserAgent>","Code":102}

### ISSUE THREAD

**Issue by akshaybabus** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#541]
I am getting the following error when doing Apple SSO from inside the login WebView

{"Domain":"WebKitErrorDomain","Description":"Frame load interrupted","AuthInfo":"<SFOAuthInfo: 0x282ee89a0, authType=SFOAuthTypeUserAgent>","Code":102}

Steps to replicate the issue:
1. Add the Cordova platform ios@5.1.1
2. Add the Salesforce Mobile SDK Cordova plugin v8.3.0
3. Set the value of "shouldAuthenticate" in the bootconfig.json to false.
4. Customize the login page at the Salesforce server by setting the value SFDCOAuthLoginHost in the Info.plist to the new custom login page and place a button for doing the Apple SSO (https://help.salesforce.com/articleView?id=sf.sso_provider_apple.htm&type=5).

5. In the javascript side, call the cordova.require('com.salesforce.plugin.oauth').authenticate()
6. Run the app
7. Tap on the Apple SSO button on the login page Webview
8. The iOS prompt appears asking the user to enter credentials/use Touch ID

![image](https://user-images.githubusercontent.com/8925138/107070866-e6bbe500-6809-11eb-984b-bf83d69b0381.png)

7. Once we enter credentials/use Touch ID, we get a popup
 
![image](https://user-images.githubusercontent.com/8925138/107071340-909b7180-680a-11eb-927a-5a7160ac6c55.png)

In the error callback of the cordova.require('com.salesforce.plugin.oauth').authenticate(), we get the following error message:
{"Domain":"WebKitErrorDomain","Description":"Frame load interrupted","AuthInfo":"<SFOAuthInfo: 0x282ee89a0, authType=SFOAuthTypeUserAgent>","Code":102}

I would really appreciate it if you could fix this issue ASAP.

Thanks in advance

**Comment by bhariharan** [comment]
In order to use `Sign in with Apple` with `Face  ID`, you need to enable advanced authentication in your org. This is because frame loads are not supported by `WKWebView` out of the box, but `ASWebAuthentication` does. Please refer our developer guide for instructions on how to enable advanced authentication in your app.

**Comment by akshaybabus** [comment]
Hello @bhariharan 

Thank you for your response. 

I have implemented the advanced authentication in the org using (https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/auth_advanced_using.htm)

I have implemented the advanced authentication in the Cordova app using (https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/auth_ios_advanced.htm)

But the issue still persists. Could you please provide the steps to enable ASWebAuthentication?

**Comment by bhariharan** [comment]
Activating advanced authentication requires:

- enabling the `"Use Browser Based Authentication on iOS"` checkbox in your org, under `My Domain` setup.
- adding a new custom  server and pointing the container to the `My Domain` URL configured above.
- following the client steps (adding `plist` and  `xml` entries) to ensure that it comes back to the app after auth completion.

Have you completed the above steps?
