### ISSUE TITLE
Please add SalesforceMobileSDK-CordovaPlugin to an NPM Registry 

### ISSUE THREAD

**Issue by sriramappnovation** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#555]
### This is strongly recommended for best practices. 

**Most of the CI/CD pipelines do not allow installation via a Github link. Therefore please add to NPM Registry.** 

_I have tried to fork and added it to the registry, however, there were breaking changes. Requesting Repo authors to do it as they are well versed with the lib and the dependencies_ 

https://www.npmjs.com/package/ionic-cordova-salesforce-hybrid-sdk

**Comment by dimosmertzanidis** [comment]
@wmathurin hi! Can you please publish the latest version to the NPM Registry?

Thanks

**Comment by dimosmertzanidis** [comment]
@bhariharan I got a notification that you are planning a publication to npmjs, do you have an estimation? Thanks 😊

**Comment by wmathurin** [comment]
The thing is `forcehybrid` does more than just `cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin`. For instance, on iOS it also removes the libCordova.a from embedded frameworks and set the build to "legacy". We are not doing those as a post install script when the plugin is added. So if we just publish the plugin on npmjs, people will run into those issues. We need to either document the extra steps or move the extra steps in a post install script.
So we are evaluating right now what to do.

**Comment by wmathurin** [comment]
Done: https://www.npmjs.com/package/salesforce-mobilesdk-cordova-plugin

**Comment by dimosmertzanidis** [comment]
@wmathurin thanks a lot 😊. A question, shoulder be submitted in [cordova-plugin-salesforce-sdk
](https://www.npmjs.com/package/cordova-plugin-salesforce-sdk) as a new version?
