### ISSUE TITLE
Help Needed!! Deferred login doesn't work

### ISSUE THREAD

**Issue by sriramappnovation** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#559]
### Help Needed!! Deferred login doesn't work

_**Did set the shouldAuthenticate value to false in bootconfig.json**_

If fails with the following error

`ERROR: TIMING com.salesforce.oauth:getAuthCredentials:1632510350826.9092 failed`

please help @wmathurin @bhariharan

**Comment by wmathurin** [comment]
We need more information: version of the SDK, type of application (hybrid local or remote) etc.

**Comment by sriramappnovation** [comment]
@wmathurin 

```
SDK version - SalesforceMobileSDK-CordovaPlugin.git#v9.1.1
ForceHybrid - hybrid_local 
```

**Comment by wmathurin** [comment]
I don't recognize
```javascript
const oauth = OAuth.createInstance();
```
Are you using `force.js`, are you using the `oauth` plugin directly?

**Comment by sriramappnovation** [comment]
I am just using the es6 version of the force.js file @wmathurin 

The force.js file from force_hybrid and the below link is from the same author. 

https://github.com/ccoenraets/forcejs

**Comment by wmathurin** [comment]
Did you edit the platform specific www/bootconfig.json like outline here: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/hybrid_deferred_login.htm

**Comment by gkotula** [comment]
Closing due to thread inactivity.
