### ISSUE TITLE
session timeout issue 

### ISSUE THREAD

**Issue by ny1014** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#561]
after session timeout, the app was logged out and back to the login view which I can't log in anymore by SSO so I have to reinstall this app and log in  ![IMG_0033](https://user-images.githubusercontent.com/59995400/142552815-741d9cd0-444a-47b4-8a5d-ed6b73b2f875.PNG)  

what I expected is 
![IMG_0034](https://user-images.githubusercontent.com/59995400/142552904-bae82f37-faa3-4684-8c60-a3c2f854cc83.PNG)

**Comment by wmathurin** [comment]
Is it a hybrid local (html/js bundled in client) or hybrid remote (visual force or lwc) ?

**Comment by ny1014** [comment]
it is a remote(lwc) project.

**Comment by wmathurin** [comment]
Just to be sure, you created a hybrid_lwc template (like described here: https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/hybrid_lightning_web_components.htm) ?

**Comment by ny1014** [comment]
yes, I created  a hybrid_lwc using that template.
also Im using advanced authentication and checked 'use browser login' on salesforce server. i can not get in to my visualforce page after logging in at first time and got "Caught login redirect from session timeout. Reauthenticating." looping. then I commanded out those code on SFHybridController.m, this way I can get into my visualforce page but yea there is where I am 
![cm](https://user-images.githubusercontent.com/59995400/142956612-3c620752-86ea-415e-936d-fa71361fcec4.png)

I can log in by using standard login page(not using browser) without commanded out those code but I still got session timeout problem

**Comment by ny1014** [comment]
![1](https://user-images.githubusercontent.com/59995400/142985377-866f1353-9643-4160-a476-9e76b295b631.png)
I got into this else condition when both log in by browser and session timeout, it doesn't work properly.

![2](https://user-images.githubusercontent.com/59995400/142985644-9a393fe1-f97d-47cd-abb5-d15040dfa512.png)

**Comment by ny1014** [comment]
<img width="1108" alt="infiloop" src="https://user-images.githubusercontent.com/59995400/144949294-84cc911c-f11e-40de-ab36-1450df141d04.png">
there is a infinite loop in else if block, I can log in using native browser now by put another bool condition in that else if condition. but it still logged out after session timeout.

**Comment by wmathurin** [comment]
We believe this [fix](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3620) should address the issue.
