### ISSUE TITLE
SDK 9.2 Ionic Cordova iOS build fails. Missing  sampleApp/platforms/ios/CordovaLib/Cordova/Info.plist

### ISSUE THREAD

**Issue by va1bhav** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#562]
I am building an ionic application for a client using SDK 9.2. With New Build system in Xcode. 

Scenario 1: Before adding Salesforce mobile SDK. Build works as expected with "New Build system" which is default Xcode setting.
Scenario 2: After adding Salesforce mobile SDK. Build fails with "New Build system" with error received in Xcode:
Build input file cannot be found: '/Users/vaibhav/Downloads/sampleApp/platforms/ios/CordovaLib/Cordova/Info.plist'

Scenario 3: After adding Salesforce mobile SDK. Build succeeds with "Legacy build system" which is deprecated.

Error 
<img width="865" alt="Screen Shot 2021-12-07 at 7 06 33 PM" src="https://user-images.githubusercontent.com/33320222/145038998-33d49935-6302-4624-bf78-c28259d50183.png">
<img width="532" alt="Screen Shot 2021-12-07 at 7 06 52 PM" src="https://user-images.githubusercontent.com/33320222/145039020-25e59aff-1c90-4366-9f1a-11ecf7b8ee12.png">

**Comment by wmathurin** [comment]
The error happens in the cordova library.
Cordova iOS does not seem to support the "new build system". For now, you have to use the "legacy build system".

**Comment by va1bhav** [comment]
@wmathurin I have verified that if I create a Ionic cordova application, I am able to build with new build system. But as soon as I add Salesforce hybird SDK, build does not work without "legacy build system". Could you please verify?

**Comment by wmathurin** [comment]
That's correct. 
NB: We don't officially support Ionic.

**Comment by va1bhav** [comment]
@wmathurin Thank you for your response, I built a vanilla cordova project to verify the same and the issue still persists with Salesforce SDK only. Could you please look into this if this can be fixed in next version? Thank you!

**Comment by rahulom** [comment]
Hi any update about this? I'm facing the same issue

**Comment by wmathurin** [comment]
Please try Mobile SDK 10.2 (released this morning) on Xcode 14.
Legacy build system has been removed from Xcode 14, and we have tweaked our generation script to create an application that builds without it.

**Comment by JeroenSchu** [comment]
@va1bhav did it work for you? We are still facing this issue, despite Mobile SDK 10.2.

**Comment by rahulom** [comment]
@JeroenSchu I'm still facing this issue, After i added this plugin the xcode is throwing so many errors.
If i use the default location for pre-user workspace settings it's throw me the  error 'After adding Salesforce mobile SDK. Build fails with "New Build system" with error received in Xcode:
Build input file cannot be found: '/Users/vaibhav/Downloads/sampleApp/platforms/ios/CordovaLib/Cordova/Info.plist' ',
and if i choose the workspace relative location getting another error, CDVWebViewEngine too  many errors emmited, stopping now.

**Comment by wmathurin** [comment]
What version of Xcode are you using ?

**Comment by wmathurin** [comment]
Do you mind opening a new issue with the details of what goes wrong when you archive?

**Comment by rahulom** [comment]
@wmathurin any updates ., i have created a new issue --
https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/608
