### ISSUE TITLE
Build is failing on Xcode 13.2.1

### ISSUE THREAD

**Issue by rskrthk** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#573]
I'm on sdk 8.2

While building the app on xcode 13.2.1 getting below error:

Multiple targets match implicit dependency for linker flags '-framework Cordova'. Consider adding an explicit dependency on the intended target to resolve this ambiguity. (in target 'AbbWorld' from project 'AbbWorld')

Target 'Cordova' (in project 'CordovaLib')
Target 'Cordova' (in project 'Pods'

<img width="248" alt="Screenshot 2022-01-27 at 1 47 01 PM" src="https://user-images.githubusercontent.com/41041720/151319036-1050e3a7-1fbf-4680-ab56-f70f5e5c955e.png">
)

**Comment by wmathurin** [comment]
To use the latest XCode, you need to use the latest Mobile SDK (9.2.1).
