### ISSUE TITLE
Build failing on Xcode 13.2.1 with New build system

### ISSUE THREAD

**Issue by rskrthk** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#577]
This is in reference with https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/573

Issue still exists (SDK 10.0) when I am trying to build with "New build system"

**Comment by wmathurin** [comment]
This has been addressed in Mobile SDK 10.2 (released this morning).
