### ISSUE TITLE
Black screen displayed during transition 

### ISSUE THREAD

**Issue by rskrthk** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#578]
SDK: v10.0
Tested on : iPad Pro (iOS 15.2)

Issue: Post login, before landing to home page, a black screen is displayed

**Comment by wmathurin** [comment]
Are you using a splash screen in your application?

**Comment by rskrthk** [comment]
> Are you using a splash screen in your application?

Yes

**Comment by wmathurin** [comment]
Closing the issue as it is quite old. Please open an new issue if it is still happening on the latest version of Mobile SDK.
