### ISSUE TITLE
Please add SalesforceMobileSDK-CordovaPlugin to an NPM Registry

### ISSUE THREAD

**Issue by dimosmertzanidis** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#588]
This is strongly recommended for best practices.
Most of the CI/CD pipelines do not allow installation via a Github link. Therefore please add to NPM Registry.

https://www.npmjs.com/package/ionic-cordova-salesforce-hybrid-sdk

**Comment by wmathurin** [comment]
Closing - this is a duplicate issue see https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/555
