### ISSUE TITLE
Support for cordova-android 11

### ISSUE THREAD

**Issue by dimosmertzanidis** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#594]
Hi team, Cordova-android 11 which supports Android API 31+ is available! 

Any plans for supporting the new release? 

This is crucial because due to the new Google Policy, Google will not accept new apps without Android 31+ support from August 1st.

Thanks

**Comment by dimosmertzanidis** [comment]
This is great @wmathurin, thanks a lot! I'll check it.

**Comment by gkotula** [comment]
We update `npm` packages with every release of Mobile SDK, so as soon as we release `10.2.0` it will be reflected there 👍   Closing as resolved.

**Comment by dimosmertzanidis** [comment]
@wmathurin, @gkotula  hi what is the plan for releasing 10.2.0?

Thanks

**Comment by wmathurin** [comment]
We are shooting for this week #safeharbor.

**Comment by dimosmertzanidis** [comment]
@wmathurin that's great, I hope everything will go smoothly 😊.
Please add it to npmjs as well when is ready. 

Thanks
