### ISSUE TITLE
App crashes upon being opened on iOS 13

### ISSUE THREAD

**Issue by ftcaeappno** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#596]
Device: iPhone 8, iOS 13.5.1
We recently upgraded the SalesforceMobileSDK 10.1.0 and the app is no longer opening on iOS 13.

App is working normally on iOS 14 and 15

**Comment by wmathurin** [comment]
Do you see anything in the logs that you could share?

**Comment by ftcaeappno** [comment]
Hello! Unfortunately not, since this is happening only on the device. When the app is opened it just closes after the splash screen.

**Comment by wmathurin** [comment]
Unfortunately without more information we can't do much. 
We have not seen the issue with our own apps (so far). Please re-open if you can get more information / repro steps.

**Comment by ftcaeappno** [comment]
@wmathurin how do you suggest us to collect the information? Also, did you guys try to reproduce the issue?

**Comment by ftcaeappno** [comment]
We are developing an app that will be launched on markets that have a big number of iOS 13 in use. Is there any official information telling that iOS 13 is not compatible SalesforceMobileSDK 10.1.0? If so, can you please provide me a link to this info so I can discuss with the client?

**Comment by wmathurin** [comment]
Do you get the crash on device with Xcode attached? Could you capture the logs then?

**Comment by wmathurin** [comment]
I will do a better job with the documentation going forward.
One option for you is to build an app for those users with Mobile SDK 9.2 since it had support for iOS 13.

**Comment by wmathurin** [comment]
Here is the section of the documentation that lists requirements for iOS: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/ios_requirements.htm

Mobile SDK 10.x supports iOS 14 and iOS 15 (10.2 should be compatible with iOS 16 also).
Mobile SDK 9.x supports iOS 13 and 14 (9.2 added compatible with iOS 15 also).
Mobile SDK 8.x supports iOS 12 and 13 (8.3 added compatibility with iOS 14 also).

You get the idea.

**Comment by ftcaeappno** [comment]
Thank you for the info, that's going to be useful for me to discuss with
the client!

**Comment by ftcaeappno** [comment]
Hello, please find attached the crash report.
[crash-report.txt](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/files/9192855/crash-report.txt)
.
