### ISSUE TITLE
ERROR|SFHybridViewController|Error while attempting to load web page: Error Domain=CDVWebViewDelegate Code=1 "CDVWebViewDelegate: Navigation started when state=1" 

### ISSUE THREAD

**Issue by tharrington** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#60]
When I quickly change between menu items in a popout menu I get the bootstrap error page with the following error:

>     CDVWebViewDelegate: Navigation started when state=1
>     2015-03-26 16:41:19:491 MayorApp[62832:607] ERROR|SFHybridViewController|Error while attempting to load web page: Error Domain=CDVWebViewDelegate Code=1 "CDVWebViewDelegate: Navigation started when state=1" UserInfo=0x7beca7b0 {NSLocalizedDescription=CDVWebViewDelegate: Navigation started when state=1}
>     2015-03-26 16:41:19.572 MayorApp[62832:1682320] Failed to load webpage with error: CDVWebViewDelegate: Navigation started when state=1
>     2015-03-26 16:41:19.581 MayorApp[62832:1682320] Resetting plugins due to page load.
>     2015-03-26 16:41:19.604 MayorApp[62832:1682320] Finished load of: about:blank

Looks like this occurs in SFHybridViewController. Has anyone seen this bug?

**Comment by bhariharan** [comment]
We have upgraded ```Cordova``` to the latest version in our ```unstable``` branch. If the issue still exists on ```unstable```, feel free to reopen this issue.
