### ISSUE TITLE
App crashes upon being opened on iOS 13

### ISSUE THREAD

**Issue by ftcaeappno** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#601]
Creating this ticket since #596 was closed.

Device: iPhone 8, iOS 13.5.1
We recently upgraded the SalesforceMobileSDK 10.1.0 and the app is no longer opening on iOS 13.

App is working normally on iOS 14 and 15

The crash report is attached.
[crash-report (1).txt](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/files/9610174/crash-report.1.txt)

**Comment by wmathurin** [comment]
iOS 13 is not supported by Mobile SDK 10.1.0.

Copying comment from the last ticket
> Here is the section of the documentation that lists requirements for iOS: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/ios_requirements.htm
> Mobile SDK 10.x supports iOS 14 and iOS 15 (10.2 should be compatible with iOS 16 also).
> Mobile SDK 9.x supports iOS 13 and 14 (9.2 added compatible with iOS 15 also).
> Mobile SDK 8.x supports iOS 12 and 13 (8.3 added compatibility with iOS 14 also).
