### ISSUE TITLE
What is the plan for releasing 10.2.0?

### ISSUE THREAD

**Issue by dimosmertzanidis** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#603]
@wmathurin hi! What is the plan for releasing 10.2.0?

Thanks

**Comment by dimosmertzanidis** [comment]
Team hi, do you have a plan for a 10.2.0 release? 

Thanks

**Comment by wmathurin** [comment]
Mobile SDK 10.2 was released this morning.
