### ISSUE TITLE
SOQL Query API responds 503 in iOS

### ISSUE THREAD

**Issue by akshayajeevan** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#621]
Hi,

Salesforce Mobile SDK: 10.2.0
OS: iOS

Recently we are getting status code 503 errors on the iOS version of app in China region. The error shows up intermittently and not sure what could be the reasons for this.
We are using `force.js` to query and get the data from SF. Do you know any scenarios or use-case where a queryAll API could respond like below error response -
```
error: Failed to complete operation. (com.salesforce.RestAPI.ErrorDomain 503)
"response":{"statusCode":503,"MIMEType":"text/html","headers":{"Content-Type":"text/html","Pragma":"no-cache","Content-Encoding":"gzip","Server":"AkamaiNetStorage","Content-Length":"123926"},
"suggestedFilename":"queryAll.html",
"body": [ HTML content with message - Service Not Available. This error originated from Salesforce CDN partner ]
"URL":"<domain>/services/data/v55.0/queryAll?q=SELECT Id,Username,LastName,FirstName,Name, ... FROM User WHERE ..."
"expectedContentLength":891240
```
Please help.

**Comment by wmathurin** [comment]
You might get a 503 during a scheduled downtime. Is it happening consistently?

**Comment by wmathurin** [comment]
Closing for lack of response.
