### ISSUE TITLE
Android App crashes when sessions timeout

### ISSUE THREAD

**Issue by ftcaeappno** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#628]
When the user keep the app open and stops interacting with it for 15 minutes (on salesforce session timeout is set to 15 mins), the user is automatically logged out and user is redirected to login page. iOS app works as expected.
However, on Android, the app crashes.

Steps to reproduce:

- Access the app
- Keep the app open, but do not interact with it
- Wait 15 minutes
- Navigate through the app

Device:

- Android 13 - Samsung A13

Android Logcat Logs attached
[logcat.txt](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/files/13189618/logcat.txt)

Please let me know if you need any more details.

**Comment by wmathurin** [comment]
Is it an hybrid remote or an hybrid local application?

**Comment by sinothomasAppno** [comment]
It's an hybrid local app.

**Comment by ftcaeappno** [comment]
Hi @wmathurin do you have any news over this topic?

**Comment by wmathurin** [comment]
What version of Mobile SDK are you using?
We fixed a bug around "session rehydration" in 11.1 (see https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2483).

**Comment by sinothomasAppno** [comment]
We are using salesforce-mobilesdk-cordova-plugin: 11.0.0

**Comment by wmathurin** [comment]
Could you try with 11.1 ?

**Comment by wmathurin** [comment]
Closing for lack of response to our last question.
