### ISSUE TITLE
How to call biometric auth methods from JavaScript?

### ISSUE THREAD

**Issue by jake-moritz-trifecta** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#636]
Is it possible to call the biometric authentication methods within JavaScript? I don't see any of the methods exposed in any of the JavaScript files.
 
Referring to the methods here: [https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/biometric_auth.htm](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/biometric_auth.htm)

**Comment by wmathurin** [comment]
There are not exposed through our cordova plugin at this point.
