### ISSUE TITLE
Erro when run on android

### ISSUE THREAD

**Issue by iFernandoSousa** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#67]
I make exactly the README file indicate:
cordova create TestApp
cd TestApp
cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin
cordova platform add android
cordova prepare
and then: cordova run android, but when I try run on android, I receive this error:

C:\Salesforce\Workspace\Mobile\TestApp>cordova run android
Running command: C:\Salesforce\Workspace\Mobile\TestApp\platforms\android\cordova\run.bat
WARNING : No target specified, deploying to device '9d1e844b'.
Buildfile: C:\Salesforce\Workspace\Mobile\TestApp\platforms\android\build.xml

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 24.1.2
 [checkenv] Installed at C:\Users\fsousa\AppData\Local\Android\android-sdk

-setup:
     [echo] Project Name: com.plugin.gcm.PushHandlerActivity
  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 22.0.1
     [echo] Resolving Build Target for com.plugin.gcm.PushHandlerActivity...
[gettarget] Project Target:   Android 5.0.1
[gettarget] API level:        21
     [echo] ----------
     [echo] Creating output directories if needed...
     [echo] ----------
     [echo] Resolving Dependencies for com.plugin.gcm.PushHandlerActivity...

BUILD FAILED
C:\Users\fsousa\AppData\Local\Android\android-sdk\tools\ant\build.xml:577: ../../external/cordova/framework resolve to a path with no project.properties file for project C:\Salesforce\Workspace\Mobile\TestApp\plugins\com.salesforce\src\android\libs\SalesforceSDK

Total time: 0 seconds

C:\Salesforce\Workspace\Mobile\TestApp\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "ant debug -f C:\Salesforce\Workspace\Mobile\TestApp\platforms\android\build.xml -Dout.dir=ant-build -Dgen.absolute.dir=ant-gen"
ERROR running one or more of the platforms: Error: C:\Salesforce\Workspace\Mobile\TestApp\platforms\android\cordova\run.bat: Command failed with exit code 1
You may not have the required environment or OS to run this project

C:\Salesforce\Workspace\Mobile\TestApp>

**Comment by alexndreazevedo** [comment]
Hi @iFernandoSousa. I'm have the same problems, specifically with Windows. This issue is the same to #56.

**Comment by bhariharan** [comment]
@iFernandoSousa What version of ```Mobile SDK``` are you using? There was a symlink issue in an earlier version that we have fixed in our latest release. If the issue still exists, we will track it in #56.
