### ISSUE TITLE
App crashes after PIN security screen in Salesforce SDK 3.3

### ISSUE THREAD

**Issue by AkshathaJ** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#90]
Hie

Im facing issue when I updated sales force mobile sdk from 3.0 to 3.3.

it is getting crashed with __pthread_kill + 20 
I ve done following things in terminal,

cordova plugin rm com.salesforce
cordova platform rm ios
cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin
cordova platform add ios
cordova prepare

Please let me know if i missed somewhere.

**Comment by bhariharan** [comment]
@AkshathaJ That simply means the app has crashed. You need to look at the logs to determine the cause of the crash. This forum is reserved for bugs in the ```Mobile SDK```. Please post general questions in our community [here](https://plus.google.com/u/1/communities/114225252149514546445).
