### ISSUE TITLE
duplicate symbol _sqlite3_...

### ISSUE THREAD

**Issue by sevem** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#91]
I try to use the SalesforceMobileSDK-CordovaPlugin in combination with an other plugin (https://github.com/litehelpers/Cordova-sqlite-storage). When I try to run the app I got this error message:

duplicate symbol _sqlite3_temp_directory in:
    /Develop/workspaces/MobileSDK/HybridOO/platforms/ios/build/HybridOO.build/Debug-iphonesimulator/HybridOO.build/Objects-normal/i386/sqlite3.o
    /Develop/workspaces/MobileSDK/HybridOO/platforms/ios/HybridOO/Plugins/com.salesforce/libsqlcipher.a(sqlite3.o)
ld: 192 duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I found no possibility to fix this problem.

**Comment by bhariharan** [comment]
@sevem Mobile SDK requires the ```SQLCipher``` library, which uses ```SQLite``` beneath the covers. Hence, adding the ```Cordova-sqlite-storage``` plugin will cause symbol conflicts. You can use ```SQLite``` APIs directly, since we have included ```libsqlcipher.a``` with the Mobile SDK.

**Comment by sevem** [comment]
@bhariharan Thx for your answer. But this is not a solution. How should I use the SQLite API directly when I'm using a other cordova plugin? Or do you mean I can create a SQLite connection with the SalesforceMobileSDK-CordovaPlugin? If yes, could you please give me a hint how to do that? I can't find such a functionality

**Comment by bhariharan** [comment]
@sevem You can use the plugin in conjunction, but you'll need to edit your linker paths in the project settings in ```XCode``` to link to the library you require, and exclude the duplicate symbols. It won't work out of the box.
