### ISSUE TITLE
cordova build failed 

### ISSUE THREAD

**Issue by tanaygit** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#94]
While running ---> cordova build 
==============================================================
C:\Users\kvp\AppData\Local\Android\sdk\tools\ant\build.xml:573: ../../external/c
ordova/framework resolve to a path with no project.properties file for project
 D:\Hybrid\pro7\contactsApp\plugins\com.salesforce\src\android\libs\SalesforceSDK
================================================================
Here is my versions details 

D:\Hybrid\pro7\contactsApp>ant -v
Apache Ant(TM) version 1.9.6 compiled on June 29 2015
Trying the default build file: build.xml
Buildfile: build.xml does not exist!
Build failed

D:\Hybrid\pro7\contactsApp>java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

D:\Hybrid\pro7\contactsApp>node -v
v0.12.7

D:\Hybrid\pro7\contactsApp>cordova -v
4.3.0

**Comment by wmathurin** [comment]
Please look at the similar issue (resolved):
https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/56

Please re-open if you believe your issue is different.
